using System;
using System.Drawing;
using System.Collections;
using System.ComponentModel;
using System.Windows.Forms;
using System.Data;
using QCI.QWMS;
using System.Runtime.InteropServices;
using QWMS.Common;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Data.SqlClient;
using System.Text;
using System.Drawing.Printing;
using CrystalDecisions.Shared;
using CrystalDecisions.CrystalReports.Engine;
using System.Diagnostics;

namespace QWMS
{
    /// <summary>
    /// StorageIn_OnLineIn 的摘要描述。
    /// </summary>
    public class StorageIn_IQC_InNew : System.Windows.Forms.Form
    {
        #region SystemAutoGenerated

        #region 物件宣告
        protected internal System.Windows.Forms.StatusBar stbStatus;
        private System.Windows.Forms.StatusBarPanel stsMandt;
        private System.Windows.Forms.StatusBarPanel stsUsrnm;
        private System.Windows.Forms.StatusBarPanel stsComcd;
        private System.Windows.Forms.StatusBarPanel stsWarning;
        private System.Windows.Forms.StatusBarPanel stsDate;
        private System.Windows.Forms.RadioButton rdoAdd;
        private System.Windows.Forms.RadioButton rdoNew;
        private System.Windows.Forms.GroupBox gbFunction;
        private System.Windows.Forms.GroupBox gbHeader;
        private System.Windows.Forms.ComboBox cmbWerks;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.TextBox txtLocat;
        private System.Windows.Forms.DateTimePicker dtpIndat;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.Button btnExit;
        private System.Windows.Forms.Button btnRefresh;
        private System.Windows.Forms.Button btnSave;
        private System.Windows.Forms.Label label5;
        private Label lblDataCount;
        private DataGridView dgvData;
        private ComboBox cmbLgort;
        private TextBox txtBoxID;
        private QCI.QWMS.LogData objLogData;
        private TextBox txtScannedQty;
        private Label label9;
        private DataGridView dgvSAP;
        private Label lblSAP;
        private TextBox txtMBLNR;
        private Label label6;
        private Button btnConfirm;
        private Label label8;
        private TextBox txtSanLocation;
        private System.ComponentModel.IContainer components;
        #endregion

        #region Windows Form Designer generated code
        /// <summary>
        /// 此為設計工具支援所必需的方法 - 請勿使用程式碼編輯器修改
        /// 這個方法的內容。
        /// </summary>
        private void InitializeComponent()
        {
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle5 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle6 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle4 = new System.Windows.Forms.DataGridViewCellStyle();
            this.gbFunction = new System.Windows.Forms.GroupBox();
            this.tableLayoutPanel3 = new System.Windows.Forms.TableLayoutPanel();
            this.rdoAdd = new System.Windows.Forms.RadioButton();
            this.rdoNew = new System.Windows.Forms.RadioButton();
            this.stbStatus = new System.Windows.Forms.StatusBar();
            this.stsMandt = new System.Windows.Forms.StatusBarPanel();
            this.stsComcd = new System.Windows.Forms.StatusBarPanel();
            this.stsUsrnm = new System.Windows.Forms.StatusBarPanel();
            this.stsWarning = new System.Windows.Forms.StatusBarPanel();
            this.stsDate = new System.Windows.Forms.StatusBarPanel();
            this.gbHeader = new System.Windows.Forms.GroupBox();
            this.tableLayoutPanel4 = new System.Windows.Forms.TableLayoutPanel();
            this.label8 = new System.Windows.Forms.Label();
            this.txtSanLocation = new System.Windows.Forms.TextBox();
            this.btnConfirm = new System.Windows.Forms.Button();
            this.txtMBLNR = new System.Windows.Forms.TextBox();
            this.label6 = new System.Windows.Forms.Label();
            this.label9 = new System.Windows.Forms.Label();
            this.label1 = new System.Windows.Forms.Label();
            this.label2 = new System.Windows.Forms.Label();
            this.txtScannedQty = new System.Windows.Forms.TextBox();
            this.label5 = new System.Windows.Forms.Label();
            this.label3 = new System.Windows.Forms.Label();
            this.cmbWerks = new System.Windows.Forms.ComboBox();
            this.cmbLgort = new System.Windows.Forms.ComboBox();
            this.dtpIndat = new System.Windows.Forms.DateTimePicker();
            this.txtLocat = new System.Windows.Forms.TextBox();
            this.label4 = new System.Windows.Forms.Label();
            this.txtBoxID = new System.Windows.Forms.TextBox();
            this.lblDataCount = new System.Windows.Forms.Label();
            this.dgvData = new System.Windows.Forms.DataGridView();
            this.btnExit = new System.Windows.Forms.Button();
            this.btnRefresh = new System.Windows.Forms.Button();
            this.btnSave = new System.Windows.Forms.Button();
            this.tableLayoutPanel1 = new System.Windows.Forms.TableLayoutPanel();
            this.dgvSAP = new System.Windows.Forms.DataGridView();
            this.lblSAP = new System.Windows.Forms.Label();
            this.tableLayoutPanel2 = new System.Windows.Forms.TableLayoutPanel();
            this.gbFunction.SuspendLayout();
            this.tableLayoutPanel3.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.stsMandt)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.stsComcd)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.stsUsrnm)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.stsWarning)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.stsDate)).BeginInit();
            this.gbHeader.SuspendLayout();
            this.tableLayoutPanel4.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.dgvData)).BeginInit();
            this.tableLayoutPanel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.dgvSAP)).BeginInit();
            this.tableLayoutPanel2.SuspendLayout();
            this.SuspendLayout();
            // 
            // gbFunction
            // 
            this.gbFunction.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom)
                        | System.Windows.Forms.AnchorStyles.Left)
                        | System.Windows.Forms.AnchorStyles.Right)));
            this.gbFunction.Controls.Add(this.tableLayoutPanel3);
            this.gbFunction.Font = new System.Drawing.Font("Arial", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.gbFunction.Location = new System.Drawing.Point(3, 3);
            this.gbFunction.Name = "gbFunction";
            this.gbFunction.Size = new System.Drawing.Size(227, 174);
            this.gbFunction.TabIndex = 0;
            this.gbFunction.TabStop = false;
            // 
            // tableLayoutPanel3
            // 
            this.tableLayoutPanel3.ColumnCount = 1;
            this.tableLayoutPanel3.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tableLayoutPanel3.Controls.Add(this.rdoAdd, 0, 1);
            this.tableLayoutPanel3.Controls.Add(this.rdoNew, 0, 0);
            this.tableLayoutPanel3.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tableLayoutPanel3.Location = new System.Drawing.Point(3, 18);
            this.tableLayoutPanel3.Name = "tableLayoutPanel3";
            this.tableLayoutPanel3.RowCount = 2;
            this.tableLayoutPanel3.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tableLayoutPanel3.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tableLayoutPanel3.Size = new System.Drawing.Size(221, 153);
            this.tableLayoutPanel3.TabIndex = 2;
            // 
            // rdoAdd
            // 
            this.rdoAdd.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right)));
            this.rdoAdd.Location = new System.Drawing.Point(3, 103);
            this.rdoAdd.Name = "rdoAdd";
            this.rdoAdd.Size = new System.Drawing.Size(215, 22);
            this.rdoAdd.TabIndex = 1;
            this.rdoAdd.Text = "Add In";
            this.rdoAdd.CheckedChanged += new System.EventHandler(this.rdoAdd_CheckedChanged);
            // 
            // rdoNew
            // 
            this.rdoNew.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right)));
            this.rdoNew.Location = new System.Drawing.Point(3, 25);
            this.rdoNew.Name = "rdoNew";
            this.rdoNew.Size = new System.Drawing.Size(215, 25);
            this.rdoNew.TabIndex = 0;
            this.rdoNew.Text = "New Pallet";
            this.rdoNew.CheckedChanged += new System.EventHandler(this.rdoNew_CheckedChanged);
            // 
            // stbStatus
            // 
            this.stbStatus.Font = new System.Drawing.Font("Arial", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(136)));
            this.stbStatus.Location = new System.Drawing.Point(0, 515);
            this.stbStatus.Name = "stbStatus";
            this.stbStatus.Panels.AddRange(new System.Windows.Forms.StatusBarPanel[] {
            this.stsMandt,
            this.stsComcd,
            this.stsUsrnm,
            this.stsWarning,
            this.stsDate});
            this.stbStatus.ShowPanels = true;
            this.stbStatus.Size = new System.Drawing.Size(980, 22);
            this.stbStatus.TabIndex = 28;
            this.stbStatus.Text = "Status";
            // 
            // stsMandt
            // 
            this.stsMandt.Alignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.stsMandt.Name = "stsMandt";
            this.stsMandt.Width = 40;
            // 
            // stsComcd
            // 
            this.stsComcd.Alignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.stsComcd.Name = "stsComcd";
            this.stsComcd.Width = 40;
            // 
            // stsUsrnm
            // 
            this.stsUsrnm.Alignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.stsUsrnm.Name = "stsUsrnm";
            // 
            // stsWarning
            // 
            this.stsWarning.Name = "stsWarning";
            this.stsWarning.Width = 430;
            // 
            // stsDate
            // 
            this.stsDate.Alignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.stsDate.Name = "stsDate";
            // 
            // gbHeader
            // 
            this.gbHeader.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom)
                        | System.Windows.Forms.AnchorStyles.Left)
                        | System.Windows.Forms.AnchorStyles.Right)));
            this.gbHeader.Controls.Add(this.tableLayoutPanel4);
            this.gbHeader.Font = new System.Drawing.Font("Arial", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.gbHeader.Location = new System.Drawing.Point(236, 3);
            this.gbHeader.Name = "gbHeader";
            this.gbHeader.Size = new System.Drawing.Size(695, 174);
            this.gbHeader.TabIndex = 29;
            this.gbHeader.TabStop = false;
            // 
            // tableLayoutPanel4
            // 
            this.tableLayoutPanel4.ColumnCount = 4;
            this.tableLayoutPanel4.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 150F));
            this.tableLayoutPanel4.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tableLayoutPanel4.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 149F));
            this.tableLayoutPanel4.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tableLayoutPanel4.Controls.Add(this.label8, 0, 4);
            this.tableLayoutPanel4.Controls.Add(this.txtSanLocation, 1, 4);
            this.tableLayoutPanel4.Controls.Add(this.btnConfirm, 3, 2);
            this.tableLayoutPanel4.Controls.Add(this.txtMBLNR, 3, 1);
            this.tableLayoutPanel4.Controls.Add(this.label6, 2, 1);
            this.tableLayoutPanel4.Controls.Add(this.label9, 2, 4);
            this.tableLayoutPanel4.Controls.Add(this.label1, 0, 0);
            this.tableLayoutPanel4.Controls.Add(this.label2, 2, 0);
            this.tableLayoutPanel4.Controls.Add(this.txtScannedQty, 3, 4);
            this.tableLayoutPanel4.Controls.Add(this.label5, 0, 3);
            this.tableLayoutPanel4.Controls.Add(this.label3, 0, 1);
            this.tableLayoutPanel4.Controls.Add(this.cmbWerks, 1, 0);
            this.tableLayoutPanel4.Controls.Add(this.cmbLgort, 3, 0);
            this.tableLayoutPanel4.Controls.Add(this.dtpIndat, 3, 3);
            this.tableLayoutPanel4.Controls.Add(this.txtLocat, 1, 1);
            this.tableLayoutPanel4.Controls.Add(this.label4, 2, 3);
            this.tableLayoutPanel4.Controls.Add(this.txtBoxID, 1, 3);
            this.tableLayoutPanel4.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tableLayoutPanel4.Location = new System.Drawing.Point(3, 18);
            this.tableLayoutPanel4.Name = "tableLayoutPanel4";
            this.tableLayoutPanel4.RowCount = 5;
            this.tableLayoutPanel4.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 23F));
            this.tableLayoutPanel4.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 23F));
            this.tableLayoutPanel4.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 25.98425F));
            this.tableLayoutPanel4.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 28.34646F));
            this.tableLayoutPanel4.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 23F));
            this.tableLayoutPanel4.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.tableLayoutPanel4.Size = new System.Drawing.Size(689, 153);
            this.tableLayoutPanel4.TabIndex = 19;
            // 
            // label8
            // 
            this.label8.Dock = System.Windows.Forms.DockStyle.Top;
            this.label8.Location = new System.Drawing.Point(3, 127);
            this.label8.Name = "label8";
            this.label8.Size = new System.Drawing.Size(144, 20);
            this.label8.TabIndex = 42;
            this.label8.Text = "Scan Location";
            this.label8.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            // 
            // txtSanLocation
            // 
            this.txtSanLocation.Dock = System.Windows.Forms.DockStyle.Top;
            this.txtSanLocation.Location = new System.Drawing.Point(153, 130);
            this.txtSanLocation.Name = "txtSanLocation";
            this.txtSanLocation.Size = new System.Drawing.Size(189, 22);
            this.txtSanLocation.TabIndex = 43;
            this.txtSanLocation.KeyDown += new System.Windows.Forms.KeyEventHandler(this.txtSanLocation_KeyDown);
            // 
            // btnConfirm
            // 
            this.btnConfirm.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom)
                        | System.Windows.Forms.AnchorStyles.Left)));
            this.btnConfirm.Location = new System.Drawing.Point(497, 61);
            this.btnConfirm.Name = "btnConfirm";
            this.btnConfirm.Size = new System.Drawing.Size(90, 27);
            this.btnConfirm.TabIndex = 41;
            this.btnConfirm.Text = "Confirm";
            this.btnConfirm.Click += new System.EventHandler(this.btnConfirm_Click);
            // 
            // txtMBLNR
            // 
            this.txtMBLNR.Dock = System.Windows.Forms.DockStyle.Top;
            this.txtMBLNR.Location = new System.Drawing.Point(497, 32);
            this.txtMBLNR.MaxLength = 100;
            this.txtMBLNR.Name = "txtMBLNR";
            this.txtMBLNR.Size = new System.Drawing.Size(189, 22);
            this.txtMBLNR.TabIndex = 40;
            this.txtMBLNR.DoubleClick += new System.EventHandler(this.txtMBLNR_DoubleClick);
            this.txtMBLNR.KeyPress += new System.Windows.Forms.KeyPressEventHandler(this.txtMBLNR_KeyPress);
            // 
            // label6
            // 
            this.label6.Dock = System.Windows.Forms.DockStyle.Top;
            this.label6.Location = new System.Drawing.Point(348, 29);
            this.label6.Name = "label6";
            this.label6.Size = new System.Drawing.Size(143, 22);
            this.label6.TabIndex = 39;
            this.label6.Text = "Document No.";
            this.label6.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            // 
            // label9
            // 
            this.label9.Dock = System.Windows.Forms.DockStyle.Top;
            this.label9.Location = new System.Drawing.Point(348, 127);
            this.label9.Name = "label9";
            this.label9.Size = new System.Drawing.Size(143, 22);
            this.label9.TabIndex = 38;
            this.label9.Text = "Scanned Qty";
            this.label9.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            // 
            // label1
            // 
            this.label1.Dock = System.Windows.Forms.DockStyle.Top;
            this.label1.Location = new System.Drawing.Point(3, 0);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(144, 22);
            this.label1.TabIndex = 1;
            this.label1.Text = "Plant";
            this.label1.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            // 
            // label2
            // 
            this.label2.Dock = System.Windows.Forms.DockStyle.Top;
            this.label2.Location = new System.Drawing.Point(348, 0);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(143, 22);
            this.label2.TabIndex = 2;
            this.label2.Text = "Storage";
            this.label2.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            // 
            // txtScannedQty
            // 
            this.txtScannedQty.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)
                        | System.Windows.Forms.AnchorStyles.Right)));
            this.txtScannedQty.CharacterCasing = System.Windows.Forms.CharacterCasing.Upper;
            this.txtScannedQty.Enabled = false;
            this.txtScannedQty.Location = new System.Drawing.Point(497, 130);
            this.txtScannedQty.MaxLength = 0;
            this.txtScannedQty.Name = "txtScannedQty";
            this.txtScannedQty.Size = new System.Drawing.Size(189, 22);
            this.txtScannedQty.TabIndex = 17;
            // 
            // label5
            // 
            this.label5.Dock = System.Windows.Forms.DockStyle.Top;
            this.label5.Location = new System.Drawing.Point(3, 91);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(144, 22);
            this.label5.TabIndex = 12;
            this.label5.Text = "BOX ID";
            this.label5.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            // 
            // label3
            // 
            this.label3.Dock = System.Windows.Forms.DockStyle.Top;
            this.label3.Location = new System.Drawing.Point(3, 29);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(144, 21);
            this.label3.TabIndex = 3;
            this.label3.Text = "Location";
            this.label3.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            // 
            // cmbWerks
            // 
            this.cmbWerks.Dock = System.Windows.Forms.DockStyle.Top;
            this.cmbWerks.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbWerks.Location = new System.Drawing.Point(153, 3);
            this.cmbWerks.Name = "cmbWerks";
            this.cmbWerks.Size = new System.Drawing.Size(189, 24);
            this.cmbWerks.TabIndex = 2;
            this.cmbWerks.SelectedIndexChanged += new System.EventHandler(this.cmbWerks_SelectedIndexChanged);
            // 
            // cmbLgort
            // 
            this.cmbLgort.Dock = System.Windows.Forms.DockStyle.Top;
            this.cmbLgort.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbLgort.Location = new System.Drawing.Point(497, 3);
            this.cmbLgort.Name = "cmbLgort";
            this.cmbLgort.Size = new System.Drawing.Size(189, 24);
            this.cmbLgort.TabIndex = 3;
            // 
            // dtpIndat
            // 
            this.dtpIndat.CalendarFont = new System.Drawing.Font("PMingLiU", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(136)));
            this.dtpIndat.Format = System.Windows.Forms.DateTimePickerFormat.Short;
            this.dtpIndat.Location = new System.Drawing.Point(497, 94);
            this.dtpIndat.Name = "dtpIndat";
            this.dtpIndat.Size = new System.Drawing.Size(104, 22);
            this.dtpIndat.TabIndex = 5;
            // 
            // txtLocat
            // 
            this.txtLocat.CharacterCasing = System.Windows.Forms.CharacterCasing.Upper;
            this.txtLocat.Dock = System.Windows.Forms.DockStyle.Top;
            this.txtLocat.Location = new System.Drawing.Point(153, 32);
            this.txtLocat.MaxLength = 10;
            this.txtLocat.Name = "txtLocat";
            this.txtLocat.Size = new System.Drawing.Size(189, 22);
            this.txtLocat.TabIndex = 4;
            this.txtLocat.DoubleClick += new System.EventHandler(this.txtLocat_DoubleClick);
            this.txtLocat.KeyDown += new System.Windows.Forms.KeyEventHandler(this.txtLocat_KeyDown);
            this.txtLocat.KeyPress += new System.Windows.Forms.KeyPressEventHandler(this.txtLocat_KeyPress);
            // 
            // label4
            // 
            this.label4.Dock = System.Windows.Forms.DockStyle.Top;
            this.label4.Location = new System.Drawing.Point(348, 91);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(143, 22);
            this.label4.TabIndex = 11;
            this.label4.Text = "In Date";
            this.label4.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            // 
            // txtBoxID
            // 
            this.txtBoxID.Dock = System.Windows.Forms.DockStyle.Top;
            this.txtBoxID.Location = new System.Drawing.Point(153, 94);
            this.txtBoxID.Name = "txtBoxID";
            this.txtBoxID.Size = new System.Drawing.Size(189, 22);
            this.txtBoxID.TabIndex = 35;
            this.txtBoxID.KeyDown += new System.Windows.Forms.KeyEventHandler(this.txtBoxID_KeyDown);
            // 
            // lblDataCount
            // 
            this.lblDataCount.AutoSize = true;
            this.lblDataCount.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblDataCount.Location = new System.Drawing.Point(3, 321);
            this.lblDataCount.Name = "lblDataCount";
            this.lblDataCount.Size = new System.Drawing.Size(61, 14);
            this.lblDataCount.TabIndex = 29;
            this.lblDataCount.Text = "0 records";
            // 
            // dgvData
            // 
            this.dgvData.AllowUserToAddRows = false;
            this.dgvData.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom)
                        | System.Windows.Forms.AnchorStyles.Left)
                        | System.Windows.Forms.AnchorStyles.Right)));
            dataGridViewCellStyle1.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle1.BackColor = System.Drawing.SystemColors.Control;
            dataGridViewCellStyle1.Font = new System.Drawing.Font("宋体", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(134)));
            dataGridViewCellStyle1.ForeColor = System.Drawing.SystemColors.WindowText;
            dataGridViewCellStyle1.SelectionBackColor = System.Drawing.SystemColors.Highlight;
            dataGridViewCellStyle1.SelectionForeColor = System.Drawing.SystemColors.HighlightText;
            dataGridViewCellStyle1.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.dgvData.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle1;
            this.dgvData.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.tableLayoutPanel1.SetColumnSpan(this.dgvData, 2);
            dataGridViewCellStyle5.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle5.BackColor = System.Drawing.SystemColors.Window;
            dataGridViewCellStyle5.Font = new System.Drawing.Font("宋体", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(134)));
            dataGridViewCellStyle5.ForeColor = System.Drawing.SystemColors.ControlText;
            dataGridViewCellStyle5.SelectionBackColor = System.Drawing.SystemColors.Highlight;
            dataGridViewCellStyle5.SelectionForeColor = System.Drawing.SystemColors.HighlightText;
            dataGridViewCellStyle5.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.dgvData.DefaultCellStyle = dataGridViewCellStyle5;
            this.dgvData.Location = new System.Drawing.Point(3, 339);
            this.dgvData.Name = "dgvData";
            dataGridViewCellStyle6.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle6.BackColor = System.Drawing.SystemColors.Control;
            dataGridViewCellStyle6.Font = new System.Drawing.Font("宋体", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(134)));
            dataGridViewCellStyle6.ForeColor = System.Drawing.SystemColors.WindowText;
            dataGridViewCellStyle6.SelectionBackColor = System.Drawing.SystemColors.Highlight;
            dataGridViewCellStyle6.SelectionForeColor = System.Drawing.SystemColors.HighlightText;
            dataGridViewCellStyle6.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.dgvData.RowHeadersDefaultCellStyle = dataGridViewCellStyle6;
            this.dgvData.RowTemplate.Height = 24;
            this.dgvData.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dgvData.Size = new System.Drawing.Size(928, 121);
            this.dgvData.TabIndex = 28;
            // 
            // btnExit
            // 
            this.btnExit.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.btnExit.Font = new System.Drawing.Font("Arial", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnExit.Location = new System.Drawing.Point(215, 477);
            this.btnExit.Name = "btnExit";
            this.btnExit.Size = new System.Drawing.Size(89, 30);
            this.btnExit.TabIndex = 10;
            this.btnExit.Text = "Exit";
            this.btnExit.Click += new System.EventHandler(this.btnExit_Click);
            // 
            // btnRefresh
            // 
            this.btnRefresh.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.btnRefresh.Font = new System.Drawing.Font("Arial", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnRefresh.Location = new System.Drawing.Point(119, 477);
            this.btnRefresh.Name = "btnRefresh";
            this.btnRefresh.Size = new System.Drawing.Size(89, 30);
            this.btnRefresh.TabIndex = 9;
            this.btnRefresh.Text = "Refresh";
            this.btnRefresh.Click += new System.EventHandler(this.btnRefresh_Click);
            // 
            // btnSave
            // 
            this.btnSave.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.btnSave.Enabled = false;
            this.btnSave.Font = new System.Drawing.Font("Arial", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnSave.Location = new System.Drawing.Point(23, 477);
            this.btnSave.Name = "btnSave";
            this.btnSave.Size = new System.Drawing.Size(89, 30);
            this.btnSave.TabIndex = 8;
            this.btnSave.Text = "Save";
            this.btnSave.Click += new System.EventHandler(this.btnSave_Click);
            // 
            // tableLayoutPanel1
            // 
            this.tableLayoutPanel1.ColumnCount = 2;
            this.tableLayoutPanel2.SetColumnSpan(this.tableLayoutPanel1, 4);
            this.tableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 25F));
            this.tableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 75F));
            this.tableLayoutPanel1.Controls.Add(this.dgvSAP, 0, 2);
            this.tableLayoutPanel1.Controls.Add(this.lblDataCount, 0, 3);
            this.tableLayoutPanel1.Controls.Add(this.gbHeader, 1, 0);
            this.tableLayoutPanel1.Controls.Add(this.gbFunction, 0, 0);
            this.tableLayoutPanel1.Controls.Add(this.dgvData, 0, 4);
            this.tableLayoutPanel1.Controls.Add(this.lblSAP, 0, 1);
            this.tableLayoutPanel1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tableLayoutPanel1.Location = new System.Drawing.Point(23, 8);
            this.tableLayoutPanel1.Name = "tableLayoutPanel1";
            this.tableLayoutPanel1.RowCount = 5;
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 180F));
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 15F));
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 15F));
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.tableLayoutPanel1.Size = new System.Drawing.Size(934, 463);
            this.tableLayoutPanel1.TabIndex = 32;
            // 
            // dgvSAP
            // 
            this.dgvSAP.AllowUserToAddRows = false;
            this.dgvSAP.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom)
                        | System.Windows.Forms.AnchorStyles.Left)
                        | System.Windows.Forms.AnchorStyles.Right)));
            dataGridViewCellStyle2.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle2.BackColor = System.Drawing.SystemColors.Control;
            dataGridViewCellStyle2.Font = new System.Drawing.Font("宋体", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(134)));
            dataGridViewCellStyle2.ForeColor = System.Drawing.SystemColors.WindowText;
            dataGridViewCellStyle2.SelectionBackColor = System.Drawing.SystemColors.Highlight;
            dataGridViewCellStyle2.SelectionForeColor = System.Drawing.SystemColors.HighlightText;
            dataGridViewCellStyle2.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.dgvSAP.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2;
            this.dgvSAP.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.tableLayoutPanel1.SetColumnSpan(this.dgvSAP, 2);
            dataGridViewCellStyle3.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle3.BackColor = System.Drawing.SystemColors.Window;
            dataGridViewCellStyle3.Font = new System.Drawing.Font("宋体", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(134)));
            dataGridViewCellStyle3.ForeColor = System.Drawing.SystemColors.ControlText;
            dataGridViewCellStyle3.SelectionBackColor = System.Drawing.SystemColors.Highlight;
            dataGridViewCellStyle3.SelectionForeColor = System.Drawing.SystemColors.HighlightText;
            dataGridViewCellStyle3.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.dgvSAP.DefaultCellStyle = dataGridViewCellStyle3;
            this.dgvSAP.Location = new System.Drawing.Point(3, 198);
            this.dgvSAP.Name = "dgvSAP";
            dataGridViewCellStyle4.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle4.BackColor = System.Drawing.SystemColors.Control;
            dataGridViewCellStyle4.Font = new System.Drawing.Font("宋体", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(134)));
            dataGridViewCellStyle4.ForeColor = System.Drawing.SystemColors.WindowText;
            dataGridViewCellStyle4.SelectionBackColor = System.Drawing.SystemColors.Highlight;
            dataGridViewCellStyle4.SelectionForeColor = System.Drawing.SystemColors.HighlightText;
            dataGridViewCellStyle4.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.dgvSAP.RowHeadersDefaultCellStyle = dataGridViewCellStyle4;
            this.dgvSAP.RowTemplate.Height = 24;
            this.dgvSAP.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dgvSAP.Size = new System.Drawing.Size(928, 120);
            this.dgvSAP.TabIndex = 30;
            // 
            // lblSAP
            // 
            this.lblSAP.AutoSize = true;
            this.lblSAP.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblSAP.Location = new System.Drawing.Point(3, 180);
            this.lblSAP.Name = "lblSAP";
            this.lblSAP.Size = new System.Drawing.Size(61, 14);
            this.lblSAP.TabIndex = 31;
            this.lblSAP.Text = "0 records";
            // 
            // tableLayoutPanel2
            // 
            this.tableLayoutPanel2.ColumnCount = 4;
            this.tableLayoutPanel2.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 96F));
            this.tableLayoutPanel2.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 96F));
            this.tableLayoutPanel2.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 96F));
            this.tableLayoutPanel2.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tableLayoutPanel2.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.tableLayoutPanel2.Controls.Add(this.btnSave, 0, 1);
            this.tableLayoutPanel2.Controls.Add(this.tableLayoutPanel1, 0, 0);
            this.tableLayoutPanel2.Controls.Add(this.btnExit, 2, 1);
            this.tableLayoutPanel2.Controls.Add(this.btnRefresh, 1, 1);
            this.tableLayoutPanel2.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tableLayoutPanel2.Location = new System.Drawing.Point(0, 0);
            this.tableLayoutPanel2.Name = "tableLayoutPanel2";
            this.tableLayoutPanel2.Padding = new System.Windows.Forms.Padding(20, 5, 20, 5);
            this.tableLayoutPanel2.RowCount = 2;
            this.tableLayoutPanel2.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tableLayoutPanel2.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 36F));
            this.tableLayoutPanel2.Size = new System.Drawing.Size(980, 515);
            this.tableLayoutPanel2.TabIndex = 33;
            // 
            // StorageIn_IQC_InNew
            // 
            this.AutoScaleBaseSize = new System.Drawing.Size(6, 14);
            this.ClientSize = new System.Drawing.Size(980, 537);
            this.Controls.Add(this.tableLayoutPanel2);
            this.Controls.Add(this.stbStatus);
            this.Name = "StorageIn_IQC_InNew";
            this.Text = "StorageIn_IQC_InNew";
            this.gbFunction.ResumeLayout(false);
            this.tableLayoutPanel3.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.stsMandt)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.stsComcd)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.stsUsrnm)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.stsWarning)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.stsDate)).EndInit();
            this.gbHeader.ResumeLayout(false);
            this.tableLayoutPanel4.ResumeLayout(false);
            this.tableLayoutPanel4.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.dgvData)).EndInit();
            this.tableLayoutPanel1.ResumeLayout(false);
            this.tableLayoutPanel1.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.dgvSAP)).EndInit();
            this.tableLayoutPanel2.ResumeLayout(false);
            this.ResumeLayout(false);

        }
        #endregion

        /// <summary>
        /// 清除任何使用中的資源。
        /// </summary>
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                if (components != null)
                {
                    components.Dispose();
                }
            }
            base.Dispose(disposing);
        }

        #endregion

        #region Constructor

        public StorageIn_IQC_InNew(UserInfo varUserData, string strProgid)
        {
            InitializeComponent();
            UserData = varUserData;
            Mandt = UserData.Client;
            Usrnm = UserData.UserId;
            Progid = strProgid;
            Comcd = UserData.CompanyCode;

            try
            {
                QCI.QWMS.StorageIn objStorageIn = new QCI.QWMS.StorageIn(CommonInfo.Instance.DBType, CommonInfo.Instance.DBCode.ToString(), CommonInfo.Instance.ErrType, CommonInfo.Instance.ErrCode.ToString(), UserData, Progid);
                QCI.QWMS.PlantData objPlantData = new QCI.QWMS.PlantData(UserData);
                objLogData = new QCI.QWMS.LogData(CommonInfo.Instance.DBType, CommonInfo.Instance.DBCode.ToString(), CommonInfo.Instance.ErrType, CommonInfo.Instance.ErrCode.ToString(), UserData, Werks, Lgort, Progid);
                //檢查權限
                if (!objStorageIn.CheckAuthority())
                {
                    throw new Exception("You don't have right to use this program!!");
                }
                else
                {
                    ShowStatusData();
                    ShowDdlWerks();
                    ShowDdlLgort();
                    bolDuplicate = objStorageIn.CheckDuplicatLocat();
                    if (cmbWerks.Items.Count > 0)
                    {
                        this.cmbWerks.SelectedIndex = 0;
                    }
                    if (cmbLgort.Items.Count > 0)
                    {
                        this.cmbLgort.SelectedIndex = 0;
                    }
                }

                rdoNew.Checked = true;
                txtBoxID.Enabled = false;
                txtSanLocation.Enabled = false;
                txtScannedQty.Enabled = false;
                //txtLoCod.Enabled = false;
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }

        #endregion

        #region DataMember

        #region 變數宣告
        public string strMandt = "";
        public string strUsrnm = "";
        public string strWerks = "";
        public string strLgort = "";
        public string strProgid = "";
        public string strMatnr = "";
        public string strMblnr = "";
        public string strType = "";
        public string strInsmk = "";
        public string strSttyp = "";
        public string strLotyp = "";
        public string strCtbto = "";
        public string strRegon = "";
        public string strMachine = "";
        public string strComcd = "";
        public bool bolDuplicate = false;
        public DataTable dtData = new DataTable();
        UserInfo UserData = new UserInfo();
        private DataTable dtTmpData = new DataTable();
        private DataTable dtCombineData = new DataTable();
        private DataTable dtLocat = new DataTable();
        private TableLayoutPanel tableLayoutPanel1;
        private TableLayoutPanel tableLayoutPanel2;
        private TableLayoutPanel tableLayoutPanel3;
        private TableLayoutPanel tableLayoutPanel4;

        int intScanQty = 0;
        private DataTable dtStorageIn = new DataTable();
        ArrayList aryMblnr = new ArrayList();
        DataTable dtVBELN = new DataTable();
        int intTotalAlqty = 0;
        #endregion

        #region 變數
        public ArrayList Mblnr
        {
            get
            {
                return aryMblnr;
            }
            set
            {
                aryMblnr = value;
            }
        }

        public string Mandt
        {
            get
            {
                return strMandt;
            }
            set
            {
                strMandt = value;
            }
        }

        public string Usrnm
        {
            get
            {
                return strUsrnm;
            }
            set
            {
                strUsrnm = value;
            }
        }

        public string Progid
        {
            get
            {
                return strProgid;
            }
            set
            {
                strProgid = value;
            }
        }

        public string Werks
        {
            get
            {
                return strWerks;
            }
            set
            {
                strWerks = value;
            }
        }

        public string Lgort
        {
            get
            {
                return strLgort;
            }
            set
            {
                strLgort = value;
            }
        }

        public string Locat
        {
            get
            {
                return this.txtLocat.Text.Trim();
            }
            set
            {
                this.txtLocat.Text = value;
            }
        }

        public string Type
        {
            get
            {
                return strType;
            }
            set
            {
                strType = value;
            }
        }

        public string Insmk
        {
            get
            {
                return strInsmk;
            }
            set
            {
                strInsmk = value;
            }
        }

        public string Sttyp
        {
            get
            {
                return strSttyp;
            }
            set
            {
                strSttyp = value;
            }
        }

        public string Lotyp
        {
            get
            {
                return strLotyp;
            }
            set
            {
                strLotyp = value;
            }
        }

        public string Ctbto
        {
            get
            {
                return strCtbto;
            }
            set
            {
                strCtbto = value;
            }
        }

        public string Regon
        {
            get
            {
                return strRegon;
            }
            set
            {
                strRegon = value;
            }
        }

        public string Machine
        {
            get
            {
                return strMachine;
            }
            set
            {
                strMachine = value;
            }
        }

        public DataTable Data
        {
            get
            {
                return dtData;
            }
            set
            {
                dtData = value;
            }
        }

        public bool Duplicate
        {
            get
            {
                return bolDuplicate;
            }
            set
            {
                bolDuplicate = value;
            }
        }

        public string Comcd
        {
            get
            {
                return strComcd;
            }
            set
            {
                strComcd = value;
            }
        }
        #endregion

        #endregion

        #region MemberFunction

        private void ShowStatusData()
        {
            this.stsDate.Text = DateTime.Now.ToString("yyyy/MM/dd");
            this.stsMandt.Text = Mandt;
            this.stsUsrnm.Text = Usrnm;
            this.stsComcd.Text = Comcd;
        }

        private void ShowDdlWerks()
        {
            DataTable dtTemp = new DataTable();
            try
            {
                QCI.QWMS.Authority objAuthority = new QCI.QWMS.Authority(UserData);
                cmbWerks.Items.Clear();
                dtTemp = objAuthority.CheckPlantAuthority();
                for (int i = 0; i < dtTemp.Rows.Count; i++)
                {
                    cmbWerks.Items.Add(dtTemp.Rows[i]["F_TEXT"].ToString());
                }
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message + "<-ShowDdlWerks()");
            }
        }

        private void ShowDdlLgort()
        {
            try
            {
                stsWarning.Text = "";
                DataTable dtTemp = new DataTable();
                QCI.QWMS.Authority objAuthority = new QCI.QWMS.Authority(UserData);
                if (cmbWerks.SelectedIndex != -1)
                {
                    strWerks = cmbWerks.Items[cmbWerks.SelectedIndex].ToString();
                    dtTemp = objAuthority.CheckLgortAuthority(strWerks);
                }
                else
                {
                    dtTemp = objAuthority.CheckLgortAuthority();
                }
                if (cmbLgort.SelectedIndex != -1)
                {
                    strLgort = cmbLgort.Items[cmbLgort.SelectedIndex].ToString();
                }
                else
                {
                    cmbLgort.Items.Clear();
                }

                if (dtTemp.Rows.Count == 0)
                {
                    cmbLgort.Items.Clear();
                    strLgort = "";
                }
                else
                {
                    cmbLgort.Items.Clear();
                    for (int i = 0; i < dtTemp.Rows.Count; i++)
                    {
                        cmbLgort.Items.Add(dtTemp.Rows[i]["F_TEXT"].ToString());
                        if (dtTemp.Rows[i]["F_TEXT"].ToString() == strLgort && strLgort != "")
                        {
                            cmbLgort.SelectedIndex = i;
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message + "<-ShowDdlLgort()");
            }
        }

        private void ShowDdlLgort(string varLogort)
        {
            try
            {
                stsWarning.Text = "";
                DataTable dtTemp = new DataTable();
                QCI.QWMS.Authority objAuthority = new QCI.QWMS.Authority(UserData);
                if (cmbWerks.SelectedIndex != -1)
                {
                    strWerks = cmbWerks.Items[cmbWerks.SelectedIndex].ToString();
                    dtTemp = objAuthority.CheckLgortWithAuth(strWerks, varLogort);
                    if (dtTemp.Rows.Count == 0)
                    {
                        MessageBox.Show("无该仓别入库权限！");
                        return;
                    }
                }
                else
                {
                    dtTemp = objAuthority.CheckLgortWithAuth(strWerks, varLogort);
                    if (dtTemp.Rows.Count == 0)
                    {
                        MessageBox.Show("无该仓别入库权限！");
                        return;
                    }
                }
                if (cmbLgort.SelectedIndex != -1)
                {
                    strLgort = cmbLgort.Items[cmbLgort.SelectedIndex].ToString();
                }
                else
                {
                    cmbLgort.Items.Clear();
                }

                if (dtTemp.Rows.Count == 0)
                {
                    cmbLgort.Items.Clear();
                    strLgort = "";
                }
                else
                {
                    cmbLgort.Items.Clear();
                    for (int i = 0; i < dtTemp.Rows.Count; i++)
                    {
                        cmbLgort.Items.Add(dtTemp.Rows[i]["CTRLC1"].ToString());
                    }
                    cmbLgort.SelectedIndex = 0;

                }
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message + "<-ShowDdlLgort()");
            }
        }

        public void ShowDataGrid()
        {
            this.dgvData.AutoGenerateColumns = false;
            this.dgvData.Columns.Clear();
            this.dgvData.ColumnHeadersHeight = 30;
            try
            {
                DataGridViewCheckBoxColumn dgvcChecked = new DataGridViewCheckBoxColumn();
                dgvcChecked.DataPropertyName = "CHKED";
                dgvcChecked.ReadOnly = true;
                this.dgvData.Columns.Add(dgvcChecked);

                DataGridViewTextBoxColumn dgvcMatnr = new DataGridViewTextBoxColumn();
                dgvcMatnr.DataPropertyName = "MATNR";
                dgvcMatnr.HeaderText = "Part No";
                dgvcMatnr.Width = 90;
                dgvcMatnr.ReadOnly = true;
                this.dgvData.Columns.Add(dgvcMatnr);

                DataGridViewTextBoxColumn boxidStyle = new DataGridViewTextBoxColumn();
                boxidStyle.DataPropertyName = "BOXID";
                boxidStyle.HeaderText = "Box ID";
                boxidStyle.Width = 120;
                boxidStyle.ReadOnly = true;
                this.dgvData.Columns.Add(boxidStyle);

                DataGridViewTextBoxColumn dgvcVbeln = new DataGridViewTextBoxColumn();
                dgvcVbeln.DataPropertyName = "VBELN";
                dgvcVbeln.HeaderText = "EC No";
                dgvcVbeln.Width = 120;
                dgvcVbeln.ReadOnly = true;
                this.dgvData.Columns.Add(dgvcVbeln);



                //良品
                DataGridViewTextBoxColumn dgvcMenge = new DataGridViewTextBoxColumn();
                dgvcMenge.DataPropertyName = "GQTY";
                dgvcMenge.HeaderText = "Un-Store In Qty(Good)";
                dgvcMenge.Width = 120;
                dgvcMenge.ReadOnly = true;
                this.dgvData.Columns.Add(dgvcMenge);

                DataGridViewTextBoxColumn dgvcAlqty = new DataGridViewTextBoxColumn();
                dgvcAlqty.DataPropertyName = "ALGQTY";
                dgvcAlqty.HeaderText = "Storage In Qty(Good)";
                dgvcAlqty.Width = 120;
                dgvcAlqty.ReadOnly = true;
                this.dgvData.Columns.Add(dgvcAlqty);

                //不良品
                DataGridViewTextBoxColumn dgvcReject = new DataGridViewTextBoxColumn();
                dgvcReject.DataPropertyName = "SQTY";
                dgvcReject.HeaderText = "Un-Store In Qty(Reject)";
                dgvcReject.Width = 120;
                dgvcReject.ReadOnly = true;
                this.dgvData.Columns.Add(dgvcReject);

                DataGridViewTextBoxColumn dgvcAlsqty = new DataGridViewTextBoxColumn();
                dgvcAlsqty.DataPropertyName = "ALSQTY";
                dgvcAlsqty.HeaderText = "Storage In Qty(Reject)";
                dgvcAlsqty.Width = 120;
                dgvcAlsqty.ReadOnly = true;
                this.dgvData.Columns.Add(dgvcAlsqty);

                DataGridViewTextBoxColumn dgvcLotCode = new DataGridViewTextBoxColumn();
                dgvcLotCode.DataPropertyName = "LotCode";
                dgvcLotCode.HeaderText = "LotCode";
                dgvcLotCode.Width = 50;
                dgvcLotCode.ReadOnly = true;
                this.dgvData.Columns.Add(dgvcLotCode);

                DataGridViewTextBoxColumn dgvcrmak1 = new DataGridViewTextBoxColumn();
                dgvcrmak1.DataPropertyName = "RMAK1";
                dgvcrmak1.HeaderText = "Remark";
                dgvcrmak1.Width = 150;
                dgvcrmak1.ReadOnly = true;
                this.dgvData.Columns.Add(dgvcrmak1);

                DataGridViewTextBoxColumn dgvcIndat = new DataGridViewTextBoxColumn();
                dgvcIndat.DataPropertyName = "INDAT";
                dgvcIndat.HeaderText = "Store In Date";
                dgvcIndat.Width = 90;
                dgvcIndat.ReadOnly = true;
                this.dgvData.Columns.Add(dgvcIndat);

                dgvData.DataSource = dtData;
                lblDataCount.Text = dtData.Rows.Count.ToString() + " records";
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message + "<-ShowDataGrid()");
            }
        }

        private void SetbtnSaveProcess()
        {
            this.btnSave.Enabled = false;
        }

        private void SetbtnSaveException()
        {
            this.btnSave.Enabled = true;
        }

        #region 初始化 DataTable
        private void GetDefaultTable()
        {
            if (Data.Rows.Count == 0)
            {
                Data = new DataTable();
                Data.Columns.Add("CHKED", typeof(Boolean));
                Data.Columns.Add("MANDT", Type.GetType());
                Data.Columns.Add("COMCD", Type.GetType());
                Data.Columns.Add("WERKS", Type.GetType());
                Data.Columns.Add("LGORT", Type.GetType());
                Data.Columns.Add("LOCAT", Type.GetType());
                Data.Columns.Add("VBELN", Type.GetType());
                Data.Columns.Add("BOXID", Type.GetType());
                Data.Columns.Add("MATNR", Type.GetType());
                Data.Columns.Add("INSMK", Type.GetType());
                Data.Columns.Add("GQTY", Type.GetType());
                Data.Columns.Add("ALGQTY", Type.GetType());
                Data.Columns.Add("SQTY", Type.GetType());
                Data.Columns.Add("ALSQTY", Type.GetType());
                Data.Columns.Add("TOTALQTY", Type.GetType());
                Data.Columns.Add("INDAT", Type.GetType());
                Data.Columns.Add("RMAK1", Type.GetType());
                Data.Columns.Add("LotCode", Type.GetType());

                DataColumn[] dcPrimaryKey = new DataColumn[4];
                dcPrimaryKey[0] = Data.Columns["VBELN"];
                dcPrimaryKey[1] = Data.Columns["MATNR"];
                dcPrimaryKey[2] = Data.Columns["BOXID"];

                Data.PrimaryKey = dcPrimaryKey;
            }
        }
        #endregion

        #region 填值到DataTable
        private void SetDefaultValue(DataTable dtTmpData)
        {
            foreach (DataRow tmpRow in dtTmpData.Rows)
            {
                DataRow drRow = Data.NewRow();

                drRow["MANDT"] = tmpRow["MANDT"].ToString();
                drRow["COMCD"] = tmpRow["COMCD"].ToString();
                drRow["WERKS"] = tmpRow["WERKS"].ToString();
                drRow["LGORT"] = tmpRow["LGORT"].ToString();
                drRow["LOCAT"] = tmpRow["LOCAT"].ToString();
                drRow["VBELN"] = tmpRow["VBELN"].ToString();
                drRow["BOXID"] = tmpRow["BOXID"].ToString();
                drRow["MATNR"] = tmpRow["MATNR"].ToString();
                drRow["INSMK"] = tmpRow["INSMK"].ToString();
                //良品
                drRow["GQTY"] = tmpRow["GQTY"].ToString();
                drRow["ALGQTY"] = tmpRow["GQTY"].ToString();
                //不良品
                drRow["SQTY"] = tmpRow["SQTY"].ToString();
                drRow["ALSQTY"] = tmpRow["SQTY"].ToString();
                drRow["TOTALQTY"] = tmpRow["TOTALQTY"].ToString();
                drRow["INDAT"] = tmpRow["INDAT"].ToString();
                drRow["RMAK1"] = string.Empty;
                drRow["LotCode"] = tmpRow["LotCode"].ToString();

                Data.Rows.Add(drRow);
            }
        }
        #endregion

        #region 初始化 dtCombineData
        private void GetCombineDataTable()
        {
            if (dtCombineData.Rows.Count == 0)
            {
                dtCombineData = new DataTable();
                dtCombineData.Columns.Add("MANDT", Type.GetType());
                dtCombineData.Columns.Add("COMCD", Type.GetType());
                dtCombineData.Columns.Add("WERKS", Type.GetType());
                dtCombineData.Columns.Add("LGORT", Type.GetType());
                dtCombineData.Columns.Add("LOCAT", Type.GetType());
                dtCombineData.Columns.Add("MBLNR", Type.GetType());
                dtCombineData.Columns.Add("BOXID", Type.GetType());
                dtCombineData.Columns.Add("MATNR", Type.GetType());
                dtCombineData.Columns.Add("INSMK", Type.GetType());
                dtCombineData.Columns.Add("ALGQTY", Type.GetType());
                dtCombineData.Columns.Add("LOCOD", Type.GetType());

                DataColumn[] dcPrimaryKey = new DataColumn[4];
                dcPrimaryKey[0] = dtCombineData.Columns["MBLNR"];
                dcPrimaryKey[1] = dtCombineData.Columns["BOXID"];
                dcPrimaryKey[2] = dtCombineData.Columns["MATNR"];
                dcPrimaryKey[3] = dtCombineData.Columns["INSMK"];
                dtCombineData.PrimaryKey = dcPrimaryKey;
            }
        }
        #endregion

        //设置控件状态
        private void SetControlState(bool bolBeforeConfirm)
        {

            this.cmbWerks.Enabled = bolBeforeConfirm;
            this.cmbLgort.Enabled = bolBeforeConfirm;
            this.dtpIndat.Enabled = bolBeforeConfirm;

            // this.txtLocat.Enabled = false;
            this.txtBoxID.Enabled = bolBeforeConfirm;
            this.txtScannedQty.Enabled = false;
        }

        public void ShowInSourceDataGrid()
        {
            this.dgvSAP.AutoGenerateColumns = false;
            this.dgvSAP.Columns.Clear();
            try
            {
                DataGridViewTextBoxColumn dgvcLocat = new DataGridViewTextBoxColumn();
                dgvcLocat.DataPropertyName = "LOCAT";
                dgvcLocat.HeaderText = "Location";
                dgvcLocat.Width = 90;
                dgvcLocat.ReadOnly = true;
                this.dgvSAP.Columns.Add(dgvcLocat);

                DataGridViewTextBoxColumn dgvcMblnr = new DataGridViewTextBoxColumn();
                dgvcMblnr.DataPropertyName = "MBLNR";
                dgvcMblnr.HeaderText = "Document No";
                dgvcMblnr.Width = 90;
                dgvcMblnr.ReadOnly = true;
                this.dgvSAP.Columns.Add(dgvcMblnr);

                DataGridViewTextBoxColumn dgvcZeile = new DataGridViewTextBoxColumn();
                dgvcZeile.DataPropertyName = "ZEILE";
                dgvcZeile.HeaderText = "Document Item";
                dgvcZeile.Width = 90;
                dgvcZeile.ReadOnly = true;
                this.dgvSAP.Columns.Add(dgvcZeile);

                DataGridViewTextBoxColumn dgvcBwart = new DataGridViewTextBoxColumn();
                dgvcBwart.DataPropertyName = "BWART";
                dgvcBwart.HeaderText = "Type";
                dgvcBwart.Width = 90;
                dgvcBwart.ReadOnly = true;
                this.dgvSAP.Columns.Add(dgvcBwart);

                DataGridViewTextBoxColumn dgvcMatnr = new DataGridViewTextBoxColumn();
                dgvcMatnr.DataPropertyName = "MATNR";
                dgvcMatnr.HeaderText = "Part No";
                dgvcMatnr.Width = 90;
                dgvcMatnr.ReadOnly = true;
                this.dgvSAP.Columns.Add(dgvcMatnr);

                DataGridViewTextBoxColumn dgvcKdmat = new DataGridViewTextBoxColumn();
                dgvcKdmat.DataPropertyName = "KDMAT";
                dgvcKdmat.HeaderText = "Customer P/N";
                dgvcKdmat.ReadOnly = true;
                this.dgvSAP.Columns.Add(dgvcKdmat);



                DataGridViewTextBoxColumn dgvcInsmk = new DataGridViewTextBoxColumn();
                dgvcInsmk.DataPropertyName = "INSMK";
                dgvcInsmk.HeaderText = "Stock";
                dgvcInsmk.Width = 50;
                dgvcInsmk.ReadOnly = true;
                this.dgvSAP.Columns.Add(dgvcInsmk);

                DataGridViewTextBoxColumn dgvcCharg = new DataGridViewTextBoxColumn();
                dgvcCharg.DataPropertyName = "CHARG";
                dgvcCharg.HeaderText = "Version";
                dgvcCharg.Width = 60;
                dgvcCharg.ReadOnly = true;
                this.dgvSAP.Columns.Add(dgvcCharg);

                DataGridViewTextBoxColumn dgvcLifnr = new DataGridViewTextBoxColumn();
                dgvcLifnr.DataPropertyName = "LIFNR";
                dgvcLifnr.HeaderText = "Vendor";
                dgvcLifnr.ReadOnly = true;
                this.dgvSAP.Columns.Add(dgvcLifnr);

                DataGridViewTextBoxColumn dgvcEbeln = new DataGridViewTextBoxColumn();
                dgvcEbeln.DataPropertyName = "EBELN";
                dgvcEbeln.HeaderText = "PO No";
                dgvcEbeln.ReadOnly = true;
                this.dgvSAP.Columns.Add(dgvcEbeln);

                DataGridViewTextBoxColumn dgvcMenge = new DataGridViewTextBoxColumn();
                dgvcMenge.DataPropertyName = "MENGE";
                dgvcMenge.HeaderText = "Un-Store In Qty";
                dgvcMenge.Width = 90;
                dgvcMenge.ReadOnly = true;
                this.dgvSAP.Columns.Add(dgvcMenge);

                DataGridViewTextBoxColumn dgvcAlqty = new DataGridViewTextBoxColumn();
                dgvcAlqty.DataPropertyName = "ALQTY";
                dgvcAlqty.HeaderText = "Storage In Qty";
                dgvcAlqty.Width = 90;
                dgvcAlqty.ReadOnly = true;
                this.dgvSAP.Columns.Add(dgvcAlqty);

                DataGridViewTextBoxColumn dgvcKostl = new DataGridViewTextBoxColumn();
                dgvcKostl.DataPropertyName = "KOSTL";
                dgvcKostl.HeaderText = "Dept No.";
                dgvcKostl.ReadOnly = true;
                this.dgvSAP.Columns.Add(dgvcKostl);

                DataGridViewTextBoxColumn dgvcArbpl = new DataGridViewTextBoxColumn();
                dgvcArbpl.DataPropertyName = "ARBPL";
                dgvcArbpl.HeaderText = "PD Line";
                dgvcArbpl.ReadOnly = true;
                this.dgvSAP.Columns.Add(dgvcArbpl);

                DataGridViewTextBoxColumn dgvcTrntp = new DataGridViewTextBoxColumn();
                dgvcTrntp.DataPropertyName = "TRNTP";
                dgvcTrntp.HeaderText = "Trn-Type";
                dgvcTrntp.ReadOnly = true;
                this.dgvSAP.Columns.Add(dgvcTrntp);

                DataGridViewTextBoxColumn dgvcInspt = new DataGridViewTextBoxColumn();
                dgvcInspt.DataPropertyName = "INSPT";
                dgvcInspt.HeaderText = "Insp.Lot No.";
                dgvcInspt.ReadOnly = true;
                this.dgvSAP.Columns.Add(dgvcInspt);

                DataGridViewTextBoxColumn dgvcIndat = new DataGridViewTextBoxColumn();
                dgvcIndat.DataPropertyName = "INDAT";
                dgvcIndat.HeaderText = "Store In Date";
                dgvcIndat.ReadOnly = true;
                this.dgvSAP.Columns.Add(dgvcIndat);

                //DataGridViewTextBoxColumn dgvcLocod = new DataGridViewTextBoxColumn();
                //dgvcLocod.DataPropertyName = "LOCOD";
                //dgvcLocod.HeaderText = "LotCode";
                //dgvcLocod.ReadOnly = true;
                //this.dgvSAP.Columns.Add(dgvcLocod);

                DataGridViewTextBoxColumn dgvcDacod = new DataGridViewTextBoxColumn();
                dgvcDacod.DataPropertyName = "DACOD";
                dgvcDacod.HeaderText = "DateCode";
                dgvcDacod.ReadOnly = true;
                this.dgvSAP.Columns.Add(dgvcDacod);

                DataGridViewTextBoxColumn dgvcVedat = new DataGridViewTextBoxColumn();
                dgvcVedat.DataPropertyName = "VEDAT";
                dgvcVedat.HeaderText = "Vendor Manufactured Date";
                dgvcVedat.ReadOnly = true;
                this.dgvSAP.Columns.Add(dgvcVedat);

                dgvSAP.DataSource = dtStorageIn;
                lblSAP.Text = dtStorageIn.Rows.Count.ToString() + " records";
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message + "<-ShowInSourceDataGrid()");
            }
        }

        #endregion

        #region Event

        private void cmbWerks_SelectedIndexChanged(object sender, System.EventArgs e)
        {
            stsWarning.Text = "";
            ShowDdlLgort();
        }

        private void txtLocat_DoubleClick(object sender, System.EventArgs e)
        {
            try
            {
                if (cmbWerks.SelectedIndex != -1)
                {
                    Werks = cmbWerks.Items[cmbWerks.SelectedIndex].ToString();
                }
                else
                {
                    Werks = "";
                }

                if (cmbLgort.SelectedIndex != -1)
                {
                    Lgort = cmbLgort.Items[cmbLgort.SelectedIndex].ToString();
                }
                else
                {
                    Lgort = "";
                }

                if (Werks == "" || Lgort == "")
                {
                    stsWarning.Text = "Plant and storage can't be empty!!";
                    return;
                }
                else
                {
                    StorageIn_LocationSelect objStorageIn_LocationSelect = new StorageIn_LocationSelect(UserData, Progid, Werks, Lgort, Type);
                    objStorageIn_LocationSelect.ShowDialog();
                    txtLocat.Text = objStorageIn_LocationSelect.Locat;
                }
            }
            catch (Exception ex)
            {
                stsWarning.Text = ex.Message;
                return;
            }
        }

        #region txtLocat_KeyPress
        private void txtLocat_KeyPress(object sender, System.Windows.Forms.KeyPressEventArgs e)
        {
            //
        }
        #endregion

        #region txtLocat_KeyDown
        private void txtLocat_KeyDown(object sender, KeyEventArgs e)
        {
            //#region 將Location填回CombineData中
            //foreach (DataRow rsTmpRow in this.dtCombineData.Rows)
            //{
            //    rsTmpRow["LOCAT"] = this.txtLocat.Text.Trim();
            //}
            //this.dtCombineData.AcceptChanges();
            //#endregion
        }
        #endregion

        #region rdoNew_CheckedChanged

        private void rdoNew_CheckedChanged(object sender, System.EventArgs e)
        {
            stsWarning.Text = string.Empty;
            strType = "NEW";
            Type = strType;
        }

        #endregion

        #region rdoAdd_CheckedChanged

        private void rdoAdd_CheckedChanged(object sender, System.EventArgs e)
        {
            stsWarning.Text = string.Empty;
            strType = "ADD";
            Type = strType;
            txtLocat.Enabled = true;
        }

        #endregion

        #region txtBoxID_KeyDown
        private void txtBoxID_KeyDown(object sender, System.Windows.Forms.KeyEventArgs e)
        {

            #region 變數宣告
            stsWarning.Text = string.Empty;
            DataTable dtTemp = new DataTable();
            QCI.QWMS.SapData objSapData = new QCI.QWMS.SapData(CommonInfo.Instance.DBType, CommonInfo.Instance.DBCode.ToString(), CommonInfo.Instance.ErrType, CommonInfo.Instance.ErrCode.ToString(), UserData, cmbWerks.Text.Trim(), Lgort);
            string strECNo = "";
            string strMatnr = "";
            #endregion

            if (e.KeyCode == System.Windows.Forms.Keys.Enter)
            {
                try
                {
                    QCI.QWMS.StorageIn objStorageIn = new QCI.QWMS.StorageIn(CommonInfo.Instance.DBType, CommonInfo.Instance.DBCode.ToString(), CommonInfo.Instance.ErrType, CommonInfo.Instance.ErrCode.ToString(), UserData, Werks, Lgort, "", Progid);
                    DataTable dtbox = new DataTable();

                    #region Valid Code

                    #region BOXID 存在性

                    string strBoxID = txtBoxID.Text.Trim().ToUpper();
                    if (string.IsNullOrEmpty(strBoxID))
                    {
                        throw new Exception("Box ID 不能为空!!");
                    }

                    #endregion

                    #region ECBOX 数据存在性

                    //ECBOX
                    dtbox = objStorageIn.QueryECBox(Werks,Lgort,txtBoxID.Text.Trim().ToUpper());
                    if (dtbox.Rows.Count > 0)
                    {
                        strECNo = dtbox.Rows[0]["VBELN"].ToString().Trim();
                        strMatnr = dtbox.Rows[0]["MATNR"].ToString().Trim();
                        if (dtbox.Rows[0]["FLAGE"].ToString().Trim() == "Y")
                        {
                            Sound.Play(@"Sound\ERROR.wav");
                            throw new Exception("BOX ID：" + txtBoxID.Text.Trim() + "已入库!!");
                        }
                        ShowDdlLgort(dtbox.Rows[0]["LGORT"].ToString().Trim());
                    }
                    else
                    {
                        Sound.Play(@"Sound\ERROR.wav");
                        throw new Exception("无BOX资料!!");
                    }

                    #endregion

                    #region Plant/Storage 存在性

                    //Plant/Storage不允许为空
                    strWerks = Convert.ToString(cmbWerks.Items[cmbWerks.SelectedIndex]);
                    strLgort = Convert.ToString(cmbLgort.Items[cmbLgort.SelectedIndex]);

                    if (string.IsNullOrEmpty(Werks) || string.IsNullOrEmpty(Lgort))
                    {
                        throw new Exception("Plant 和 storage 不能为空!!");
                    }

                    //Storage必须有数据
                    QCI.QWMS.PlantData objPlantData = new QCI.QWMS.PlantData(UserData);
                    dtTemp = objPlantData.GetPlantStorageData("LGORT", strWerks, strLgort);
                    if (dtTemp.Rows.Count >= 1)
                    {
                        strSttyp = dtTemp.Rows[0]["CTRLC4"].ToString().ToUpper();
                        strLotyp = dtTemp.Rows[0]["CTRLC5"].ToString().ToUpper();
                    }
                    else
                    {
                        throw new Exception("没有 storage 数据!!");
                    }

                    #endregion

                    #region ECInfo

                    if (strECNo.ToUpper() != dtVBELN.Rows[0]["VBELN"].ToString().ToUpper())
                    {
                        Sound.Play(@"sound\error.wav");
                        throw new Exception("扫入的BOX与扣帐单号不匹配!!");
                    }
                    if (strMatnr.ToUpper() != dtVBELN.Rows[0]["MATNR"].ToString().ToUpper())
                    {
                        Sound.Play(@"sound\error.wav");
                        throw new Exception("扫入的料号与扣帐单号不匹配!!");
                    }
                    #endregion

                    #region DataGridView 初始化

                    if (Data.Rows.Count == 0)
                    {
                        dtTmpData = new DataTable();
                        //ECBOX Data
                        dtTmpData = objStorageIn.QueryECBoxByECNo(Werks, Lgort, txtLocat.Text.Trim(), dtpIndat.Value.ToString("yyyyMMdd"), strECNo, Insmk, strMatnr);

                        if (dtTmpData != null && dtTmpData.Rows.Count > 0)
                        {
                            //初始化 DataTable
                            GetDefaultTable();
                            //填值到DataTable
                            SetDefaultValue(dtTmpData);

                            ShowDataGrid();
                        }
                        else
                        {
                            txtBoxID.Text = string.Empty;
                            Sound.Play(@"Sound\ERROR.wav");
                            throw new Exception("无数据!!");
                        }
                    }

                    #endregion

                    #region 单笔BOXID是否已经刷入/是否存在
                    int tempQty = 0;
                    foreach (DataGridViewRow dataGridRow in dgvData.Rows)
                    {
                        dataGridRow.DefaultCellStyle.BackColor = Color.Silver;
                        if (txtBoxID.Text.Trim().ToUpper() == dataGridRow.Cells[2].Value.ToString().ToUpper())
                        {

                            if (dataGridRow.Cells[0].Value.ToString() == "True")
                            {
                                Sound.Play(@"Sound\ERROR.wav");
                                throw new Exception("BOX ID 已经扫过!!");
                            }
                            else
                            {
                                tempQty += Int32.Parse(dataGridRow.Cells[4].Value.ToString());
                                if (intTotalAlqty >= tempQty)
                                {
                                    #region 修改入库单据数量
                                    //本次待入库数量
                                    int intNowInQty = tempQty;
                                    foreach (DataRow dr in dtStorageIn.Rows)
                                    {
                                        if (intNowInQty == 0) 
                                            break;

                                        if (dr["MENGE"].ToString() != dr["ALQTY"].ToString())
                                        {
                                            //可入库数量
                                            int intCanStorageInQty = Convert.ToInt32(dr["MENGE"].ToString()) - Convert.ToInt32(dr["ALQTY"].ToString());
                                            if (intCanStorageInQty > 0)
                                            {
                                                //WHLOG异动记录
                                                if (dtCombineData.Rows.Count == 0)
                                                    GetCombineDataTable();

                                                DataRow drRow = dtCombineData.NewRow();

                                                drRow["MANDT"] = Mandt;
                                                drRow["COMCD"] = Comcd;
                                                drRow["WERKS"] = dr["WERKS"].ToString();
                                                drRow["LGORT"] = dr["LGORT"].ToString();
                                                drRow["LOCAT"] = txtLocat.Text.Trim();
                                                drRow["MBLNR"] = dr["MBLNR"].ToString();
                                                drRow["BOXID"] = dataGridRow.Cells[2].Value.ToString().ToUpper();
                                                drRow["MATNR"] = dr["MATNR"].ToString();
                                                drRow["INSMK"] = dr["INSMK"].ToString();
                                                
                                                if (intNowInQty > intCanStorageInQty)
                                                {
                                                    drRow["ALGQTY"] = intCanStorageInQty;
                                                    dr["ALQTY"] = Convert.ToInt32(dr["ALQTY"].ToString()) + intCanStorageInQty;
                                                    intNowInQty = intNowInQty - intCanStorageInQty;
                                                }
                                                else
                                                {
                                                    drRow["ALGQTY"] = intNowInQty;
                                                    dr["ALQTY"] = Convert.ToInt32(dr["ALQTY"].ToString()) + intNowInQty;
                                                    intNowInQty = 0;
                                                }

                                                dtCombineData.Rows.Add(drRow);
                                            }
                                        }
                                    }
                                    #endregion

                                    intTotalAlqty = intTotalAlqty - tempQty;
                                    dataGridRow.Cells[0].Value = true;
                                    dataGridRow.DefaultCellStyle.BackColor = Color.Blue;
                                }
                                else
                                {
                                    Sound.Play(@"Sound\ERROR.wav");
                                    throw new Exception("SAP单据数量不足!!");
                                }
                            }
                        }
                    }

                    if (tempQty == 0)
                    {
                        throw new Exception("Box ID 不存在!!!");
                    }
                    else
                    {
                        intScanQty += tempQty;
                    }
                    txtScannedQty.Text = intScanQty.ToString();

                    #endregion

                    DataRow[] drScan = Data.Select("CHKED = true");
                    lblDataCount.Text = string.Format("Scanned {0} of {1} records", drScan.Length, Data.Rows.Count.ToString());
                    if (intTotalAlqty == 0)
                    {
                        if (strType == "ADD")
                        {
                            this.txtSanLocation.Focus();
                        }
                    }
                    else
                    {
                        btnSave.Enabled = false;
                    }

                    #endregion
                }
                catch (Exception ex)
                {
                    stsWarning.Text = ex.Message;
                    this.txtBoxID.Text = "";
                    Sound.Play(@"Sound\ERROR.wav");
                    return;
                }
                finally
                {
                    this.txtBoxID.Text = string.Empty;
                }
            }
        }
        #endregion

        private void btnSave_Click(object sender, System.EventArgs e)
        {
            try
            {
                #region 良品Qty校验
                if (string.IsNullOrEmpty(txtScannedQty.Text.Trim()))
                {
                    MessageBox.Show("请先扫入BOX！");
                    txtBoxID.Focus();
                    return;
                }
                this.btnSave.Enabled = false;
                #endregion

                #region 参数初始化

                SetbtnSaveProcess();
                string strMtype = string.Empty;
                stsWarning.Text = "";
                DataTable dtTemp = new DataTable();
                ArrayList SN = new ArrayList();
                string[] message = new string[2];
                QCI.QWMS.StorageIn objStorageIn = new QCI.QWMS.StorageIn(CommonInfo.Instance.DBType,
                    CommonInfo.Instance.DBCode.ToString(), CommonInfo.Instance.ErrType,
                    CommonInfo.Instance.ErrCode.ToString(), UserData, Werks, Lgort, "", Progid);

                #endregion

                #region 防呆

                if (txtLocat.Text.Trim() == "")
                {
                    MessageBox.Show("Location不能为空！");
                    return;
                }
                else
                {
                    DataTable dtlocation = new DataTable();
                    dtlocation = objStorageIn.QuerywhitmbyLocat(Werks, Lgort, txtLocat.Text.Trim());
                    if (dtlocation.Rows.Count > 0)
                    {
                        for (int i = 0; i < dtlocation.Rows.Count; i++)
                        {
                            if (dtData.Rows.Count > 0)
                            {
                                if (dtlocation.Rows[i]["MATNR"].ToString().Trim() != dtData.Rows[0]["MATNR"].ToString())
                                {
                                    stsWarning.Text = "该储位中已经存在不同的料号！";
                                    return;
                                }
                            }
                        }
                    }
                }
                if (dtData.Rows.Count == 0)
                {
                    stsWarning.Text = "数据不能为空!!";
                    SetbtnSaveException();
                    return;
                }

                #endregion

                foreach (DataRow row in dtCombineData.Rows)
                {
                    row["LOCAT"] = Locat;
                   // row["LOCOD"] = txtLoCod.Text.Trim();
                }
                dtCombineData.AcceptChanges();

                #region 入QWMS的庫存

                //入QWMS
                if (objStorageIn.AddIQCInData(dtCombineData, dtData, dtStorageIn))
                {
                    btnRefresh_Click(sender, e);
                    stsWarning.Text = "Add OK!!";
                    Sound.Play(@"Sound\OO1.wav");
                }
                else
                {
                    stsWarning.Text = "Add fail!! " + objStorageIn.ERRMSG;
                    Sound.Play(@"Sound\ERROR.wav");
                }

                #endregion

                dtTmpData.Clear();
                return;
            }
            catch (Exception ex)
            {
                stsWarning.Text = ex.Message;
                return;
            }
        }

        private void btnRefresh_Click(object sender, System.EventArgs e)
        {
            stsWarning.Text = string.Empty;
            this.rdoAdd.Checked = false;
            this.rdoNew.Checked = true;
            this.gbFunction.Enabled = true;
            this.gbHeader.Enabled = true;
            this.txtLocat.Text = string.Empty;
            this.txtBoxID.Text = string.Empty;
            this.txtScannedQty.Text = string.Empty;
            intScanQty = 0;
            this.dtData.Rows.Clear();
            this.dgvData.DataSource = null;
            this.lblDataCount.Text = "0 records";
            this.btnSave.Enabled = false;
            this.dgvData.Columns.Clear();
            dtTmpData.Clear();
            this.cmbLgort.Text = "";

            this.dgvSAP.DataSource = null;
            this.dgvSAP.Columns.Clear();
            this.dtStorageIn = new DataTable();
            this.lblSAP.Text = "0 records";
            this.btnConfirm.Enabled = true;
            this.txtSanLocation.Text = string.Empty;
            this.txtSanLocation.Enabled = false;
            this.cmbWerks.Enabled = true;
            this.cmbLgort.Enabled = true;
            this.dtpIndat.Enabled = true;
            this.txtBoxID.Enabled = false;
            //txtLoCod.Enabled = false;
            this.txtScannedQty.Enabled = false;
            rdoNew.Enabled = true;
            rdoAdd.Enabled = true;
            this.txtLocat.Enabled = true;
            this.txtMBLNR.Text = string.Empty;
            this.txtMBLNR.Enabled = true;
            dtVBELN = new DataTable();
            strInsmk = string.Empty;
            intTotalAlqty = 0;
            dtCombineData = new DataTable();
            //txtLoCod.Text = "";
        }

        private void btnExit_Click(object sender, System.EventArgs e)
        {
            this.Close();
        }

        private void btnConfirm_Click(object sender, System.EventArgs e)
        {
            try
            {
                stsWarning.Text = "";
                if (txtMBLNR.Text.Trim() != "")
                {
                    string[] aryTempMblnr;
                    aryTempMblnr = txtMBLNR.Text.Trim().Split(new char[] { ',' });
                    aryMblnr.Clear();
                    if (aryMblnr.Count == 0)
                    {
                        for (int i = 0; i < aryTempMblnr.Length; i++)
                        {
                            aryMblnr.Add(aryTempMblnr[i].ToString().Trim());
                        }
                    }
                }

                if (cmbWerks.SelectedIndex != -1)
                    strWerks = cmbWerks.Items[cmbWerks.SelectedIndex].ToString();
                else
                    strWerks = "";

                if (cmbLgort.SelectedIndex != -1)
                    strLgort = cmbLgort.Items[cmbLgort.SelectedIndex].ToString();
                else
                    strLgort = "";
                //廠區倉別不為空
                if (Werks == "" || Lgort == "")
                {
                    stsWarning.Text = "Plant and storage can't be empty!!";
                    return;
                }
                //库位
                if (txtLocat.Text.Trim() == "")
                {
                    stsWarning.Text = "Location can't be empty！!!";
                    return;
                }
                //单号不为空
                if (Mblnr.Count == 0)
                {
                    stsWarning.Text = "Document No can't be empty!!";
                    return;
                }

                if (Mblnr.Count > 1)
                {
                    stsWarning.Text = "一次只能选择一条单据";
                    return;
                }
                QCI.QWMS.StorageIn objStorageIn = new QCI.QWMS.StorageIn(CommonInfo.Instance.DBType, CommonInfo.Instance.DBCode.ToString(), CommonInfo.Instance.ErrType, CommonInfo.Instance.ErrCode.ToString(), UserData, Werks, Lgort, "", Progid);

                //EC单号
                dtVBELN = objStorageIn.QuerySAPByECNo(txtMBLNR.Text.Trim());
                if (dtVBELN == null || dtVBELN.Rows.Count == 0)
                {
                    stsWarning.Text = "EC单扣帐单号暂未回传，请稍候重试!!";
                    return;
                }
                //同一EC单相关的SAP单据
                dtStorageIn = objStorageIn.QuerySAPInData(Locat, dtpIndat.Value.ToString("yyyyMMdd"),
                                                          dtVBELN.Rows[0]["BWART"].ToString(), dtVBELN.Rows[0]["VBELN"].ToString(),
                                                          dtVBELN.Rows[0]["MATNR"].ToString(), dtVBELN.Rows[0]["CHARG"].ToString());
                if (dtStorageIn.Rows.Count == 0)
                {
                    stsWarning.Text = "No data!!";
                    return;
                }

                #region 扣帐单号信息
                foreach (DataRow tmpRow in dtStorageIn.Rows)
                {
                    strInsmk = tmpRow["INSMK"].ToString();
                    intTotalAlqty += Convert.ToInt32(tmpRow["MENGE"].ToString());
                }
                #endregion
                
                ShowInSourceDataGrid();
                


                #region 設定按鈕状态
                this.btnConfirm.Enabled = false;
                this.cmbWerks.Enabled = false;
                this.cmbLgort.Enabled = false;
                this.txtLocat.Enabled = false;
                this.txtMBLNR.Enabled = false;
                this.txtBoxID.Text = "";
                this.txtBoxID.Enabled = true;
                txtBoxID.Focus();
                this.txtScannedQty.Enabled = false;
                this.txtSanLocation.Enabled = true;
                rdoNew.Enabled = false;
                rdoAdd.Enabled = false;
                //txtLoCod.Enabled = true;
                #endregion

            }
            catch (Exception ex)
            {
                stsWarning.Text = ex.Message;
                return;
            }
        }

        private void txtMBLNR_DoubleClick(object sender, EventArgs e)
        {
            try
            {
                if (cmbWerks.SelectedIndex != -1)
                {
                    strWerks = cmbWerks.Items[cmbWerks.SelectedIndex].ToString();
                }
                else
                {
                    strWerks = "";
                }

                if (cmbLgort.SelectedIndex != -1)
                {
                    strLgort = cmbLgort.Items[cmbLgort.SelectedIndex].ToString();
                }
                else
                {
                    strLgort = "";
                }

                //廠區倉別不為空
                if (Werks == "" || Lgort == "")
                {
                    stsWarning.Text = "Plant and storage can't be empty!!";
                    return;
                }

                aryMblnr.Clear();
                if (txtMBLNR.Text.Trim() != "")
                {
                    aryMblnr.Add(txtMBLNR.Text.Trim());
                }
                StorageIn_SapDataSelect objStorageIn_SapDataSelect = new StorageIn_SapDataSelect(UserData, Werks, Lgort, Progid, txtMBLNR.Text.Trim(), "ONLINE_EC", Insmk);
                objStorageIn_SapDataSelect.ShowDialog();
                txtMBLNR.Text = objStorageIn_SapDataSelect.Mblnr;
            }
            catch (Exception ex)
            {
                stsWarning.Text = ex.Message;
                return;
            }
        }

        private void txtMBLNR_KeyPress(object sender, KeyPressEventArgs e)
        {
            if (e.KeyChar == (char)13)
            {
                try
                {
                    btnConfirm_Click(null, null);
                }
                catch (Exception ex)
                {
                    MessageBox.Show(ex.Message);
                    return;
                }
            }
        }

        private void txtSanLocation_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.KeyValue == (char)13)
            {
                if (txtSanLocation.Text.Trim().ToUpper() != "" && txtSanLocation.Text.Trim().ToUpper() == txtLocat.Text.Trim().ToUpper())
                {
                    txtSanLocation.Text = txtLocat.Text.Trim().ToUpper();
                    #region 將Location 填回Data中
                    foreach (DataRow rsTmpRow in this.Data.Rows)
                    {
                        rsTmpRow["LOCAT"] = this.txtLocat.Text.Trim();
                    }
                    this.Data.AcceptChanges();
                    #endregion

                    #region 設定按鈕
                    this.txtBoxID.Text = "";
                    this.txtScannedQty.Enabled = false;
                    this.btnSave.Enabled = true;
                    this.txtBoxID.Enabled = true;
                    this.txtBoxID.Focus();
                    //txtLoCod.Enabled = true;
                    #endregion
                }
                else
                {
                    btnSave.Enabled = false;
                    Sound.Play(@"Sound\OO.wav");
                    MessageBox.Show("储位扫描错误！");
                    return;
                }
            }
        }

        #endregion
    }
}
