//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace QWMS.BPMTIC {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="GWF074_wsUploadApvstaSoap", Namespace="http://tempuri.org/")]
    public partial class GWF074_wsUploadApvsta : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback wsActionFunctionOperationCompleted;
        
        private System.Threading.SendOrPostCallback GWF074_ProvideQWMSApproveScrapItemOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public GWF074_wsUploadApvsta() {
            this.Url = global::QWMS.Properties.Settings.Default.QWMS_BPMTIC_GWF074_wsUploadApvsta;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event wsActionFunctionCompletedEventHandler wsActionFunctionCompleted;
        
        /// <remarks/>
        public event GWF074_ProvideQWMSApproveScrapItemCompletedEventHandler GWF074_ProvideQWMSApproveScrapItemCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/wsActionFunction", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool wsActionFunction(int intDBType, string strDBCode, string varFormID, string varApplid, string varFlowLevel, string varFlowNumber, string varSeqNumber, string varQuType, string varSituat, string varParam01, string varParam02) {
            object[] results = this.Invoke("wsActionFunction", new object[] {
                        intDBType,
                        strDBCode,
                        varFormID,
                        varApplid,
                        varFlowLevel,
                        varFlowNumber,
                        varSeqNumber,
                        varQuType,
                        varSituat,
                        varParam01,
                        varParam02});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void wsActionFunctionAsync(int intDBType, string strDBCode, string varFormID, string varApplid, string varFlowLevel, string varFlowNumber, string varSeqNumber, string varQuType, string varSituat, string varParam01, string varParam02) {
            this.wsActionFunctionAsync(intDBType, strDBCode, varFormID, varApplid, varFlowLevel, varFlowNumber, varSeqNumber, varQuType, varSituat, varParam01, varParam02, null);
        }
        
        /// <remarks/>
        public void wsActionFunctionAsync(int intDBType, string strDBCode, string varFormID, string varApplid, string varFlowLevel, string varFlowNumber, string varSeqNumber, string varQuType, string varSituat, string varParam01, string varParam02, object userState) {
            if ((this.wsActionFunctionOperationCompleted == null)) {
                this.wsActionFunctionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnwsActionFunctionOperationCompleted);
            }
            this.InvokeAsync("wsActionFunction", new object[] {
                        intDBType,
                        strDBCode,
                        varFormID,
                        varApplid,
                        varFlowLevel,
                        varFlowNumber,
                        varSeqNumber,
                        varQuType,
                        varSituat,
                        varParam01,
                        varParam02}, this.wsActionFunctionOperationCompleted, userState);
        }
        
        private void OnwsActionFunctionOperationCompleted(object arg) {
            if ((this.wsActionFunctionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.wsActionFunctionCompleted(this, new wsActionFunctionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GWF074_ProvideQWMSApproveScrapItem", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GWF074_ProvideQWMSApproveScrapItem(string varBPMApplid, string varSAPRefnum) {
            object[] results = this.Invoke("GWF074_ProvideQWMSApproveScrapItem", new object[] {
                        varBPMApplid,
                        varSAPRefnum});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GWF074_ProvideQWMSApproveScrapItemAsync(string varBPMApplid, string varSAPRefnum) {
            this.GWF074_ProvideQWMSApproveScrapItemAsync(varBPMApplid, varSAPRefnum, null);
        }
        
        /// <remarks/>
        public void GWF074_ProvideQWMSApproveScrapItemAsync(string varBPMApplid, string varSAPRefnum, object userState) {
            if ((this.GWF074_ProvideQWMSApproveScrapItemOperationCompleted == null)) {
                this.GWF074_ProvideQWMSApproveScrapItemOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGWF074_ProvideQWMSApproveScrapItemOperationCompleted);
            }
            this.InvokeAsync("GWF074_ProvideQWMSApproveScrapItem", new object[] {
                        varBPMApplid,
                        varSAPRefnum}, this.GWF074_ProvideQWMSApproveScrapItemOperationCompleted, userState);
        }
        
        private void OnGWF074_ProvideQWMSApproveScrapItemOperationCompleted(object arg) {
            if ((this.GWF074_ProvideQWMSApproveScrapItemCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GWF074_ProvideQWMSApproveScrapItemCompleted(this, new GWF074_ProvideQWMSApproveScrapItemCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void wsActionFunctionCompletedEventHandler(object sender, wsActionFunctionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class wsActionFunctionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal wsActionFunctionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void GWF074_ProvideQWMSApproveScrapItemCompletedEventHandler(object sender, GWF074_ProvideQWMSApproveScrapItemCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GWF074_ProvideQWMSApproveScrapItemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GWF074_ProvideQWMSApproveScrapItemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591