//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace QWMS.PP {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="PP_ServiceSoap", Namespace="http://SDSWS05/SAP_WebService/QSMC/EC/PP/PP_Service.asmx")]
    public partial class PP_Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback Z_RFC_VMATNR1OperationCompleted;
        
        private System.Threading.SendOrPostCallback ZRFC_IQC_ZMWFCOperationCompleted;
        
        private System.Threading.SendOrPostCallback ZRFC_PP_311_AUTO_RETURN_NOperationCompleted;
        
        private System.Threading.SendOrPostCallback ZRFC_MM_QWMS_LGORTOperationCompleted;
        
        private System.Threading.SendOrPostCallback ZRFC_PP_QWMS_DEBITOperationCompleted;
        
        private System.Threading.SendOrPostCallback ZRFC_PP_WO_AUTO_GR_MOperationCompleted;
        
        private System.Threading.SendOrPostCallback ZRFC_PP_WO_AUTO_GR_M_WithPlantOperationCompleted;
        
        private System.Threading.SendOrPostCallback ZRFC_PP_311_AUTO_RETURN_MOperationCompleted;
        
        private System.Threading.SendOrPostCallback ZRFC_PP_311_AUTO_RETURN_M_WithPlantOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public PP_Service() {
            this.Url = global::QWMS.Properties.Settings.Default.QWMS_PP_PP_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event Z_RFC_VMATNR1CompletedEventHandler Z_RFC_VMATNR1Completed;
        
        /// <remarks/>
        public event ZRFC_IQC_ZMWFCCompletedEventHandler ZRFC_IQC_ZMWFCCompleted;
        
        /// <remarks/>
        public event ZRFC_PP_311_AUTO_RETURN_NCompletedEventHandler ZRFC_PP_311_AUTO_RETURN_NCompleted;
        
        /// <remarks/>
        public event ZRFC_MM_QWMS_LGORTCompletedEventHandler ZRFC_MM_QWMS_LGORTCompleted;
        
        /// <remarks/>
        public event ZRFC_PP_QWMS_DEBITCompletedEventHandler ZRFC_PP_QWMS_DEBITCompleted;
        
        /// <remarks/>
        public event ZRFC_PP_WO_AUTO_GR_MCompletedEventHandler ZRFC_PP_WO_AUTO_GR_MCompleted;
        
        /// <remarks/>
        public event ZRFC_PP_WO_AUTO_GR_M_WithPlantCompletedEventHandler ZRFC_PP_WO_AUTO_GR_M_WithPlantCompleted;
        
        /// <remarks/>
        public event ZRFC_PP_311_AUTO_RETURN_MCompletedEventHandler ZRFC_PP_311_AUTO_RETURN_MCompleted;
        
        /// <remarks/>
        public event ZRFC_PP_311_AUTO_RETURN_M_WithPlantCompletedEventHandler ZRFC_PP_311_AUTO_RETURN_M_WithPlantCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://SDSWS05/SAP_WebService/QSMC/EC/PP/PP_Service.asmx/Z_RFC_VMATNR1", RequestNamespace="http://SDSWS05/SAP_WebService/QSMC/EC/PP/PP_Service.asmx", ResponseNamespace="http://SDSWS05/SAP_WebService/QSMC/EC/PP/PP_Service.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable Z_RFC_VMATNR1(string varMatnr) {
            object[] results = this.Invoke("Z_RFC_VMATNR1", new object[] {
                        varMatnr});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void Z_RFC_VMATNR1Async(string varMatnr) {
            this.Z_RFC_VMATNR1Async(varMatnr, null);
        }
        
        /// <remarks/>
        public void Z_RFC_VMATNR1Async(string varMatnr, object userState) {
            if ((this.Z_RFC_VMATNR1OperationCompleted == null)) {
                this.Z_RFC_VMATNR1OperationCompleted = new System.Threading.SendOrPostCallback(this.OnZ_RFC_VMATNR1OperationCompleted);
            }
            this.InvokeAsync("Z_RFC_VMATNR1", new object[] {
                        varMatnr}, this.Z_RFC_VMATNR1OperationCompleted, userState);
        }
        
        private void OnZ_RFC_VMATNR1OperationCompleted(object arg) {
            if ((this.Z_RFC_VMATNR1Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Z_RFC_VMATNR1Completed(this, new Z_RFC_VMATNR1CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://SDSWS05/SAP_WebService/QSMC/EC/PP/PP_Service.asmx/ZRFC_IQC_ZMWFC", RequestNamespace="http://SDSWS05/SAP_WebService/QSMC/EC/PP/PP_Service.asmx", ResponseNamespace="http://SDSWS05/SAP_WebService/QSMC/EC/PP/PP_Service.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet ZRFC_IQC_ZMWFC(System.Data.DataSet vards) {
            object[] results = this.Invoke("ZRFC_IQC_ZMWFC", new object[] {
                        vards});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void ZRFC_IQC_ZMWFCAsync(System.Data.DataSet vards) {
            this.ZRFC_IQC_ZMWFCAsync(vards, null);
        }
        
        /// <remarks/>
        public void ZRFC_IQC_ZMWFCAsync(System.Data.DataSet vards, object userState) {
            if ((this.ZRFC_IQC_ZMWFCOperationCompleted == null)) {
                this.ZRFC_IQC_ZMWFCOperationCompleted = new System.Threading.SendOrPostCallback(this.OnZRFC_IQC_ZMWFCOperationCompleted);
            }
            this.InvokeAsync("ZRFC_IQC_ZMWFC", new object[] {
                        vards}, this.ZRFC_IQC_ZMWFCOperationCompleted, userState);
        }
        
        private void OnZRFC_IQC_ZMWFCOperationCompleted(object arg) {
            if ((this.ZRFC_IQC_ZMWFCCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ZRFC_IQC_ZMWFCCompleted(this, new ZRFC_IQC_ZMWFCCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://SDSWS05/SAP_WebService/QSMC/EC/PP/PP_Service.asmx/ZRFC_PP_311_AUTO_RETURN_" +
            "N", RequestNamespace="http://SDSWS05/SAP_WebService/QSMC/EC/PP/PP_Service.asmx", ResponseNamespace="http://SDSWS05/SAP_WebService/QSMC/EC/PP/PP_Service.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet ZRFC_PP_311_AUTO_RETURN_N(System.Data.DataSet vards) {
            object[] results = this.Invoke("ZRFC_PP_311_AUTO_RETURN_N", new object[] {
                        vards});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void ZRFC_PP_311_AUTO_RETURN_NAsync(System.Data.DataSet vards) {
            this.ZRFC_PP_311_AUTO_RETURN_NAsync(vards, null);
        }
        
        /// <remarks/>
        public void ZRFC_PP_311_AUTO_RETURN_NAsync(System.Data.DataSet vards, object userState) {
            if ((this.ZRFC_PP_311_AUTO_RETURN_NOperationCompleted == null)) {
                this.ZRFC_PP_311_AUTO_RETURN_NOperationCompleted = new System.Threading.SendOrPostCallback(this.OnZRFC_PP_311_AUTO_RETURN_NOperationCompleted);
            }
            this.InvokeAsync("ZRFC_PP_311_AUTO_RETURN_N", new object[] {
                        vards}, this.ZRFC_PP_311_AUTO_RETURN_NOperationCompleted, userState);
        }
        
        private void OnZRFC_PP_311_AUTO_RETURN_NOperationCompleted(object arg) {
            if ((this.ZRFC_PP_311_AUTO_RETURN_NCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ZRFC_PP_311_AUTO_RETURN_NCompleted(this, new ZRFC_PP_311_AUTO_RETURN_NCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://SDSWS05/SAP_WebService/QSMC/EC/PP/PP_Service.asmx/ZRFC_MM_QWMS_LGORT", RequestNamespace="http://SDSWS05/SAP_WebService/QSMC/EC/PP/PP_Service.asmx", ResponseNamespace="http://SDSWS05/SAP_WebService/QSMC/EC/PP/PP_Service.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet ZRFC_MM_QWMS_LGORT(System.Data.DataSet dsData) {
            object[] results = this.Invoke("ZRFC_MM_QWMS_LGORT", new object[] {
                        dsData});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void ZRFC_MM_QWMS_LGORTAsync(System.Data.DataSet dsData) {
            this.ZRFC_MM_QWMS_LGORTAsync(dsData, null);
        }
        
        /// <remarks/>
        public void ZRFC_MM_QWMS_LGORTAsync(System.Data.DataSet dsData, object userState) {
            if ((this.ZRFC_MM_QWMS_LGORTOperationCompleted == null)) {
                this.ZRFC_MM_QWMS_LGORTOperationCompleted = new System.Threading.SendOrPostCallback(this.OnZRFC_MM_QWMS_LGORTOperationCompleted);
            }
            this.InvokeAsync("ZRFC_MM_QWMS_LGORT", new object[] {
                        dsData}, this.ZRFC_MM_QWMS_LGORTOperationCompleted, userState);
        }
        
        private void OnZRFC_MM_QWMS_LGORTOperationCompleted(object arg) {
            if ((this.ZRFC_MM_QWMS_LGORTCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ZRFC_MM_QWMS_LGORTCompleted(this, new ZRFC_MM_QWMS_LGORTCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://SDSWS05/SAP_WebService/QSMC/EC/PP/PP_Service.asmx/ZRFC_PP_QWMS_DEBIT", RequestNamespace="http://SDSWS05/SAP_WebService/QSMC/EC/PP/PP_Service.asmx", ResponseNamespace="http://SDSWS05/SAP_WebService/QSMC/EC/PP/PP_Service.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet ZRFC_PP_QWMS_DEBIT(System.Data.DataSet dsData) {
            object[] results = this.Invoke("ZRFC_PP_QWMS_DEBIT", new object[] {
                        dsData});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void ZRFC_PP_QWMS_DEBITAsync(System.Data.DataSet dsData) {
            this.ZRFC_PP_QWMS_DEBITAsync(dsData, null);
        }
        
        /// <remarks/>
        public void ZRFC_PP_QWMS_DEBITAsync(System.Data.DataSet dsData, object userState) {
            if ((this.ZRFC_PP_QWMS_DEBITOperationCompleted == null)) {
                this.ZRFC_PP_QWMS_DEBITOperationCompleted = new System.Threading.SendOrPostCallback(this.OnZRFC_PP_QWMS_DEBITOperationCompleted);
            }
            this.InvokeAsync("ZRFC_PP_QWMS_DEBIT", new object[] {
                        dsData}, this.ZRFC_PP_QWMS_DEBITOperationCompleted, userState);
        }
        
        private void OnZRFC_PP_QWMS_DEBITOperationCompleted(object arg) {
            if ((this.ZRFC_PP_QWMS_DEBITCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ZRFC_PP_QWMS_DEBITCompleted(this, new ZRFC_PP_QWMS_DEBITCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://SDSWS05/SAP_WebService/QSMC/EC/PP/PP_Service.asmx/ZRFC_PP_WO_AUTO_GR_M", RequestNamespace="http://SDSWS05/SAP_WebService/QSMC/EC/PP/PP_Service.asmx", ResponseNamespace="http://SDSWS05/SAP_WebService/QSMC/EC/PP/PP_Service.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet ZRFC_PP_WO_AUTO_GR_M(System.Data.DataSet vards) {
            object[] results = this.Invoke("ZRFC_PP_WO_AUTO_GR_M", new object[] {
                        vards});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void ZRFC_PP_WO_AUTO_GR_MAsync(System.Data.DataSet vards) {
            this.ZRFC_PP_WO_AUTO_GR_MAsync(vards, null);
        }
        
        /// <remarks/>
        public void ZRFC_PP_WO_AUTO_GR_MAsync(System.Data.DataSet vards, object userState) {
            if ((this.ZRFC_PP_WO_AUTO_GR_MOperationCompleted == null)) {
                this.ZRFC_PP_WO_AUTO_GR_MOperationCompleted = new System.Threading.SendOrPostCallback(this.OnZRFC_PP_WO_AUTO_GR_MOperationCompleted);
            }
            this.InvokeAsync("ZRFC_PP_WO_AUTO_GR_M", new object[] {
                        vards}, this.ZRFC_PP_WO_AUTO_GR_MOperationCompleted, userState);
        }
        
        private void OnZRFC_PP_WO_AUTO_GR_MOperationCompleted(object arg) {
            if ((this.ZRFC_PP_WO_AUTO_GR_MCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ZRFC_PP_WO_AUTO_GR_MCompleted(this, new ZRFC_PP_WO_AUTO_GR_MCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://SDSWS05/SAP_WebService/QSMC/EC/PP/PP_Service.asmx/ZRFC_PP_WO_AUTO_GR_M_Wit" +
            "hPlant", RequestNamespace="http://SDSWS05/SAP_WebService/QSMC/EC/PP/PP_Service.asmx", ResponseNamespace="http://SDSWS05/SAP_WebService/QSMC/EC/PP/PP_Service.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet ZRFC_PP_WO_AUTO_GR_M_WithPlant(string varPlant, System.Data.DataSet vards) {
            object[] results = this.Invoke("ZRFC_PP_WO_AUTO_GR_M_WithPlant", new object[] {
                        varPlant,
                        vards});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void ZRFC_PP_WO_AUTO_GR_M_WithPlantAsync(string varPlant, System.Data.DataSet vards) {
            this.ZRFC_PP_WO_AUTO_GR_M_WithPlantAsync(varPlant, vards, null);
        }
        
        /// <remarks/>
        public void ZRFC_PP_WO_AUTO_GR_M_WithPlantAsync(string varPlant, System.Data.DataSet vards, object userState) {
            if ((this.ZRFC_PP_WO_AUTO_GR_M_WithPlantOperationCompleted == null)) {
                this.ZRFC_PP_WO_AUTO_GR_M_WithPlantOperationCompleted = new System.Threading.SendOrPostCallback(this.OnZRFC_PP_WO_AUTO_GR_M_WithPlantOperationCompleted);
            }
            this.InvokeAsync("ZRFC_PP_WO_AUTO_GR_M_WithPlant", new object[] {
                        varPlant,
                        vards}, this.ZRFC_PP_WO_AUTO_GR_M_WithPlantOperationCompleted, userState);
        }
        
        private void OnZRFC_PP_WO_AUTO_GR_M_WithPlantOperationCompleted(object arg) {
            if ((this.ZRFC_PP_WO_AUTO_GR_M_WithPlantCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ZRFC_PP_WO_AUTO_GR_M_WithPlantCompleted(this, new ZRFC_PP_WO_AUTO_GR_M_WithPlantCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://SDSWS05/SAP_WebService/QSMC/EC/PP/PP_Service.asmx/ZRFC_PP_311_AUTO_RETURN_" +
            "M", RequestNamespace="http://SDSWS05/SAP_WebService/QSMC/EC/PP/PP_Service.asmx", ResponseNamespace="http://SDSWS05/SAP_WebService/QSMC/EC/PP/PP_Service.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet ZRFC_PP_311_AUTO_RETURN_M(System.Data.DataSet vards) {
            object[] results = this.Invoke("ZRFC_PP_311_AUTO_RETURN_M", new object[] {
                        vards});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void ZRFC_PP_311_AUTO_RETURN_MAsync(System.Data.DataSet vards) {
            this.ZRFC_PP_311_AUTO_RETURN_MAsync(vards, null);
        }
        
        /// <remarks/>
        public void ZRFC_PP_311_AUTO_RETURN_MAsync(System.Data.DataSet vards, object userState) {
            if ((this.ZRFC_PP_311_AUTO_RETURN_MOperationCompleted == null)) {
                this.ZRFC_PP_311_AUTO_RETURN_MOperationCompleted = new System.Threading.SendOrPostCallback(this.OnZRFC_PP_311_AUTO_RETURN_MOperationCompleted);
            }
            this.InvokeAsync("ZRFC_PP_311_AUTO_RETURN_M", new object[] {
                        vards}, this.ZRFC_PP_311_AUTO_RETURN_MOperationCompleted, userState);
        }
        
        private void OnZRFC_PP_311_AUTO_RETURN_MOperationCompleted(object arg) {
            if ((this.ZRFC_PP_311_AUTO_RETURN_MCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ZRFC_PP_311_AUTO_RETURN_MCompleted(this, new ZRFC_PP_311_AUTO_RETURN_MCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://SDSWS05/SAP_WebService/QSMC/EC/PP/PP_Service.asmx/ZRFC_PP_311_AUTO_RETURN_" +
            "M_WithPlant", RequestNamespace="http://SDSWS05/SAP_WebService/QSMC/EC/PP/PP_Service.asmx", ResponseNamespace="http://SDSWS05/SAP_WebService/QSMC/EC/PP/PP_Service.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet ZRFC_PP_311_AUTO_RETURN_M_WithPlant(string varPlant, System.Data.DataSet vards) {
            object[] results = this.Invoke("ZRFC_PP_311_AUTO_RETURN_M_WithPlant", new object[] {
                        varPlant,
                        vards});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void ZRFC_PP_311_AUTO_RETURN_M_WithPlantAsync(string varPlant, System.Data.DataSet vards) {
            this.ZRFC_PP_311_AUTO_RETURN_M_WithPlantAsync(varPlant, vards, null);
        }
        
        /// <remarks/>
        public void ZRFC_PP_311_AUTO_RETURN_M_WithPlantAsync(string varPlant, System.Data.DataSet vards, object userState) {
            if ((this.ZRFC_PP_311_AUTO_RETURN_M_WithPlantOperationCompleted == null)) {
                this.ZRFC_PP_311_AUTO_RETURN_M_WithPlantOperationCompleted = new System.Threading.SendOrPostCallback(this.OnZRFC_PP_311_AUTO_RETURN_M_WithPlantOperationCompleted);
            }
            this.InvokeAsync("ZRFC_PP_311_AUTO_RETURN_M_WithPlant", new object[] {
                        varPlant,
                        vards}, this.ZRFC_PP_311_AUTO_RETURN_M_WithPlantOperationCompleted, userState);
        }
        
        private void OnZRFC_PP_311_AUTO_RETURN_M_WithPlantOperationCompleted(object arg) {
            if ((this.ZRFC_PP_311_AUTO_RETURN_M_WithPlantCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ZRFC_PP_311_AUTO_RETURN_M_WithPlantCompleted(this, new ZRFC_PP_311_AUTO_RETURN_M_WithPlantCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void Z_RFC_VMATNR1CompletedEventHandler(object sender, Z_RFC_VMATNR1CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Z_RFC_VMATNR1CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Z_RFC_VMATNR1CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void ZRFC_IQC_ZMWFCCompletedEventHandler(object sender, ZRFC_IQC_ZMWFCCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ZRFC_IQC_ZMWFCCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ZRFC_IQC_ZMWFCCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void ZRFC_PP_311_AUTO_RETURN_NCompletedEventHandler(object sender, ZRFC_PP_311_AUTO_RETURN_NCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ZRFC_PP_311_AUTO_RETURN_NCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ZRFC_PP_311_AUTO_RETURN_NCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void ZRFC_MM_QWMS_LGORTCompletedEventHandler(object sender, ZRFC_MM_QWMS_LGORTCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ZRFC_MM_QWMS_LGORTCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ZRFC_MM_QWMS_LGORTCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void ZRFC_PP_QWMS_DEBITCompletedEventHandler(object sender, ZRFC_PP_QWMS_DEBITCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ZRFC_PP_QWMS_DEBITCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ZRFC_PP_QWMS_DEBITCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void ZRFC_PP_WO_AUTO_GR_MCompletedEventHandler(object sender, ZRFC_PP_WO_AUTO_GR_MCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ZRFC_PP_WO_AUTO_GR_MCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ZRFC_PP_WO_AUTO_GR_MCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void ZRFC_PP_WO_AUTO_GR_M_WithPlantCompletedEventHandler(object sender, ZRFC_PP_WO_AUTO_GR_M_WithPlantCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ZRFC_PP_WO_AUTO_GR_M_WithPlantCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ZRFC_PP_WO_AUTO_GR_M_WithPlantCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void ZRFC_PP_311_AUTO_RETURN_MCompletedEventHandler(object sender, ZRFC_PP_311_AUTO_RETURN_MCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ZRFC_PP_311_AUTO_RETURN_MCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ZRFC_PP_311_AUTO_RETURN_MCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void ZRFC_PP_311_AUTO_RETURN_M_WithPlantCompletedEventHandler(object sender, ZRFC_PP_311_AUTO_RETURN_M_WithPlantCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ZRFC_PP_311_AUTO_RETURN_M_WithPlantCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ZRFC_PP_311_AUTO_RETURN_M_WithPlantCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591