//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace QWMS.iworkflow {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WFWebServiceSoap", Namespace="http://tempuri.org/")]
    public partial class WFWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ReturnBasicFlowDataSetOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetApproverByRMBOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetQMBApproverByRMBOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReturnApplicationIDGUIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateApplicationUseDefaultFlowDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateApplicationOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateApplicationKeyIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback CancelApplicationOperationCompleted;
        
        private System.Threading.SendOrPostCallback CancelApplicationCancelByOperationCompleted;
        
        private System.Threading.SendOrPostCallback ApproveOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetIsWFSApproveOperationCompleted;
        
        private System.Threading.SendOrPostCallback ModifyApproverOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertPreviousFlowOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertNextFlowOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertNextFlowIsOnlyNoticeOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertNextFlowFullParameterOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertSequenceOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteFlowOperationCompleted;
        
        private System.Threading.SendOrPostCallback QueryApplicationStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetApplicationApproveFlowOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCurrentFlowDescriptionOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetApprDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback IsEndFlowNoOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateEmplidOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WFWebService() {
            this.Url = global::QWMS.Properties.Settings.Default.QWMS_iworkflow_WFWebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ReturnBasicFlowDataSetCompletedEventHandler ReturnBasicFlowDataSetCompleted;
        
        /// <remarks/>
        public event GetApproverByRMBCompletedEventHandler GetApproverByRMBCompleted;
        
        /// <remarks/>
        public event GetQMBApproverByRMBCompletedEventHandler GetQMBApproverByRMBCompleted;
        
        /// <remarks/>
        public event ReturnApplicationIDGUIDCompletedEventHandler ReturnApplicationIDGUIDCompleted;
        
        /// <remarks/>
        public event CreateApplicationUseDefaultFlowDataCompletedEventHandler CreateApplicationUseDefaultFlowDataCompleted;
        
        /// <remarks/>
        public event CreateApplicationCompletedEventHandler CreateApplicationCompleted;
        
        /// <remarks/>
        public event CreateApplicationKeyIDCompletedEventHandler CreateApplicationKeyIDCompleted;
        
        /// <remarks/>
        public event CancelApplicationCompletedEventHandler CancelApplicationCompleted;
        
        /// <remarks/>
        public event CancelApplicationCancelByCompletedEventHandler CancelApplicationCancelByCompleted;
        
        /// <remarks/>
        public event ApproveCompletedEventHandler ApproveCompleted;
        
        /// <remarks/>
        public event SetIsWFSApproveCompletedEventHandler SetIsWFSApproveCompleted;
        
        /// <remarks/>
        public event ModifyApproverCompletedEventHandler ModifyApproverCompleted;
        
        /// <remarks/>
        public event InsertPreviousFlowCompletedEventHandler InsertPreviousFlowCompleted;
        
        /// <remarks/>
        public event InsertNextFlowCompletedEventHandler InsertNextFlowCompleted;
        
        /// <remarks/>
        public event InsertNextFlowIsOnlyNoticeCompletedEventHandler InsertNextFlowIsOnlyNoticeCompleted;
        
        /// <remarks/>
        public event InsertNextFlowFullParameterCompletedEventHandler InsertNextFlowFullParameterCompleted;
        
        /// <remarks/>
        public event InsertSequenceCompletedEventHandler InsertSequenceCompleted;
        
        /// <remarks/>
        public event DeleteFlowCompletedEventHandler DeleteFlowCompleted;
        
        /// <remarks/>
        public event QueryApplicationStatusCompletedEventHandler QueryApplicationStatusCompleted;
        
        /// <remarks/>
        public event GetApplicationApproveFlowCompletedEventHandler GetApplicationApproveFlowCompleted;
        
        /// <remarks/>
        public event GetCurrentFlowDescriptionCompletedEventHandler GetCurrentFlowDescriptionCompleted;
        
        /// <remarks/>
        public event GetApprDataCompletedEventHandler GetApprDataCompleted;
        
        /// <remarks/>
        public event IsEndFlowNoCompletedEventHandler IsEndFlowNoCompleted;
        
        /// <remarks/>
        public event UpdateEmplidCompletedEventHandler UpdateEmplidCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ReturnBasicFlowDataSet", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet ReturnBasicFlowDataSet() {
            object[] results = this.Invoke("ReturnBasicFlowDataSet", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void ReturnBasicFlowDataSetAsync() {
            this.ReturnBasicFlowDataSetAsync(null);
        }
        
        /// <remarks/>
        public void ReturnBasicFlowDataSetAsync(object userState) {
            if ((this.ReturnBasicFlowDataSetOperationCompleted == null)) {
                this.ReturnBasicFlowDataSetOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReturnBasicFlowDataSetOperationCompleted);
            }
            this.InvokeAsync("ReturnBasicFlowDataSet", new object[0], this.ReturnBasicFlowDataSetOperationCompleted, userState);
        }
        
        private void OnReturnBasicFlowDataSetOperationCompleted(object arg) {
            if ((this.ReturnBasicFlowDataSetCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReturnBasicFlowDataSetCompleted(this, new ReturnBasicFlowDataSetCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetApproverByRMB", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetApproverByRMB(string company, string depcod, decimal money, bool IsApvcod, bool IsJobName) {
            object[] results = this.Invoke("GetApproverByRMB", new object[] {
                        company,
                        depcod,
                        money,
                        IsApvcod,
                        IsJobName});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetApproverByRMBAsync(string company, string depcod, decimal money, bool IsApvcod, bool IsJobName) {
            this.GetApproverByRMBAsync(company, depcod, money, IsApvcod, IsJobName, null);
        }
        
        /// <remarks/>
        public void GetApproverByRMBAsync(string company, string depcod, decimal money, bool IsApvcod, bool IsJobName, object userState) {
            if ((this.GetApproverByRMBOperationCompleted == null)) {
                this.GetApproverByRMBOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetApproverByRMBOperationCompleted);
            }
            this.InvokeAsync("GetApproverByRMB", new object[] {
                        company,
                        depcod,
                        money,
                        IsApvcod,
                        IsJobName}, this.GetApproverByRMBOperationCompleted, userState);
        }
        
        private void OnGetApproverByRMBOperationCompleted(object arg) {
            if ((this.GetApproverByRMBCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetApproverByRMBCompleted(this, new GetApproverByRMBCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetQMBApproverByRMB", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetQMBApproverByRMB(string company, string depcod, decimal money, bool IsApvcod, bool IsJobName, string Emplid) {
            object[] results = this.Invoke("GetQMBApproverByRMB", new object[] {
                        company,
                        depcod,
                        money,
                        IsApvcod,
                        IsJobName,
                        Emplid});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetQMBApproverByRMBAsync(string company, string depcod, decimal money, bool IsApvcod, bool IsJobName, string Emplid) {
            this.GetQMBApproverByRMBAsync(company, depcod, money, IsApvcod, IsJobName, Emplid, null);
        }
        
        /// <remarks/>
        public void GetQMBApproverByRMBAsync(string company, string depcod, decimal money, bool IsApvcod, bool IsJobName, string Emplid, object userState) {
            if ((this.GetQMBApproverByRMBOperationCompleted == null)) {
                this.GetQMBApproverByRMBOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetQMBApproverByRMBOperationCompleted);
            }
            this.InvokeAsync("GetQMBApproverByRMB", new object[] {
                        company,
                        depcod,
                        money,
                        IsApvcod,
                        IsJobName,
                        Emplid}, this.GetQMBApproverByRMBOperationCompleted, userState);
        }
        
        private void OnGetQMBApproverByRMBOperationCompleted(object arg) {
            if ((this.GetQMBApproverByRMBCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetQMBApproverByRMBCompleted(this, new GetQMBApproverByRMBCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ReturnApplicationIDGUID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ReturnApplicationIDGUID(string formID, out string applicationID, out string GUID) {
            object[] results = this.Invoke("ReturnApplicationIDGUID", new object[] {
                        formID});
            applicationID = ((string)(results[1]));
            GUID = ((string)(results[2]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ReturnApplicationIDGUIDAsync(string formID) {
            this.ReturnApplicationIDGUIDAsync(formID, null);
        }
        
        /// <remarks/>
        public void ReturnApplicationIDGUIDAsync(string formID, object userState) {
            if ((this.ReturnApplicationIDGUIDOperationCompleted == null)) {
                this.ReturnApplicationIDGUIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReturnApplicationIDGUIDOperationCompleted);
            }
            this.InvokeAsync("ReturnApplicationIDGUID", new object[] {
                        formID}, this.ReturnApplicationIDGUIDOperationCompleted, userState);
        }
        
        private void OnReturnApplicationIDGUIDOperationCompleted(object arg) {
            if ((this.ReturnApplicationIDGUIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReturnApplicationIDGUIDCompleted(this, new ReturnApplicationIDGUIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CreateApplicationUseDefaultFlowData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool CreateApplicationUseDefaultFlowData(string formID, string company, string applicant, string applyReason, string applicationID, string GUID) {
            object[] results = this.Invoke("CreateApplicationUseDefaultFlowData", new object[] {
                        formID,
                        company,
                        applicant,
                        applyReason,
                        applicationID,
                        GUID});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void CreateApplicationUseDefaultFlowDataAsync(string formID, string company, string applicant, string applyReason, string applicationID, string GUID) {
            this.CreateApplicationUseDefaultFlowDataAsync(formID, company, applicant, applyReason, applicationID, GUID, null);
        }
        
        /// <remarks/>
        public void CreateApplicationUseDefaultFlowDataAsync(string formID, string company, string applicant, string applyReason, string applicationID, string GUID, object userState) {
            if ((this.CreateApplicationUseDefaultFlowDataOperationCompleted == null)) {
                this.CreateApplicationUseDefaultFlowDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateApplicationUseDefaultFlowDataOperationCompleted);
            }
            this.InvokeAsync("CreateApplicationUseDefaultFlowData", new object[] {
                        formID,
                        company,
                        applicant,
                        applyReason,
                        applicationID,
                        GUID}, this.CreateApplicationUseDefaultFlowDataOperationCompleted, userState);
        }
        
        private void OnCreateApplicationUseDefaultFlowDataOperationCompleted(object arg) {
            if ((this.CreateApplicationUseDefaultFlowDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateApplicationUseDefaultFlowDataCompleted(this, new CreateApplicationUseDefaultFlowDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CreateApplication", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool CreateApplication(string formID, string company, string applicant, string applyReason, System.Data.DataSet flow, out string applicationID, out string GUID) {
            object[] results = this.Invoke("CreateApplication", new object[] {
                        formID,
                        company,
                        applicant,
                        applyReason,
                        flow});
            applicationID = ((string)(results[1]));
            GUID = ((string)(results[2]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void CreateApplicationAsync(string formID, string company, string applicant, string applyReason, System.Data.DataSet flow) {
            this.CreateApplicationAsync(formID, company, applicant, applyReason, flow, null);
        }
        
        /// <remarks/>
        public void CreateApplicationAsync(string formID, string company, string applicant, string applyReason, System.Data.DataSet flow, object userState) {
            if ((this.CreateApplicationOperationCompleted == null)) {
                this.CreateApplicationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateApplicationOperationCompleted);
            }
            this.InvokeAsync("CreateApplication", new object[] {
                        formID,
                        company,
                        applicant,
                        applyReason,
                        flow}, this.CreateApplicationOperationCompleted, userState);
        }
        
        private void OnCreateApplicationOperationCompleted(object arg) {
            if ((this.CreateApplicationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateApplicationCompleted(this, new CreateApplicationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CreateApplicationKeyID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool CreateApplicationKeyID(string formID, string company, string applicant, string applyReason, System.Data.DataSet flow, string keyID, out string applicationID, out string GUID) {
            object[] results = this.Invoke("CreateApplicationKeyID", new object[] {
                        formID,
                        company,
                        applicant,
                        applyReason,
                        flow,
                        keyID});
            applicationID = ((string)(results[1]));
            GUID = ((string)(results[2]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void CreateApplicationKeyIDAsync(string formID, string company, string applicant, string applyReason, System.Data.DataSet flow, string keyID) {
            this.CreateApplicationKeyIDAsync(formID, company, applicant, applyReason, flow, keyID, null);
        }
        
        /// <remarks/>
        public void CreateApplicationKeyIDAsync(string formID, string company, string applicant, string applyReason, System.Data.DataSet flow, string keyID, object userState) {
            if ((this.CreateApplicationKeyIDOperationCompleted == null)) {
                this.CreateApplicationKeyIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateApplicationKeyIDOperationCompleted);
            }
            this.InvokeAsync("CreateApplicationKeyID", new object[] {
                        formID,
                        company,
                        applicant,
                        applyReason,
                        flow,
                        keyID}, this.CreateApplicationKeyIDOperationCompleted, userState);
        }
        
        private void OnCreateApplicationKeyIDOperationCompleted(object arg) {
            if ((this.CreateApplicationKeyIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateApplicationKeyIDCompleted(this, new CreateApplicationKeyIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CancelApplication", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool CancelApplication(string formID, string applicationID, string GUID, string cancelReason) {
            object[] results = this.Invoke("CancelApplication", new object[] {
                        formID,
                        applicationID,
                        GUID,
                        cancelReason});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void CancelApplicationAsync(string formID, string applicationID, string GUID, string cancelReason) {
            this.CancelApplicationAsync(formID, applicationID, GUID, cancelReason, null);
        }
        
        /// <remarks/>
        public void CancelApplicationAsync(string formID, string applicationID, string GUID, string cancelReason, object userState) {
            if ((this.CancelApplicationOperationCompleted == null)) {
                this.CancelApplicationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCancelApplicationOperationCompleted);
            }
            this.InvokeAsync("CancelApplication", new object[] {
                        formID,
                        applicationID,
                        GUID,
                        cancelReason}, this.CancelApplicationOperationCompleted, userState);
        }
        
        private void OnCancelApplicationOperationCompleted(object arg) {
            if ((this.CancelApplicationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CancelApplicationCompleted(this, new CancelApplicationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CancelApplicationCancelBy", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool CancelApplicationCancelBy(string formID, string applicationID, string GUID, string cancelReason, string CancelBy) {
            object[] results = this.Invoke("CancelApplicationCancelBy", new object[] {
                        formID,
                        applicationID,
                        GUID,
                        cancelReason,
                        CancelBy});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void CancelApplicationCancelByAsync(string formID, string applicationID, string GUID, string cancelReason, string CancelBy) {
            this.CancelApplicationCancelByAsync(formID, applicationID, GUID, cancelReason, CancelBy, null);
        }
        
        /// <remarks/>
        public void CancelApplicationCancelByAsync(string formID, string applicationID, string GUID, string cancelReason, string CancelBy, object userState) {
            if ((this.CancelApplicationCancelByOperationCompleted == null)) {
                this.CancelApplicationCancelByOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCancelApplicationCancelByOperationCompleted);
            }
            this.InvokeAsync("CancelApplicationCancelBy", new object[] {
                        formID,
                        applicationID,
                        GUID,
                        cancelReason,
                        CancelBy}, this.CancelApplicationCancelByOperationCompleted, userState);
        }
        
        private void OnCancelApplicationCancelByOperationCompleted(object arg) {
            if ((this.CancelApplicationCancelByCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CancelApplicationCancelByCompleted(this, new CancelApplicationCancelByCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Approve", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Approve(string formID, string applicationID, string GUID, int flowNo, int sequenceNo, string approver, string approveStatus, string approveRemark) {
            object[] results = this.Invoke("Approve", new object[] {
                        formID,
                        applicationID,
                        GUID,
                        flowNo,
                        sequenceNo,
                        approver,
                        approveStatus,
                        approveRemark});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ApproveAsync(string formID, string applicationID, string GUID, int flowNo, int sequenceNo, string approver, string approveStatus, string approveRemark) {
            this.ApproveAsync(formID, applicationID, GUID, flowNo, sequenceNo, approver, approveStatus, approveRemark, null);
        }
        
        /// <remarks/>
        public void ApproveAsync(string formID, string applicationID, string GUID, int flowNo, int sequenceNo, string approver, string approveStatus, string approveRemark, object userState) {
            if ((this.ApproveOperationCompleted == null)) {
                this.ApproveOperationCompleted = new System.Threading.SendOrPostCallback(this.OnApproveOperationCompleted);
            }
            this.InvokeAsync("Approve", new object[] {
                        formID,
                        applicationID,
                        GUID,
                        flowNo,
                        sequenceNo,
                        approver,
                        approveStatus,
                        approveRemark}, this.ApproveOperationCompleted, userState);
        }
        
        private void OnApproveOperationCompleted(object arg) {
            if ((this.ApproveCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ApproveCompleted(this, new ApproveCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SetIsWFSApprove", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool SetIsWFSApprove(string formID, string applicationID, string GUID, int flowNo, int sequenceNo, string approver, string approveStatus, string approveRemark, string isWFS) {
            object[] results = this.Invoke("SetIsWFSApprove", new object[] {
                        formID,
                        applicationID,
                        GUID,
                        flowNo,
                        sequenceNo,
                        approver,
                        approveStatus,
                        approveRemark,
                        isWFS});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void SetIsWFSApproveAsync(string formID, string applicationID, string GUID, int flowNo, int sequenceNo, string approver, string approveStatus, string approveRemark, string isWFS) {
            this.SetIsWFSApproveAsync(formID, applicationID, GUID, flowNo, sequenceNo, approver, approveStatus, approveRemark, isWFS, null);
        }
        
        /// <remarks/>
        public void SetIsWFSApproveAsync(string formID, string applicationID, string GUID, int flowNo, int sequenceNo, string approver, string approveStatus, string approveRemark, string isWFS, object userState) {
            if ((this.SetIsWFSApproveOperationCompleted == null)) {
                this.SetIsWFSApproveOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetIsWFSApproveOperationCompleted);
            }
            this.InvokeAsync("SetIsWFSApprove", new object[] {
                        formID,
                        applicationID,
                        GUID,
                        flowNo,
                        sequenceNo,
                        approver,
                        approveStatus,
                        approveRemark,
                        isWFS}, this.SetIsWFSApproveOperationCompleted, userState);
        }
        
        private void OnSetIsWFSApproveOperationCompleted(object arg) {
            if ((this.SetIsWFSApproveCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetIsWFSApproveCompleted(this, new SetIsWFSApproveCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ModifyApprover", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ModifyApprover(string formID, string applicationID, string GUID, int flowNo, int sequenceNo, string approver, string agent, string modifyReason, string modifyBy) {
            object[] results = this.Invoke("ModifyApprover", new object[] {
                        formID,
                        applicationID,
                        GUID,
                        flowNo,
                        sequenceNo,
                        approver,
                        agent,
                        modifyReason,
                        modifyBy});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ModifyApproverAsync(string formID, string applicationID, string GUID, int flowNo, int sequenceNo, string approver, string agent, string modifyReason, string modifyBy) {
            this.ModifyApproverAsync(formID, applicationID, GUID, flowNo, sequenceNo, approver, agent, modifyReason, modifyBy, null);
        }
        
        /// <remarks/>
        public void ModifyApproverAsync(string formID, string applicationID, string GUID, int flowNo, int sequenceNo, string approver, string agent, string modifyReason, string modifyBy, object userState) {
            if ((this.ModifyApproverOperationCompleted == null)) {
                this.ModifyApproverOperationCompleted = new System.Threading.SendOrPostCallback(this.OnModifyApproverOperationCompleted);
            }
            this.InvokeAsync("ModifyApprover", new object[] {
                        formID,
                        applicationID,
                        GUID,
                        flowNo,
                        sequenceNo,
                        approver,
                        agent,
                        modifyReason,
                        modifyBy}, this.ModifyApproverOperationCompleted, userState);
        }
        
        private void OnModifyApproverOperationCompleted(object arg) {
            if ((this.ModifyApproverCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ModifyApproverCompleted(this, new ModifyApproverCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsertPreviousFlow", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool InsertPreviousFlow(string formID, string applicationID, string GUID, int flowNo, string approver, string agent, string modifyReason, string modifyBy) {
            object[] results = this.Invoke("InsertPreviousFlow", new object[] {
                        formID,
                        applicationID,
                        GUID,
                        flowNo,
                        approver,
                        agent,
                        modifyReason,
                        modifyBy});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void InsertPreviousFlowAsync(string formID, string applicationID, string GUID, int flowNo, string approver, string agent, string modifyReason, string modifyBy) {
            this.InsertPreviousFlowAsync(formID, applicationID, GUID, flowNo, approver, agent, modifyReason, modifyBy, null);
        }
        
        /// <remarks/>
        public void InsertPreviousFlowAsync(string formID, string applicationID, string GUID, int flowNo, string approver, string agent, string modifyReason, string modifyBy, object userState) {
            if ((this.InsertPreviousFlowOperationCompleted == null)) {
                this.InsertPreviousFlowOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertPreviousFlowOperationCompleted);
            }
            this.InvokeAsync("InsertPreviousFlow", new object[] {
                        formID,
                        applicationID,
                        GUID,
                        flowNo,
                        approver,
                        agent,
                        modifyReason,
                        modifyBy}, this.InsertPreviousFlowOperationCompleted, userState);
        }
        
        private void OnInsertPreviousFlowOperationCompleted(object arg) {
            if ((this.InsertPreviousFlowCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertPreviousFlowCompleted(this, new InsertPreviousFlowCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsertNextFlow", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool InsertNextFlow(string formID, string applicationID, string GUID, int flowNo, string approver, string agent, string modifyReason, string modifyBy) {
            object[] results = this.Invoke("InsertNextFlow", new object[] {
                        formID,
                        applicationID,
                        GUID,
                        flowNo,
                        approver,
                        agent,
                        modifyReason,
                        modifyBy});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void InsertNextFlowAsync(string formID, string applicationID, string GUID, int flowNo, string approver, string agent, string modifyReason, string modifyBy) {
            this.InsertNextFlowAsync(formID, applicationID, GUID, flowNo, approver, agent, modifyReason, modifyBy, null);
        }
        
        /// <remarks/>
        public void InsertNextFlowAsync(string formID, string applicationID, string GUID, int flowNo, string approver, string agent, string modifyReason, string modifyBy, object userState) {
            if ((this.InsertNextFlowOperationCompleted == null)) {
                this.InsertNextFlowOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertNextFlowOperationCompleted);
            }
            this.InvokeAsync("InsertNextFlow", new object[] {
                        formID,
                        applicationID,
                        GUID,
                        flowNo,
                        approver,
                        agent,
                        modifyReason,
                        modifyBy}, this.InsertNextFlowOperationCompleted, userState);
        }
        
        private void OnInsertNextFlowOperationCompleted(object arg) {
            if ((this.InsertNextFlowCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertNextFlowCompleted(this, new InsertNextFlowCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsertNextFlowIsOnlyNotice", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool InsertNextFlowIsOnlyNotice(string formID, string applicationID, string GUID, int flowNo, string approver, string agent, string modifyReason, string modifyBy) {
            object[] results = this.Invoke("InsertNextFlowIsOnlyNotice", new object[] {
                        formID,
                        applicationID,
                        GUID,
                        flowNo,
                        approver,
                        agent,
                        modifyReason,
                        modifyBy});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void InsertNextFlowIsOnlyNoticeAsync(string formID, string applicationID, string GUID, int flowNo, string approver, string agent, string modifyReason, string modifyBy) {
            this.InsertNextFlowIsOnlyNoticeAsync(formID, applicationID, GUID, flowNo, approver, agent, modifyReason, modifyBy, null);
        }
        
        /// <remarks/>
        public void InsertNextFlowIsOnlyNoticeAsync(string formID, string applicationID, string GUID, int flowNo, string approver, string agent, string modifyReason, string modifyBy, object userState) {
            if ((this.InsertNextFlowIsOnlyNoticeOperationCompleted == null)) {
                this.InsertNextFlowIsOnlyNoticeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertNextFlowIsOnlyNoticeOperationCompleted);
            }
            this.InvokeAsync("InsertNextFlowIsOnlyNotice", new object[] {
                        formID,
                        applicationID,
                        GUID,
                        flowNo,
                        approver,
                        agent,
                        modifyReason,
                        modifyBy}, this.InsertNextFlowIsOnlyNoticeOperationCompleted, userState);
        }
        
        private void OnInsertNextFlowIsOnlyNoticeOperationCompleted(object arg) {
            if ((this.InsertNextFlowIsOnlyNoticeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertNextFlowIsOnlyNoticeCompleted(this, new InsertNextFlowIsOnlyNoticeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsertNextFlowFullParameter", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool InsertNextFlowFullParameter(string formID, string applicationID, string GUID, int flowNo, string approver, string agent, string flowDescrption, bool isSimpleApprove, int dueDay, string dueProcessMode, string modifyReason, string modifyBy) {
            object[] results = this.Invoke("InsertNextFlowFullParameter", new object[] {
                        formID,
                        applicationID,
                        GUID,
                        flowNo,
                        approver,
                        agent,
                        flowDescrption,
                        isSimpleApprove,
                        dueDay,
                        dueProcessMode,
                        modifyReason,
                        modifyBy});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void InsertNextFlowFullParameterAsync(string formID, string applicationID, string GUID, int flowNo, string approver, string agent, string flowDescrption, bool isSimpleApprove, int dueDay, string dueProcessMode, string modifyReason, string modifyBy) {
            this.InsertNextFlowFullParameterAsync(formID, applicationID, GUID, flowNo, approver, agent, flowDescrption, isSimpleApprove, dueDay, dueProcessMode, modifyReason, modifyBy, null);
        }
        
        /// <remarks/>
        public void InsertNextFlowFullParameterAsync(string formID, string applicationID, string GUID, int flowNo, string approver, string agent, string flowDescrption, bool isSimpleApprove, int dueDay, string dueProcessMode, string modifyReason, string modifyBy, object userState) {
            if ((this.InsertNextFlowFullParameterOperationCompleted == null)) {
                this.InsertNextFlowFullParameterOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertNextFlowFullParameterOperationCompleted);
            }
            this.InvokeAsync("InsertNextFlowFullParameter", new object[] {
                        formID,
                        applicationID,
                        GUID,
                        flowNo,
                        approver,
                        agent,
                        flowDescrption,
                        isSimpleApprove,
                        dueDay,
                        dueProcessMode,
                        modifyReason,
                        modifyBy}, this.InsertNextFlowFullParameterOperationCompleted, userState);
        }
        
        private void OnInsertNextFlowFullParameterOperationCompleted(object arg) {
            if ((this.InsertNextFlowFullParameterCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertNextFlowFullParameterCompleted(this, new InsertNextFlowFullParameterCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsertSequence", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool InsertSequence(string formID, string applicationID, string GUID, int flowNo, string approver, string agent, string modifyReason, string modifyBy) {
            object[] results = this.Invoke("InsertSequence", new object[] {
                        formID,
                        applicationID,
                        GUID,
                        flowNo,
                        approver,
                        agent,
                        modifyReason,
                        modifyBy});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void InsertSequenceAsync(string formID, string applicationID, string GUID, int flowNo, string approver, string agent, string modifyReason, string modifyBy) {
            this.InsertSequenceAsync(formID, applicationID, GUID, flowNo, approver, agent, modifyReason, modifyBy, null);
        }
        
        /// <remarks/>
        public void InsertSequenceAsync(string formID, string applicationID, string GUID, int flowNo, string approver, string agent, string modifyReason, string modifyBy, object userState) {
            if ((this.InsertSequenceOperationCompleted == null)) {
                this.InsertSequenceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertSequenceOperationCompleted);
            }
            this.InvokeAsync("InsertSequence", new object[] {
                        formID,
                        applicationID,
                        GUID,
                        flowNo,
                        approver,
                        agent,
                        modifyReason,
                        modifyBy}, this.InsertSequenceOperationCompleted, userState);
        }
        
        private void OnInsertSequenceOperationCompleted(object arg) {
            if ((this.InsertSequenceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertSequenceCompleted(this, new InsertSequenceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeleteFlow", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool DeleteFlow(string formID, string applicationID, string GUID, int flowNo, int sequenceNo, string deleteReason, string deleteBy) {
            object[] results = this.Invoke("DeleteFlow", new object[] {
                        formID,
                        applicationID,
                        GUID,
                        flowNo,
                        sequenceNo,
                        deleteReason,
                        deleteBy});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteFlowAsync(string formID, string applicationID, string GUID, int flowNo, int sequenceNo, string deleteReason, string deleteBy) {
            this.DeleteFlowAsync(formID, applicationID, GUID, flowNo, sequenceNo, deleteReason, deleteBy, null);
        }
        
        /// <remarks/>
        public void DeleteFlowAsync(string formID, string applicationID, string GUID, int flowNo, int sequenceNo, string deleteReason, string deleteBy, object userState) {
            if ((this.DeleteFlowOperationCompleted == null)) {
                this.DeleteFlowOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteFlowOperationCompleted);
            }
            this.InvokeAsync("DeleteFlow", new object[] {
                        formID,
                        applicationID,
                        GUID,
                        flowNo,
                        sequenceNo,
                        deleteReason,
                        deleteBy}, this.DeleteFlowOperationCompleted, userState);
        }
        
        private void OnDeleteFlowOperationCompleted(object arg) {
            if ((this.DeleteFlowCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteFlowCompleted(this, new DeleteFlowCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/QueryApplicationStatus", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string QueryApplicationStatus(string formID, string applicationID, string GUID) {
            object[] results = this.Invoke("QueryApplicationStatus", new object[] {
                        formID,
                        applicationID,
                        GUID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void QueryApplicationStatusAsync(string formID, string applicationID, string GUID) {
            this.QueryApplicationStatusAsync(formID, applicationID, GUID, null);
        }
        
        /// <remarks/>
        public void QueryApplicationStatusAsync(string formID, string applicationID, string GUID, object userState) {
            if ((this.QueryApplicationStatusOperationCompleted == null)) {
                this.QueryApplicationStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQueryApplicationStatusOperationCompleted);
            }
            this.InvokeAsync("QueryApplicationStatus", new object[] {
                        formID,
                        applicationID,
                        GUID}, this.QueryApplicationStatusOperationCompleted, userState);
        }
        
        private void OnQueryApplicationStatusOperationCompleted(object arg) {
            if ((this.QueryApplicationStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QueryApplicationStatusCompleted(this, new QueryApplicationStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetApplicationApproveFlow", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetApplicationApproveFlow(string formID, string applicationID, string GUID) {
            object[] results = this.Invoke("GetApplicationApproveFlow", new object[] {
                        formID,
                        applicationID,
                        GUID});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetApplicationApproveFlowAsync(string formID, string applicationID, string GUID) {
            this.GetApplicationApproveFlowAsync(formID, applicationID, GUID, null);
        }
        
        /// <remarks/>
        public void GetApplicationApproveFlowAsync(string formID, string applicationID, string GUID, object userState) {
            if ((this.GetApplicationApproveFlowOperationCompleted == null)) {
                this.GetApplicationApproveFlowOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetApplicationApproveFlowOperationCompleted);
            }
            this.InvokeAsync("GetApplicationApproveFlow", new object[] {
                        formID,
                        applicationID,
                        GUID}, this.GetApplicationApproveFlowOperationCompleted, userState);
        }
        
        private void OnGetApplicationApproveFlowOperationCompleted(object arg) {
            if ((this.GetApplicationApproveFlowCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetApplicationApproveFlowCompleted(this, new GetApplicationApproveFlowCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCurrentFlowDescription", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetCurrentFlowDescription(string userEmplid, string comcod, string formID, string ApplicationID, int flowNo, int sequenceNo) {
            object[] results = this.Invoke("GetCurrentFlowDescription", new object[] {
                        userEmplid,
                        comcod,
                        formID,
                        ApplicationID,
                        flowNo,
                        sequenceNo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetCurrentFlowDescriptionAsync(string userEmplid, string comcod, string formID, string ApplicationID, int flowNo, int sequenceNo) {
            this.GetCurrentFlowDescriptionAsync(userEmplid, comcod, formID, ApplicationID, flowNo, sequenceNo, null);
        }
        
        /// <remarks/>
        public void GetCurrentFlowDescriptionAsync(string userEmplid, string comcod, string formID, string ApplicationID, int flowNo, int sequenceNo, object userState) {
            if ((this.GetCurrentFlowDescriptionOperationCompleted == null)) {
                this.GetCurrentFlowDescriptionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCurrentFlowDescriptionOperationCompleted);
            }
            this.InvokeAsync("GetCurrentFlowDescription", new object[] {
                        userEmplid,
                        comcod,
                        formID,
                        ApplicationID,
                        flowNo,
                        sequenceNo}, this.GetCurrentFlowDescriptionOperationCompleted, userState);
        }
        
        private void OnGetCurrentFlowDescriptionOperationCompleted(object arg) {
            if ((this.GetCurrentFlowDescriptionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCurrentFlowDescriptionCompleted(this, new GetCurrentFlowDescriptionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetApprData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetApprData(string strApprover, string strAppFrom, string strAppTo, string strFromDate, string strToDate, string strForm, string strStatus) {
            object[] results = this.Invoke("GetApprData", new object[] {
                        strApprover,
                        strAppFrom,
                        strAppTo,
                        strFromDate,
                        strToDate,
                        strForm,
                        strStatus});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetApprDataAsync(string strApprover, string strAppFrom, string strAppTo, string strFromDate, string strToDate, string strForm, string strStatus) {
            this.GetApprDataAsync(strApprover, strAppFrom, strAppTo, strFromDate, strToDate, strForm, strStatus, null);
        }
        
        /// <remarks/>
        public void GetApprDataAsync(string strApprover, string strAppFrom, string strAppTo, string strFromDate, string strToDate, string strForm, string strStatus, object userState) {
            if ((this.GetApprDataOperationCompleted == null)) {
                this.GetApprDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetApprDataOperationCompleted);
            }
            this.InvokeAsync("GetApprData", new object[] {
                        strApprover,
                        strAppFrom,
                        strAppTo,
                        strFromDate,
                        strToDate,
                        strForm,
                        strStatus}, this.GetApprDataOperationCompleted, userState);
        }
        
        private void OnGetApprDataOperationCompleted(object arg) {
            if ((this.GetApprDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetApprDataCompleted(this, new GetApprDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IsEndFlowNo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool IsEndFlowNo(string formID, string ApplicationID, int flowNo) {
            object[] results = this.Invoke("IsEndFlowNo", new object[] {
                        formID,
                        ApplicationID,
                        flowNo});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void IsEndFlowNoAsync(string formID, string ApplicationID, int flowNo) {
            this.IsEndFlowNoAsync(formID, ApplicationID, flowNo, null);
        }
        
        /// <remarks/>
        public void IsEndFlowNoAsync(string formID, string ApplicationID, int flowNo, object userState) {
            if ((this.IsEndFlowNoOperationCompleted == null)) {
                this.IsEndFlowNoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIsEndFlowNoOperationCompleted);
            }
            this.InvokeAsync("IsEndFlowNo", new object[] {
                        formID,
                        ApplicationID,
                        flowNo}, this.IsEndFlowNoOperationCompleted, userState);
        }
        
        private void OnIsEndFlowNoOperationCompleted(object arg) {
            if ((this.IsEndFlowNoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IsEndFlowNoCompleted(this, new IsEndFlowNoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateEmplid", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool UpdateEmplid(string varOldEmplid, string varNewEmplid) {
            object[] results = this.Invoke("UpdateEmplid", new object[] {
                        varOldEmplid,
                        varNewEmplid});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateEmplidAsync(string varOldEmplid, string varNewEmplid) {
            this.UpdateEmplidAsync(varOldEmplid, varNewEmplid, null);
        }
        
        /// <remarks/>
        public void UpdateEmplidAsync(string varOldEmplid, string varNewEmplid, object userState) {
            if ((this.UpdateEmplidOperationCompleted == null)) {
                this.UpdateEmplidOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateEmplidOperationCompleted);
            }
            this.InvokeAsync("UpdateEmplid", new object[] {
                        varOldEmplid,
                        varNewEmplid}, this.UpdateEmplidOperationCompleted, userState);
        }
        
        private void OnUpdateEmplidOperationCompleted(object arg) {
            if ((this.UpdateEmplidCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateEmplidCompleted(this, new UpdateEmplidCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void ReturnBasicFlowDataSetCompletedEventHandler(object sender, ReturnBasicFlowDataSetCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReturnBasicFlowDataSetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReturnBasicFlowDataSetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GetApproverByRMBCompletedEventHandler(object sender, GetApproverByRMBCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetApproverByRMBCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetApproverByRMBCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GetQMBApproverByRMBCompletedEventHandler(object sender, GetQMBApproverByRMBCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetQMBApproverByRMBCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetQMBApproverByRMBCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void ReturnApplicationIDGUIDCompletedEventHandler(object sender, ReturnApplicationIDGUIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReturnApplicationIDGUIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReturnApplicationIDGUIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string applicationID {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string GUID {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void CreateApplicationUseDefaultFlowDataCompletedEventHandler(object sender, CreateApplicationUseDefaultFlowDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateApplicationUseDefaultFlowDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateApplicationUseDefaultFlowDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void CreateApplicationCompletedEventHandler(object sender, CreateApplicationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateApplicationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateApplicationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string applicationID {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string GUID {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void CreateApplicationKeyIDCompletedEventHandler(object sender, CreateApplicationKeyIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateApplicationKeyIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateApplicationKeyIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string applicationID {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string GUID {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void CancelApplicationCompletedEventHandler(object sender, CancelApplicationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CancelApplicationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CancelApplicationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void CancelApplicationCancelByCompletedEventHandler(object sender, CancelApplicationCancelByCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CancelApplicationCancelByCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CancelApplicationCancelByCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void ApproveCompletedEventHandler(object sender, ApproveCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ApproveCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ApproveCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void SetIsWFSApproveCompletedEventHandler(object sender, SetIsWFSApproveCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetIsWFSApproveCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SetIsWFSApproveCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void ModifyApproverCompletedEventHandler(object sender, ModifyApproverCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ModifyApproverCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ModifyApproverCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void InsertPreviousFlowCompletedEventHandler(object sender, InsertPreviousFlowCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertPreviousFlowCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertPreviousFlowCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void InsertNextFlowCompletedEventHandler(object sender, InsertNextFlowCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertNextFlowCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertNextFlowCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void InsertNextFlowIsOnlyNoticeCompletedEventHandler(object sender, InsertNextFlowIsOnlyNoticeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertNextFlowIsOnlyNoticeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertNextFlowIsOnlyNoticeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void InsertNextFlowFullParameterCompletedEventHandler(object sender, InsertNextFlowFullParameterCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertNextFlowFullParameterCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertNextFlowFullParameterCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void InsertSequenceCompletedEventHandler(object sender, InsertSequenceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertSequenceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertSequenceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void DeleteFlowCompletedEventHandler(object sender, DeleteFlowCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteFlowCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteFlowCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void QueryApplicationStatusCompletedEventHandler(object sender, QueryApplicationStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QueryApplicationStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QueryApplicationStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GetApplicationApproveFlowCompletedEventHandler(object sender, GetApplicationApproveFlowCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetApplicationApproveFlowCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetApplicationApproveFlowCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GetCurrentFlowDescriptionCompletedEventHandler(object sender, GetCurrentFlowDescriptionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCurrentFlowDescriptionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCurrentFlowDescriptionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GetApprDataCompletedEventHandler(object sender, GetApprDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetApprDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetApprDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void IsEndFlowNoCompletedEventHandler(object sender, IsEndFlowNoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsEndFlowNoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IsEndFlowNoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void UpdateEmplidCompletedEventHandler(object sender, UpdateEmplidCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateEmplidCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateEmplidCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591