//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace QWMS.MM_Test {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="MM_ServiceSoap", Namespace="http://SDSWS05/SAP_WebService/QSMC/EC/MM/MM_Service.asmx")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(object[]))]
    public partial class MM_Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback Z_Ec_Getmat_Rfc2OperationCompleted;
        
        private System.Threading.SendOrPostCallback Z_Rfc_Ec503_MblnrOperationCompleted;
        
        private System.Threading.SendOrPostCallback Z_Rfc_Ec503_ForpmcOperationCompleted;
        
        private System.Threading.SendOrPostCallback Z_Rfc_Ec503_GrinfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback Z_Rfc_Rtv_From_Ec_311fOperationCompleted;
        
        private System.Threading.SendOrPostCallback Z_RFC_EC503_FORPUROperationCompleted;
        
        private System.Threading.SendOrPostCallback Z_RFC_SYN_503_MODEL_BUOperationCompleted;
        
        private System.Threading.SendOrPostCallback Z_RFC_GET503PACKINGOperationCompleted;
        
        private System.Threading.SendOrPostCallback ZRFC_503_EXCHANGE_RATEOperationCompleted;
        
        private System.Threading.SendOrPostCallback Z_EC_GETMAT_RFC_LOTOperationCompleted;
        
        private System.Threading.SendOrPostCallback ZBAPI_PO_CREATE1_851POOperationCompleted;
        
        private System.Threading.SendOrPostCallback ZBAPI_PO_CREATE1_851PO_DeleteOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetExportCustomsDataItemOperationCompleted;
        
        private System.Threading.SendOrPostCallback ZRFC_46PO_RECORDOperationCompleted;
        
        private System.Threading.SendOrPostCallback Z_MM_RFC_POSTYCNOperationCompleted;
        
        private System.Threading.SendOrPostCallback Z_RFC_PACKING_POSTOperationCompleted;
        
        private System.Threading.SendOrPostCallback Z_RFC_PACKING_POST_MOperationCompleted;
        
        private System.Threading.SendOrPostCallback Z_RFC_SCRAP_ZSC1_POSTOperationCompleted;
        
        private System.Threading.SendOrPostCallback Z_MM_RFC_COMPARE_QWMSSAPOperationCompleted;
        
        private System.Threading.SendOrPostCallback Z_MM_RFC_PACKING_TO_QWMSOperationCompleted;
        
        private System.Threading.SendOrPostCallback Z_RFC_PCBA_LIKE_ZCL2OperationCompleted;
        
        private System.Threading.SendOrPostCallback Z_RFC_MRPCODEOperationCompleted;
        
        private System.Threading.SendOrPostCallback Z_MM_RFC_POSTYCN_QMMCOperationCompleted;
        
        private System.Threading.SendOrPostCallback ZRFC_MM_SENDE_EDI_46POOperationCompleted;
        
        private System.Threading.SendOrPostCallback Z_MM_RFC_DIAOBO_QWMS_TO_SAPOperationCompleted;
        
        private System.Threading.SendOrPostCallback Z_RFC_SCRAP_GR_QWMSOperationCompleted;
        
        private System.Threading.SendOrPostCallback Z_MM_RFC_ZBRF_DATA_TO_RCOperationCompleted;
        
        private System.Threading.SendOrPostCallback Z_RFC_ZSCRAP_TO_QWMSOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public MM_Service() {
            this.Url = global::QWMS.Properties.Settings.Default.QWMS_MM_Test_MM_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event Z_Ec_Getmat_Rfc2CompletedEventHandler Z_Ec_Getmat_Rfc2Completed;
        
        /// <remarks/>
        public event Z_Rfc_Ec503_MblnrCompletedEventHandler Z_Rfc_Ec503_MblnrCompleted;
        
        /// <remarks/>
        public event Z_Rfc_Ec503_ForpmcCompletedEventHandler Z_Rfc_Ec503_ForpmcCompleted;
        
        /// <remarks/>
        public event Z_Rfc_Ec503_GrinfoCompletedEventHandler Z_Rfc_Ec503_GrinfoCompleted;
        
        /// <remarks/>
        public event Z_Rfc_Rtv_From_Ec_311fCompletedEventHandler Z_Rfc_Rtv_From_Ec_311fCompleted;
        
        /// <remarks/>
        public event Z_RFC_EC503_FORPURCompletedEventHandler Z_RFC_EC503_FORPURCompleted;
        
        /// <remarks/>
        public event Z_RFC_SYN_503_MODEL_BUCompletedEventHandler Z_RFC_SYN_503_MODEL_BUCompleted;
        
        /// <remarks/>
        public event Z_RFC_GET503PACKINGCompletedEventHandler Z_RFC_GET503PACKINGCompleted;
        
        /// <remarks/>
        public event ZRFC_503_EXCHANGE_RATECompletedEventHandler ZRFC_503_EXCHANGE_RATECompleted;
        
        /// <remarks/>
        public event Z_EC_GETMAT_RFC_LOTCompletedEventHandler Z_EC_GETMAT_RFC_LOTCompleted;
        
        /// <remarks/>
        public event ZBAPI_PO_CREATE1_851POCompletedEventHandler ZBAPI_PO_CREATE1_851POCompleted;
        
        /// <remarks/>
        public event ZBAPI_PO_CREATE1_851PO_DeleteCompletedEventHandler ZBAPI_PO_CREATE1_851PO_DeleteCompleted;
        
        /// <remarks/>
        public event GetExportCustomsDataItemCompletedEventHandler GetExportCustomsDataItemCompleted;
        
        /// <remarks/>
        public event ZRFC_46PO_RECORDCompletedEventHandler ZRFC_46PO_RECORDCompleted;
        
        /// <remarks/>
        public event Z_MM_RFC_POSTYCNCompletedEventHandler Z_MM_RFC_POSTYCNCompleted;
        
        /// <remarks/>
        public event Z_RFC_PACKING_POSTCompletedEventHandler Z_RFC_PACKING_POSTCompleted;
        
        /// <remarks/>
        public event Z_RFC_PACKING_POST_MCompletedEventHandler Z_RFC_PACKING_POST_MCompleted;
        
        /// <remarks/>
        public event Z_RFC_SCRAP_ZSC1_POSTCompletedEventHandler Z_RFC_SCRAP_ZSC1_POSTCompleted;
        
        /// <remarks/>
        public event Z_MM_RFC_COMPARE_QWMSSAPCompletedEventHandler Z_MM_RFC_COMPARE_QWMSSAPCompleted;
        
        /// <remarks/>
        public event Z_MM_RFC_PACKING_TO_QWMSCompletedEventHandler Z_MM_RFC_PACKING_TO_QWMSCompleted;
        
        /// <remarks/>
        public event Z_RFC_PCBA_LIKE_ZCL2CompletedEventHandler Z_RFC_PCBA_LIKE_ZCL2Completed;
        
        /// <remarks/>
        public event Z_RFC_MRPCODECompletedEventHandler Z_RFC_MRPCODECompleted;
        
        /// <remarks/>
        public event Z_MM_RFC_POSTYCN_QMMCCompletedEventHandler Z_MM_RFC_POSTYCN_QMMCCompleted;
        
        /// <remarks/>
        public event ZRFC_MM_SENDE_EDI_46POCompletedEventHandler ZRFC_MM_SENDE_EDI_46POCompleted;
        
        /// <remarks/>
        public event Z_MM_RFC_DIAOBO_QWMS_TO_SAPCompletedEventHandler Z_MM_RFC_DIAOBO_QWMS_TO_SAPCompleted;
        
        /// <remarks/>
        public event Z_RFC_SCRAP_GR_QWMSCompletedEventHandler Z_RFC_SCRAP_GR_QWMSCompleted;
        
        /// <remarks/>
        public event Z_MM_RFC_ZBRF_DATA_TO_RCCompletedEventHandler Z_MM_RFC_ZBRF_DATA_TO_RCCompleted;
        
        /// <remarks/>
        public event Z_RFC_ZSCRAP_TO_QWMSCompletedEventHandler Z_RFC_ZSCRAP_TO_QWMSCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://SDSWS05/SAP_WebService/QSMC/EC/MM/MM_Service.asmx/Z_Ec_Getmat_Rfc2", RequestNamespace="http://SDSWS05/SAP_WebService/QSMC/EC/MM/MM_Service.asmx", ResponseNamespace="http://SDSWS05/SAP_WebService/QSMC/EC/MM/MM_Service.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object[] Z_Ec_Getmat_Rfc2(string varClient, string varPlant, string varMaterial, string varVendorCode) {
            object[] results = this.Invoke("Z_Ec_Getmat_Rfc2", new object[] {
                        varClient,
                        varPlant,
                        varMaterial,
                        varVendorCode});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void Z_Ec_Getmat_Rfc2Async(string varClient, string varPlant, string varMaterial, string varVendorCode) {
            this.Z_Ec_Getmat_Rfc2Async(varClient, varPlant, varMaterial, varVendorCode, null);
        }
        
        /// <remarks/>
        public void Z_Ec_Getmat_Rfc2Async(string varClient, string varPlant, string varMaterial, string varVendorCode, object userState) {
            if ((this.Z_Ec_Getmat_Rfc2OperationCompleted == null)) {
                this.Z_Ec_Getmat_Rfc2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnZ_Ec_Getmat_Rfc2OperationCompleted);
            }
            this.InvokeAsync("Z_Ec_Getmat_Rfc2", new object[] {
                        varClient,
                        varPlant,
                        varMaterial,
                        varVendorCode}, this.Z_Ec_Getmat_Rfc2OperationCompleted, userState);
        }
        
        private void OnZ_Ec_Getmat_Rfc2OperationCompleted(object arg) {
            if ((this.Z_Ec_Getmat_Rfc2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Z_Ec_Getmat_Rfc2Completed(this, new Z_Ec_Getmat_Rfc2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://SDSWS05/SAP_WebService/QSMC/EC/MM/MM_Service.asmx/Z_Rfc_Ec503_Mblnr", RequestNamespace="http://SDSWS05/SAP_WebService/QSMC/EC/MM/MM_Service.asmx", ResponseNamespace="http://SDSWS05/SAP_WebService/QSMC/EC/MM/MM_Service.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet Z_Rfc_Ec503_Mblnr(System.Data.DataSet varConditions) {
            object[] results = this.Invoke("Z_Rfc_Ec503_Mblnr", new object[] {
                        varConditions});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void Z_Rfc_Ec503_MblnrAsync(System.Data.DataSet varConditions) {
            this.Z_Rfc_Ec503_MblnrAsync(varConditions, null);
        }
        
        /// <remarks/>
        public void Z_Rfc_Ec503_MblnrAsync(System.Data.DataSet varConditions, object userState) {
            if ((this.Z_Rfc_Ec503_MblnrOperationCompleted == null)) {
                this.Z_Rfc_Ec503_MblnrOperationCompleted = new System.Threading.SendOrPostCallback(this.OnZ_Rfc_Ec503_MblnrOperationCompleted);
            }
            this.InvokeAsync("Z_Rfc_Ec503_Mblnr", new object[] {
                        varConditions}, this.Z_Rfc_Ec503_MblnrOperationCompleted, userState);
        }
        
        private void OnZ_Rfc_Ec503_MblnrOperationCompleted(object arg) {
            if ((this.Z_Rfc_Ec503_MblnrCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Z_Rfc_Ec503_MblnrCompleted(this, new Z_Rfc_Ec503_MblnrCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://SDSWS05/SAP_WebService/QSMC/EC/MM/MM_Service.asmx/Z_Rfc_Ec503_Forpmc", RequestNamespace="http://SDSWS05/SAP_WebService/QSMC/EC/MM/MM_Service.asmx", ResponseNamespace="http://SDSWS05/SAP_WebService/QSMC/EC/MM/MM_Service.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet Z_Rfc_Ec503_Forpmc(System.Data.DataSet varCondition) {
            object[] results = this.Invoke("Z_Rfc_Ec503_Forpmc", new object[] {
                        varCondition});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void Z_Rfc_Ec503_ForpmcAsync(System.Data.DataSet varCondition) {
            this.Z_Rfc_Ec503_ForpmcAsync(varCondition, null);
        }
        
        /// <remarks/>
        public void Z_Rfc_Ec503_ForpmcAsync(System.Data.DataSet varCondition, object userState) {
            if ((this.Z_Rfc_Ec503_ForpmcOperationCompleted == null)) {
                this.Z_Rfc_Ec503_ForpmcOperationCompleted = new System.Threading.SendOrPostCallback(this.OnZ_Rfc_Ec503_ForpmcOperationCompleted);
            }
            this.InvokeAsync("Z_Rfc_Ec503_Forpmc", new object[] {
                        varCondition}, this.Z_Rfc_Ec503_ForpmcOperationCompleted, userState);
        }
        
        private void OnZ_Rfc_Ec503_ForpmcOperationCompleted(object arg) {
            if ((this.Z_Rfc_Ec503_ForpmcCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Z_Rfc_Ec503_ForpmcCompleted(this, new Z_Rfc_Ec503_ForpmcCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://SDSWS05/SAP_WebService/QSMC/EC/MM/MM_Service.asmx/Z_Rfc_Ec503_Grinfo", RequestNamespace="http://SDSWS05/SAP_WebService/QSMC/EC/MM/MM_Service.asmx", ResponseNamespace="http://SDSWS05/SAP_WebService/QSMC/EC/MM/MM_Service.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet Z_Rfc_Ec503_Grinfo(System.Data.DataSet varCondition, string varFlag) {
            object[] results = this.Invoke("Z_Rfc_Ec503_Grinfo", new object[] {
                        varCondition,
                        varFlag});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void Z_Rfc_Ec503_GrinfoAsync(System.Data.DataSet varCondition, string varFlag) {
            this.Z_Rfc_Ec503_GrinfoAsync(varCondition, varFlag, null);
        }
        
        /// <remarks/>
        public void Z_Rfc_Ec503_GrinfoAsync(System.Data.DataSet varCondition, string varFlag, object userState) {
            if ((this.Z_Rfc_Ec503_GrinfoOperationCompleted == null)) {
                this.Z_Rfc_Ec503_GrinfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnZ_Rfc_Ec503_GrinfoOperationCompleted);
            }
            this.InvokeAsync("Z_Rfc_Ec503_Grinfo", new object[] {
                        varCondition,
                        varFlag}, this.Z_Rfc_Ec503_GrinfoOperationCompleted, userState);
        }
        
        private void OnZ_Rfc_Ec503_GrinfoOperationCompleted(object arg) {
            if ((this.Z_Rfc_Ec503_GrinfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Z_Rfc_Ec503_GrinfoCompleted(this, new Z_Rfc_Ec503_GrinfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://SDSWS05/SAP_WebService/QSMC/EC/MM/MM_Service.asmx/Z_Rfc_Rtv_From_Ec_311f", RequestNamespace="http://SDSWS05/SAP_WebService/QSMC/EC/MM/MM_Service.asmx", ResponseNamespace="http://SDSWS05/SAP_WebService/QSMC/EC/MM/MM_Service.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Z_Rfc_Rtv_From_Ec_311f(ref System.Data.DataSet varCondition) {
            object[] results = this.Invoke("Z_Rfc_Rtv_From_Ec_311f", new object[] {
                        varCondition});
            varCondition = ((System.Data.DataSet)(results[1]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Z_Rfc_Rtv_From_Ec_311fAsync(System.Data.DataSet varCondition) {
            this.Z_Rfc_Rtv_From_Ec_311fAsync(varCondition, null);
        }
        
        /// <remarks/>
        public void Z_Rfc_Rtv_From_Ec_311fAsync(System.Data.DataSet varCondition, object userState) {
            if ((this.Z_Rfc_Rtv_From_Ec_311fOperationCompleted == null)) {
                this.Z_Rfc_Rtv_From_Ec_311fOperationCompleted = new System.Threading.SendOrPostCallback(this.OnZ_Rfc_Rtv_From_Ec_311fOperationCompleted);
            }
            this.InvokeAsync("Z_Rfc_Rtv_From_Ec_311f", new object[] {
                        varCondition}, this.Z_Rfc_Rtv_From_Ec_311fOperationCompleted, userState);
        }
        
        private void OnZ_Rfc_Rtv_From_Ec_311fOperationCompleted(object arg) {
            if ((this.Z_Rfc_Rtv_From_Ec_311fCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Z_Rfc_Rtv_From_Ec_311fCompleted(this, new Z_Rfc_Rtv_From_Ec_311fCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://SDSWS05/SAP_WebService/QSMC/EC/MM/MM_Service.asmx/Z_RFC_EC503_FORPUR", RequestNamespace="http://SDSWS05/SAP_WebService/QSMC/EC/MM/MM_Service.asmx", ResponseNamespace="http://SDSWS05/SAP_WebService/QSMC/EC/MM/MM_Service.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet Z_RFC_EC503_FORPUR(System.Data.DataSet varCondition) {
            object[] results = this.Invoke("Z_RFC_EC503_FORPUR", new object[] {
                        varCondition});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void Z_RFC_EC503_FORPURAsync(System.Data.DataSet varCondition) {
            this.Z_RFC_EC503_FORPURAsync(varCondition, null);
        }
        
        /// <remarks/>
        public void Z_RFC_EC503_FORPURAsync(System.Data.DataSet varCondition, object userState) {
            if ((this.Z_RFC_EC503_FORPUROperationCompleted == null)) {
                this.Z_RFC_EC503_FORPUROperationCompleted = new System.Threading.SendOrPostCallback(this.OnZ_RFC_EC503_FORPUROperationCompleted);
            }
            this.InvokeAsync("Z_RFC_EC503_FORPUR", new object[] {
                        varCondition}, this.Z_RFC_EC503_FORPUROperationCompleted, userState);
        }
        
        private void OnZ_RFC_EC503_FORPUROperationCompleted(object arg) {
            if ((this.Z_RFC_EC503_FORPURCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Z_RFC_EC503_FORPURCompleted(this, new Z_RFC_EC503_FORPURCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://SDSWS05/SAP_WebService/QSMC/EC/MM/MM_Service.asmx/Z_RFC_SYN_503_MODEL_BU", RequestNamespace="http://SDSWS05/SAP_WebService/QSMC/EC/MM/MM_Service.asmx", ResponseNamespace="http://SDSWS05/SAP_WebService/QSMC/EC/MM/MM_Service.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Z_RFC_SYN_503_MODEL_BU(string varCondition) {
            object[] results = this.Invoke("Z_RFC_SYN_503_MODEL_BU", new object[] {
                        varCondition});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Z_RFC_SYN_503_MODEL_BUAsync(string varCondition) {
            this.Z_RFC_SYN_503_MODEL_BUAsync(varCondition, null);
        }
        
        /// <remarks/>
        public void Z_RFC_SYN_503_MODEL_BUAsync(string varCondition, object userState) {
            if ((this.Z_RFC_SYN_503_MODEL_BUOperationCompleted == null)) {
                this.Z_RFC_SYN_503_MODEL_BUOperationCompleted = new System.Threading.SendOrPostCallback(this.OnZ_RFC_SYN_503_MODEL_BUOperationCompleted);
            }
            this.InvokeAsync("Z_RFC_SYN_503_MODEL_BU", new object[] {
                        varCondition}, this.Z_RFC_SYN_503_MODEL_BUOperationCompleted, userState);
        }
        
        private void OnZ_RFC_SYN_503_MODEL_BUOperationCompleted(object arg) {
            if ((this.Z_RFC_SYN_503_MODEL_BUCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Z_RFC_SYN_503_MODEL_BUCompleted(this, new Z_RFC_SYN_503_MODEL_BUCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://SDSWS05/SAP_WebService/QSMC/EC/MM/MM_Service.asmx/Z_RFC_GET503PACKING", RequestNamespace="http://SDSWS05/SAP_WebService/QSMC/EC/MM/MM_Service.asmx", ResponseNamespace="http://SDSWS05/SAP_WebService/QSMC/EC/MM/MM_Service.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Z_RFC_GET503PACKING(ref System.Data.DataSet varCondition) {
            object[] results = this.Invoke("Z_RFC_GET503PACKING", new object[] {
                        varCondition});
            varCondition = ((System.Data.DataSet)(results[1]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Z_RFC_GET503PACKINGAsync(System.Data.DataSet varCondition) {
            this.Z_RFC_GET503PACKINGAsync(varCondition, null);
        }
        
        /// <remarks/>
        public void Z_RFC_GET503PACKINGAsync(System.Data.DataSet varCondition, object userState) {
            if ((this.Z_RFC_GET503PACKINGOperationCompleted == null)) {
                this.Z_RFC_GET503PACKINGOperationCompleted = new System.Threading.SendOrPostCallback(this.OnZ_RFC_GET503PACKINGOperationCompleted);
            }
            this.InvokeAsync("Z_RFC_GET503PACKING", new object[] {
                        varCondition}, this.Z_RFC_GET503PACKINGOperationCompleted, userState);
        }
        
        private void OnZ_RFC_GET503PACKINGOperationCompleted(object arg) {
            if ((this.Z_RFC_GET503PACKINGCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Z_RFC_GET503PACKINGCompleted(this, new Z_RFC_GET503PACKINGCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://SDSWS05/SAP_WebService/QSMC/EC/MM/MM_Service.asmx/ZRFC_503_EXCHANGE_RATE", RequestNamespace="http://SDSWS05/SAP_WebService/QSMC/EC/MM/MM_Service.asmx", ResponseNamespace="http://SDSWS05/SAP_WebService/QSMC/EC/MM/MM_Service.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ZRFC_503_EXCHANGE_RATE(System.Data.DataSet varCondition) {
            object[] results = this.Invoke("ZRFC_503_EXCHANGE_RATE", new object[] {
                        varCondition});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ZRFC_503_EXCHANGE_RATEAsync(System.Data.DataSet varCondition) {
            this.ZRFC_503_EXCHANGE_RATEAsync(varCondition, null);
        }
        
        /// <remarks/>
        public void ZRFC_503_EXCHANGE_RATEAsync(System.Data.DataSet varCondition, object userState) {
            if ((this.ZRFC_503_EXCHANGE_RATEOperationCompleted == null)) {
                this.ZRFC_503_EXCHANGE_RATEOperationCompleted = new System.Threading.SendOrPostCallback(this.OnZRFC_503_EXCHANGE_RATEOperationCompleted);
            }
            this.InvokeAsync("ZRFC_503_EXCHANGE_RATE", new object[] {
                        varCondition}, this.ZRFC_503_EXCHANGE_RATEOperationCompleted, userState);
        }
        
        private void OnZRFC_503_EXCHANGE_RATEOperationCompleted(object arg) {
            if ((this.ZRFC_503_EXCHANGE_RATECompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ZRFC_503_EXCHANGE_RATECompleted(this, new ZRFC_503_EXCHANGE_RATECompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://SDSWS05/SAP_WebService/QSMC/EC/MM/MM_Service.asmx/Z_EC_GETMAT_RFC_LOT", RequestNamespace="http://SDSWS05/SAP_WebService/QSMC/EC/MM/MM_Service.asmx", ResponseNamespace="http://SDSWS05/SAP_WebService/QSMC/EC/MM/MM_Service.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable Z_EC_GETMAT_RFC_LOT(System.Data.DataTable varCondition) {
            object[] results = this.Invoke("Z_EC_GETMAT_RFC_LOT", new object[] {
                        varCondition});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void Z_EC_GETMAT_RFC_LOTAsync(System.Data.DataTable varCondition) {
            this.Z_EC_GETMAT_RFC_LOTAsync(varCondition, null);
        }
        
        /// <remarks/>
        public void Z_EC_GETMAT_RFC_LOTAsync(System.Data.DataTable varCondition, object userState) {
            if ((this.Z_EC_GETMAT_RFC_LOTOperationCompleted == null)) {
                this.Z_EC_GETMAT_RFC_LOTOperationCompleted = new System.Threading.SendOrPostCallback(this.OnZ_EC_GETMAT_RFC_LOTOperationCompleted);
            }
            this.InvokeAsync("Z_EC_GETMAT_RFC_LOT", new object[] {
                        varCondition}, this.Z_EC_GETMAT_RFC_LOTOperationCompleted, userState);
        }
        
        private void OnZ_EC_GETMAT_RFC_LOTOperationCompleted(object arg) {
            if ((this.Z_EC_GETMAT_RFC_LOTCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Z_EC_GETMAT_RFC_LOTCompleted(this, new Z_EC_GETMAT_RFC_LOTCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://SDSWS05/SAP_WebService/QSMC/EC/MM/MM_Service.asmx/ZBAPI_PO_CREATE1_851PO", RequestNamespace="http://SDSWS05/SAP_WebService/QSMC/EC/MM/MM_Service.asmx", ResponseNamespace="http://SDSWS05/SAP_WebService/QSMC/EC/MM/MM_Service.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet ZBAPI_PO_CREATE1_851PO(string varFlag, System.Data.DataSet vardsNHeader, System.Data.DataSet vardsNItem) {
            object[] results = this.Invoke("ZBAPI_PO_CREATE1_851PO", new object[] {
                        varFlag,
                        vardsNHeader,
                        vardsNItem});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void ZBAPI_PO_CREATE1_851POAsync(string varFlag, System.Data.DataSet vardsNHeader, System.Data.DataSet vardsNItem) {
            this.ZBAPI_PO_CREATE1_851POAsync(varFlag, vardsNHeader, vardsNItem, null);
        }
        
        /// <remarks/>
        public void ZBAPI_PO_CREATE1_851POAsync(string varFlag, System.Data.DataSet vardsNHeader, System.Data.DataSet vardsNItem, object userState) {
            if ((this.ZBAPI_PO_CREATE1_851POOperationCompleted == null)) {
                this.ZBAPI_PO_CREATE1_851POOperationCompleted = new System.Threading.SendOrPostCallback(this.OnZBAPI_PO_CREATE1_851POOperationCompleted);
            }
            this.InvokeAsync("ZBAPI_PO_CREATE1_851PO", new object[] {
                        varFlag,
                        vardsNHeader,
                        vardsNItem}, this.ZBAPI_PO_CREATE1_851POOperationCompleted, userState);
        }
        
        private void OnZBAPI_PO_CREATE1_851POOperationCompleted(object arg) {
            if ((this.ZBAPI_PO_CREATE1_851POCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ZBAPI_PO_CREATE1_851POCompleted(this, new ZBAPI_PO_CREATE1_851POCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://SDSWS05/SAP_WebService/QSMC/EC/MM/MM_Service.asmx/ZBAPI_PO_CREATE1_851PO_D" +
            "elete", RequestNamespace="http://SDSWS05/SAP_WebService/QSMC/EC/MM/MM_Service.asmx", ResponseNamespace="http://SDSWS05/SAP_WebService/QSMC/EC/MM/MM_Service.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet ZBAPI_PO_CREATE1_851PO_Delete(string varFlag, System.Data.DataSet vardsNData) {
            object[] results = this.Invoke("ZBAPI_PO_CREATE1_851PO_Delete", new object[] {
                        varFlag,
                        vardsNData});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void ZBAPI_PO_CREATE1_851PO_DeleteAsync(string varFlag, System.Data.DataSet vardsNData) {
            this.ZBAPI_PO_CREATE1_851PO_DeleteAsync(varFlag, vardsNData, null);
        }
        
        /// <remarks/>
        public void ZBAPI_PO_CREATE1_851PO_DeleteAsync(string varFlag, System.Data.DataSet vardsNData, object userState) {
            if ((this.ZBAPI_PO_CREATE1_851PO_DeleteOperationCompleted == null)) {
                this.ZBAPI_PO_CREATE1_851PO_DeleteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnZBAPI_PO_CREATE1_851PO_DeleteOperationCompleted);
            }
            this.InvokeAsync("ZBAPI_PO_CREATE1_851PO_Delete", new object[] {
                        varFlag,
                        vardsNData}, this.ZBAPI_PO_CREATE1_851PO_DeleteOperationCompleted, userState);
        }
        
        private void OnZBAPI_PO_CREATE1_851PO_DeleteOperationCompleted(object arg) {
            if ((this.ZBAPI_PO_CREATE1_851PO_DeleteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ZBAPI_PO_CREATE1_851PO_DeleteCompleted(this, new ZBAPI_PO_CREATE1_851PO_DeleteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://SDSWS05/SAP_WebService/QSMC/EC/MM/MM_Service.asmx/GetExportCustomsDataItem" +
            "", RequestNamespace="http://SDSWS05/SAP_WebService/QSMC/EC/MM/MM_Service.asmx", ResponseNamespace="http://SDSWS05/SAP_WebService/QSMC/EC/MM/MM_Service.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetExportCustomsDataItem(string Z_BUKRS, string Z_ZEXNO) {
            object[] results = this.Invoke("GetExportCustomsDataItem", new object[] {
                        Z_BUKRS,
                        Z_ZEXNO});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetExportCustomsDataItemAsync(string Z_BUKRS, string Z_ZEXNO) {
            this.GetExportCustomsDataItemAsync(Z_BUKRS, Z_ZEXNO, null);
        }
        
        /// <remarks/>
        public void GetExportCustomsDataItemAsync(string Z_BUKRS, string Z_ZEXNO, object userState) {
            if ((this.GetExportCustomsDataItemOperationCompleted == null)) {
                this.GetExportCustomsDataItemOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetExportCustomsDataItemOperationCompleted);
            }
            this.InvokeAsync("GetExportCustomsDataItem", new object[] {
                        Z_BUKRS,
                        Z_ZEXNO}, this.GetExportCustomsDataItemOperationCompleted, userState);
        }
        
        private void OnGetExportCustomsDataItemOperationCompleted(object arg) {
            if ((this.GetExportCustomsDataItemCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetExportCustomsDataItemCompleted(this, new GetExportCustomsDataItemCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://SDSWS05/SAP_WebService/QSMC/EC/MM/MM_Service.asmx/ZRFC_46PO_RECORD", RequestNamespace="http://SDSWS05/SAP_WebService/QSMC/EC/MM/MM_Service.asmx", ResponseNamespace="http://SDSWS05/SAP_WebService/QSMC/EC/MM/MM_Service.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet ZRFC_46PO_RECORD(string varFlag, System.Data.DataSet vardsData) {
            object[] results = this.Invoke("ZRFC_46PO_RECORD", new object[] {
                        varFlag,
                        vardsData});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void ZRFC_46PO_RECORDAsync(string varFlag, System.Data.DataSet vardsData) {
            this.ZRFC_46PO_RECORDAsync(varFlag, vardsData, null);
        }
        
        /// <remarks/>
        public void ZRFC_46PO_RECORDAsync(string varFlag, System.Data.DataSet vardsData, object userState) {
            if ((this.ZRFC_46PO_RECORDOperationCompleted == null)) {
                this.ZRFC_46PO_RECORDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnZRFC_46PO_RECORDOperationCompleted);
            }
            this.InvokeAsync("ZRFC_46PO_RECORD", new object[] {
                        varFlag,
                        vardsData}, this.ZRFC_46PO_RECORDOperationCompleted, userState);
        }
        
        private void OnZRFC_46PO_RECORDOperationCompleted(object arg) {
            if ((this.ZRFC_46PO_RECORDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ZRFC_46PO_RECORDCompleted(this, new ZRFC_46PO_RECORDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://SDSWS05/SAP_WebService/QSMC/EC/MM/MM_Service.asmx/Z_MM_RFC_POSTYCN", RequestNamespace="http://SDSWS05/SAP_WebService/QSMC/EC/MM/MM_Service.asmx", ResponseNamespace="http://SDSWS05/SAP_WebService/QSMC/EC/MM/MM_Service.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet Z_MM_RFC_POSTYCN(string varFlag, System.Data.DataSet dsData) {
            object[] results = this.Invoke("Z_MM_RFC_POSTYCN", new object[] {
                        varFlag,
                        dsData});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void Z_MM_RFC_POSTYCNAsync(string varFlag, System.Data.DataSet dsData) {
            this.Z_MM_RFC_POSTYCNAsync(varFlag, dsData, null);
        }
        
        /// <remarks/>
        public void Z_MM_RFC_POSTYCNAsync(string varFlag, System.Data.DataSet dsData, object userState) {
            if ((this.Z_MM_RFC_POSTYCNOperationCompleted == null)) {
                this.Z_MM_RFC_POSTYCNOperationCompleted = new System.Threading.SendOrPostCallback(this.OnZ_MM_RFC_POSTYCNOperationCompleted);
            }
            this.InvokeAsync("Z_MM_RFC_POSTYCN", new object[] {
                        varFlag,
                        dsData}, this.Z_MM_RFC_POSTYCNOperationCompleted, userState);
        }
        
        private void OnZ_MM_RFC_POSTYCNOperationCompleted(object arg) {
            if ((this.Z_MM_RFC_POSTYCNCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Z_MM_RFC_POSTYCNCompleted(this, new Z_MM_RFC_POSTYCNCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://SDSWS05/SAP_WebService/QSMC/EC/MM/MM_Service.asmx/Z_RFC_PACKING_POST", RequestNamespace="http://SDSWS05/SAP_WebService/QSMC/EC/MM/MM_Service.asmx", ResponseNamespace="http://SDSWS05/SAP_WebService/QSMC/EC/MM/MM_Service.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet Z_RFC_PACKING_POST(string varName, string varPnum, string varType, string varRun, System.Data.DataSet vardsData) {
            object[] results = this.Invoke("Z_RFC_PACKING_POST", new object[] {
                        varName,
                        varPnum,
                        varType,
                        varRun,
                        vardsData});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void Z_RFC_PACKING_POSTAsync(string varName, string varPnum, string varType, string varRun, System.Data.DataSet vardsData) {
            this.Z_RFC_PACKING_POSTAsync(varName, varPnum, varType, varRun, vardsData, null);
        }
        
        /// <remarks/>
        public void Z_RFC_PACKING_POSTAsync(string varName, string varPnum, string varType, string varRun, System.Data.DataSet vardsData, object userState) {
            if ((this.Z_RFC_PACKING_POSTOperationCompleted == null)) {
                this.Z_RFC_PACKING_POSTOperationCompleted = new System.Threading.SendOrPostCallback(this.OnZ_RFC_PACKING_POSTOperationCompleted);
            }
            this.InvokeAsync("Z_RFC_PACKING_POST", new object[] {
                        varName,
                        varPnum,
                        varType,
                        varRun,
                        vardsData}, this.Z_RFC_PACKING_POSTOperationCompleted, userState);
        }
        
        private void OnZ_RFC_PACKING_POSTOperationCompleted(object arg) {
            if ((this.Z_RFC_PACKING_POSTCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Z_RFC_PACKING_POSTCompleted(this, new Z_RFC_PACKING_POSTCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://SDSWS05/SAP_WebService/QSMC/EC/MM/MM_Service.asmx/Z_RFC_PACKING_POST_M", RequestNamespace="http://SDSWS05/SAP_WebService/QSMC/EC/MM/MM_Service.asmx", ResponseNamespace="http://SDSWS05/SAP_WebService/QSMC/EC/MM/MM_Service.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet Z_RFC_PACKING_POST_M(string varName, string varPnum, string varType, string varRun, System.Data.DataSet vardsData) {
            object[] results = this.Invoke("Z_RFC_PACKING_POST_M", new object[] {
                        varName,
                        varPnum,
                        varType,
                        varRun,
                        vardsData});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void Z_RFC_PACKING_POST_MAsync(string varName, string varPnum, string varType, string varRun, System.Data.DataSet vardsData) {
            this.Z_RFC_PACKING_POST_MAsync(varName, varPnum, varType, varRun, vardsData, null);
        }
        
        /// <remarks/>
        public void Z_RFC_PACKING_POST_MAsync(string varName, string varPnum, string varType, string varRun, System.Data.DataSet vardsData, object userState) {
            if ((this.Z_RFC_PACKING_POST_MOperationCompleted == null)) {
                this.Z_RFC_PACKING_POST_MOperationCompleted = new System.Threading.SendOrPostCallback(this.OnZ_RFC_PACKING_POST_MOperationCompleted);
            }
            this.InvokeAsync("Z_RFC_PACKING_POST_M", new object[] {
                        varName,
                        varPnum,
                        varType,
                        varRun,
                        vardsData}, this.Z_RFC_PACKING_POST_MOperationCompleted, userState);
        }
        
        private void OnZ_RFC_PACKING_POST_MOperationCompleted(object arg) {
            if ((this.Z_RFC_PACKING_POST_MCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Z_RFC_PACKING_POST_MCompleted(this, new Z_RFC_PACKING_POST_MCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://SDSWS05/SAP_WebService/QSMC/EC/MM/MM_Service.asmx/Z_RFC_SCRAP_ZSC1_POST", RequestNamespace="http://SDSWS05/SAP_WebService/QSMC/EC/MM/MM_Service.asmx", ResponseNamespace="http://SDSWS05/SAP_WebService/QSMC/EC/MM/MM_Service.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet Z_RFC_SCRAP_ZSC1_POST(string varMANDT, string varMJAHR, string varWERKS, string varSCPNO) {
            object[] results = this.Invoke("Z_RFC_SCRAP_ZSC1_POST", new object[] {
                        varMANDT,
                        varMJAHR,
                        varWERKS,
                        varSCPNO});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void Z_RFC_SCRAP_ZSC1_POSTAsync(string varMANDT, string varMJAHR, string varWERKS, string varSCPNO) {
            this.Z_RFC_SCRAP_ZSC1_POSTAsync(varMANDT, varMJAHR, varWERKS, varSCPNO, null);
        }
        
        /// <remarks/>
        public void Z_RFC_SCRAP_ZSC1_POSTAsync(string varMANDT, string varMJAHR, string varWERKS, string varSCPNO, object userState) {
            if ((this.Z_RFC_SCRAP_ZSC1_POSTOperationCompleted == null)) {
                this.Z_RFC_SCRAP_ZSC1_POSTOperationCompleted = new System.Threading.SendOrPostCallback(this.OnZ_RFC_SCRAP_ZSC1_POSTOperationCompleted);
            }
            this.InvokeAsync("Z_RFC_SCRAP_ZSC1_POST", new object[] {
                        varMANDT,
                        varMJAHR,
                        varWERKS,
                        varSCPNO}, this.Z_RFC_SCRAP_ZSC1_POSTOperationCompleted, userState);
        }
        
        private void OnZ_RFC_SCRAP_ZSC1_POSTOperationCompleted(object arg) {
            if ((this.Z_RFC_SCRAP_ZSC1_POSTCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Z_RFC_SCRAP_ZSC1_POSTCompleted(this, new Z_RFC_SCRAP_ZSC1_POSTCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://SDSWS05/SAP_WebService/QSMC/EC/MM/MM_Service.asmx/Z_MM_RFC_COMPARE_QWMSSAP" +
            "", RequestNamespace="http://SDSWS05/SAP_WebService/QSMC/EC/MM/MM_Service.asmx", ResponseNamespace="http://SDSWS05/SAP_WebService/QSMC/EC/MM/MM_Service.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet Z_MM_RFC_COMPARE_QWMSSAP(System.Data.DataSet varCondition, string varFlag) {
            object[] results = this.Invoke("Z_MM_RFC_COMPARE_QWMSSAP", new object[] {
                        varCondition,
                        varFlag});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void Z_MM_RFC_COMPARE_QWMSSAPAsync(System.Data.DataSet varCondition, string varFlag) {
            this.Z_MM_RFC_COMPARE_QWMSSAPAsync(varCondition, varFlag, null);
        }
        
        /// <remarks/>
        public void Z_MM_RFC_COMPARE_QWMSSAPAsync(System.Data.DataSet varCondition, string varFlag, object userState) {
            if ((this.Z_MM_RFC_COMPARE_QWMSSAPOperationCompleted == null)) {
                this.Z_MM_RFC_COMPARE_QWMSSAPOperationCompleted = new System.Threading.SendOrPostCallback(this.OnZ_MM_RFC_COMPARE_QWMSSAPOperationCompleted);
            }
            this.InvokeAsync("Z_MM_RFC_COMPARE_QWMSSAP", new object[] {
                        varCondition,
                        varFlag}, this.Z_MM_RFC_COMPARE_QWMSSAPOperationCompleted, userState);
        }
        
        private void OnZ_MM_RFC_COMPARE_QWMSSAPOperationCompleted(object arg) {
            if ((this.Z_MM_RFC_COMPARE_QWMSSAPCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Z_MM_RFC_COMPARE_QWMSSAPCompleted(this, new Z_MM_RFC_COMPARE_QWMSSAPCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://SDSWS05/SAP_WebService/QSMC/EC/MM/MM_Service.asmx/Z_MM_RFC_PACKING_TO_QWMS" +
            "", RequestNamespace="http://SDSWS05/SAP_WebService/QSMC/EC/MM/MM_Service.asmx", ResponseNamespace="http://SDSWS05/SAP_WebService/QSMC/EC/MM/MM_Service.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet Z_MM_RFC_PACKING_TO_QWMS(string varPN) {
            object[] results = this.Invoke("Z_MM_RFC_PACKING_TO_QWMS", new object[] {
                        varPN});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void Z_MM_RFC_PACKING_TO_QWMSAsync(string varPN) {
            this.Z_MM_RFC_PACKING_TO_QWMSAsync(varPN, null);
        }
        
        /// <remarks/>
        public void Z_MM_RFC_PACKING_TO_QWMSAsync(string varPN, object userState) {
            if ((this.Z_MM_RFC_PACKING_TO_QWMSOperationCompleted == null)) {
                this.Z_MM_RFC_PACKING_TO_QWMSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnZ_MM_RFC_PACKING_TO_QWMSOperationCompleted);
            }
            this.InvokeAsync("Z_MM_RFC_PACKING_TO_QWMS", new object[] {
                        varPN}, this.Z_MM_RFC_PACKING_TO_QWMSOperationCompleted, userState);
        }
        
        private void OnZ_MM_RFC_PACKING_TO_QWMSOperationCompleted(object arg) {
            if ((this.Z_MM_RFC_PACKING_TO_QWMSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Z_MM_RFC_PACKING_TO_QWMSCompleted(this, new Z_MM_RFC_PACKING_TO_QWMSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://SDSWS05/SAP_WebService/QSMC/EC/MM/MM_Service.asmx/Z_RFC_PCBA_LIKE_ZCL2", RequestNamespace="http://SDSWS05/SAP_WebService/QSMC/EC/MM/MM_Service.asmx", ResponseNamespace="http://SDSWS05/SAP_WebService/QSMC/EC/MM/MM_Service.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet Z_RFC_PCBA_LIKE_ZCL2(string varMANDT, string varMJAHR, string varWERKS, string varZBLBNO) {
            object[] results = this.Invoke("Z_RFC_PCBA_LIKE_ZCL2", new object[] {
                        varMANDT,
                        varMJAHR,
                        varWERKS,
                        varZBLBNO});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void Z_RFC_PCBA_LIKE_ZCL2Async(string varMANDT, string varMJAHR, string varWERKS, string varZBLBNO) {
            this.Z_RFC_PCBA_LIKE_ZCL2Async(varMANDT, varMJAHR, varWERKS, varZBLBNO, null);
        }
        
        /// <remarks/>
        public void Z_RFC_PCBA_LIKE_ZCL2Async(string varMANDT, string varMJAHR, string varWERKS, string varZBLBNO, object userState) {
            if ((this.Z_RFC_PCBA_LIKE_ZCL2OperationCompleted == null)) {
                this.Z_RFC_PCBA_LIKE_ZCL2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnZ_RFC_PCBA_LIKE_ZCL2OperationCompleted);
            }
            this.InvokeAsync("Z_RFC_PCBA_LIKE_ZCL2", new object[] {
                        varMANDT,
                        varMJAHR,
                        varWERKS,
                        varZBLBNO}, this.Z_RFC_PCBA_LIKE_ZCL2OperationCompleted, userState);
        }
        
        private void OnZ_RFC_PCBA_LIKE_ZCL2OperationCompleted(object arg) {
            if ((this.Z_RFC_PCBA_LIKE_ZCL2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Z_RFC_PCBA_LIKE_ZCL2Completed(this, new Z_RFC_PCBA_LIKE_ZCL2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://SDSWS05/SAP_WebService/QSMC/EC/MM/MM_Service.asmx/Z_RFC_MRPCODE", RequestNamespace="http://SDSWS05/SAP_WebService/QSMC/EC/MM/MM_Service.asmx", ResponseNamespace="http://SDSWS05/SAP_WebService/QSMC/EC/MM/MM_Service.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet Z_RFC_MRPCODE(System.Data.DataSet dsData) {
            object[] results = this.Invoke("Z_RFC_MRPCODE", new object[] {
                        dsData});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void Z_RFC_MRPCODEAsync(System.Data.DataSet dsData) {
            this.Z_RFC_MRPCODEAsync(dsData, null);
        }
        
        /// <remarks/>
        public void Z_RFC_MRPCODEAsync(System.Data.DataSet dsData, object userState) {
            if ((this.Z_RFC_MRPCODEOperationCompleted == null)) {
                this.Z_RFC_MRPCODEOperationCompleted = new System.Threading.SendOrPostCallback(this.OnZ_RFC_MRPCODEOperationCompleted);
            }
            this.InvokeAsync("Z_RFC_MRPCODE", new object[] {
                        dsData}, this.Z_RFC_MRPCODEOperationCompleted, userState);
        }
        
        private void OnZ_RFC_MRPCODEOperationCompleted(object arg) {
            if ((this.Z_RFC_MRPCODECompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Z_RFC_MRPCODECompleted(this, new Z_RFC_MRPCODECompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://SDSWS05/SAP_WebService/QSMC/EC/MM/MM_Service.asmx/Z_MM_RFC_POSTYCN_QMMC", RequestNamespace="http://SDSWS05/SAP_WebService/QSMC/EC/MM/MM_Service.asmx", ResponseNamespace="http://SDSWS05/SAP_WebService/QSMC/EC/MM/MM_Service.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet Z_MM_RFC_POSTYCN_QMMC(string varFlag, System.Data.DataSet dsData) {
            object[] results = this.Invoke("Z_MM_RFC_POSTYCN_QMMC", new object[] {
                        varFlag,
                        dsData});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void Z_MM_RFC_POSTYCN_QMMCAsync(string varFlag, System.Data.DataSet dsData) {
            this.Z_MM_RFC_POSTYCN_QMMCAsync(varFlag, dsData, null);
        }
        
        /// <remarks/>
        public void Z_MM_RFC_POSTYCN_QMMCAsync(string varFlag, System.Data.DataSet dsData, object userState) {
            if ((this.Z_MM_RFC_POSTYCN_QMMCOperationCompleted == null)) {
                this.Z_MM_RFC_POSTYCN_QMMCOperationCompleted = new System.Threading.SendOrPostCallback(this.OnZ_MM_RFC_POSTYCN_QMMCOperationCompleted);
            }
            this.InvokeAsync("Z_MM_RFC_POSTYCN_QMMC", new object[] {
                        varFlag,
                        dsData}, this.Z_MM_RFC_POSTYCN_QMMCOperationCompleted, userState);
        }
        
        private void OnZ_MM_RFC_POSTYCN_QMMCOperationCompleted(object arg) {
            if ((this.Z_MM_RFC_POSTYCN_QMMCCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Z_MM_RFC_POSTYCN_QMMCCompleted(this, new Z_MM_RFC_POSTYCN_QMMCCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://SDSWS05/SAP_WebService/QSMC/EC/MM/MM_Service.asmx/ZRFC_MM_SENDE_EDI_46PO", RequestNamespace="http://SDSWS05/SAP_WebService/QSMC/EC/MM/MM_Service.asmx", ResponseNamespace="http://SDSWS05/SAP_WebService/QSMC/EC/MM/MM_Service.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable ZRFC_MM_SENDE_EDI_46PO(System.Data.DataTable varCondition) {
            object[] results = this.Invoke("ZRFC_MM_SENDE_EDI_46PO", new object[] {
                        varCondition});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void ZRFC_MM_SENDE_EDI_46POAsync(System.Data.DataTable varCondition) {
            this.ZRFC_MM_SENDE_EDI_46POAsync(varCondition, null);
        }
        
        /// <remarks/>
        public void ZRFC_MM_SENDE_EDI_46POAsync(System.Data.DataTable varCondition, object userState) {
            if ((this.ZRFC_MM_SENDE_EDI_46POOperationCompleted == null)) {
                this.ZRFC_MM_SENDE_EDI_46POOperationCompleted = new System.Threading.SendOrPostCallback(this.OnZRFC_MM_SENDE_EDI_46POOperationCompleted);
            }
            this.InvokeAsync("ZRFC_MM_SENDE_EDI_46PO", new object[] {
                        varCondition}, this.ZRFC_MM_SENDE_EDI_46POOperationCompleted, userState);
        }
        
        private void OnZRFC_MM_SENDE_EDI_46POOperationCompleted(object arg) {
            if ((this.ZRFC_MM_SENDE_EDI_46POCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ZRFC_MM_SENDE_EDI_46POCompleted(this, new ZRFC_MM_SENDE_EDI_46POCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://SDSWS05/SAP_WebService/QSMC/EC/MM/MM_Service.asmx/Z_MM_RFC_DIAOBO_QWMS_TO_" +
            "SAP", RequestNamespace="http://SDSWS05/SAP_WebService/QSMC/EC/MM/MM_Service.asmx", ResponseNamespace="http://SDSWS05/SAP_WebService/QSMC/EC/MM/MM_Service.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet Z_MM_RFC_DIAOBO_QWMS_TO_SAP(string varFlag, System.Data.DataSet vardsData) {
            object[] results = this.Invoke("Z_MM_RFC_DIAOBO_QWMS_TO_SAP", new object[] {
                        varFlag,
                        vardsData});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void Z_MM_RFC_DIAOBO_QWMS_TO_SAPAsync(string varFlag, System.Data.DataSet vardsData) {
            this.Z_MM_RFC_DIAOBO_QWMS_TO_SAPAsync(varFlag, vardsData, null);
        }
        
        /// <remarks/>
        public void Z_MM_RFC_DIAOBO_QWMS_TO_SAPAsync(string varFlag, System.Data.DataSet vardsData, object userState) {
            if ((this.Z_MM_RFC_DIAOBO_QWMS_TO_SAPOperationCompleted == null)) {
                this.Z_MM_RFC_DIAOBO_QWMS_TO_SAPOperationCompleted = new System.Threading.SendOrPostCallback(this.OnZ_MM_RFC_DIAOBO_QWMS_TO_SAPOperationCompleted);
            }
            this.InvokeAsync("Z_MM_RFC_DIAOBO_QWMS_TO_SAP", new object[] {
                        varFlag,
                        vardsData}, this.Z_MM_RFC_DIAOBO_QWMS_TO_SAPOperationCompleted, userState);
        }
        
        private void OnZ_MM_RFC_DIAOBO_QWMS_TO_SAPOperationCompleted(object arg) {
            if ((this.Z_MM_RFC_DIAOBO_QWMS_TO_SAPCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Z_MM_RFC_DIAOBO_QWMS_TO_SAPCompleted(this, new Z_MM_RFC_DIAOBO_QWMS_TO_SAPCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://SDSWS05/SAP_WebService/QSMC/EC/MM/MM_Service.asmx/Z_RFC_SCRAP_GR_QWMS", RequestNamespace="http://SDSWS05/SAP_WebService/QSMC/EC/MM/MM_Service.asmx", ResponseNamespace="http://SDSWS05/SAP_WebService/QSMC/EC/MM/MM_Service.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet Z_RFC_SCRAP_GR_QWMS(System.Data.DataSet vardsData) {
            object[] results = this.Invoke("Z_RFC_SCRAP_GR_QWMS", new object[] {
                        vardsData});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void Z_RFC_SCRAP_GR_QWMSAsync(System.Data.DataSet vardsData) {
            this.Z_RFC_SCRAP_GR_QWMSAsync(vardsData, null);
        }
        
        /// <remarks/>
        public void Z_RFC_SCRAP_GR_QWMSAsync(System.Data.DataSet vardsData, object userState) {
            if ((this.Z_RFC_SCRAP_GR_QWMSOperationCompleted == null)) {
                this.Z_RFC_SCRAP_GR_QWMSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnZ_RFC_SCRAP_GR_QWMSOperationCompleted);
            }
            this.InvokeAsync("Z_RFC_SCRAP_GR_QWMS", new object[] {
                        vardsData}, this.Z_RFC_SCRAP_GR_QWMSOperationCompleted, userState);
        }
        
        private void OnZ_RFC_SCRAP_GR_QWMSOperationCompleted(object arg) {
            if ((this.Z_RFC_SCRAP_GR_QWMSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Z_RFC_SCRAP_GR_QWMSCompleted(this, new Z_RFC_SCRAP_GR_QWMSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://SDSWS05/SAP_WebService/QSMC/EC/MM/MM_Service.asmx/Z_MM_RFC_ZBRF_DATA_TO_RC" +
            "", RequestNamespace="http://SDSWS05/SAP_WebService/QSMC/EC/MM/MM_Service.asmx", ResponseNamespace="http://SDSWS05/SAP_WebService/QSMC/EC/MM/MM_Service.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet Z_MM_RFC_ZBRF_DATA_TO_RC(string invoiceNO) {
            object[] results = this.Invoke("Z_MM_RFC_ZBRF_DATA_TO_RC", new object[] {
                        invoiceNO});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void Z_MM_RFC_ZBRF_DATA_TO_RCAsync(string invoiceNO) {
            this.Z_MM_RFC_ZBRF_DATA_TO_RCAsync(invoiceNO, null);
        }
        
        /// <remarks/>
        public void Z_MM_RFC_ZBRF_DATA_TO_RCAsync(string invoiceNO, object userState) {
            if ((this.Z_MM_RFC_ZBRF_DATA_TO_RCOperationCompleted == null)) {
                this.Z_MM_RFC_ZBRF_DATA_TO_RCOperationCompleted = new System.Threading.SendOrPostCallback(this.OnZ_MM_RFC_ZBRF_DATA_TO_RCOperationCompleted);
            }
            this.InvokeAsync("Z_MM_RFC_ZBRF_DATA_TO_RC", new object[] {
                        invoiceNO}, this.Z_MM_RFC_ZBRF_DATA_TO_RCOperationCompleted, userState);
        }
        
        private void OnZ_MM_RFC_ZBRF_DATA_TO_RCOperationCompleted(object arg) {
            if ((this.Z_MM_RFC_ZBRF_DATA_TO_RCCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Z_MM_RFC_ZBRF_DATA_TO_RCCompleted(this, new Z_MM_RFC_ZBRF_DATA_TO_RCCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://SDSWS05/SAP_WebService/QSMC/EC/MM/MM_Service.asmx/Z_RFC_ZSCRAP_TO_QWMS", RequestNamespace="http://SDSWS05/SAP_WebService/QSMC/EC/MM/MM_Service.asmx", ResponseNamespace="http://SDSWS05/SAP_WebService/QSMC/EC/MM/MM_Service.asmx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet Z_RFC_ZSCRAP_TO_QWMS(System.Data.DataSet vardsData) {
            object[] results = this.Invoke("Z_RFC_ZSCRAP_TO_QWMS", new object[] {
                        vardsData});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void Z_RFC_ZSCRAP_TO_QWMSAsync(System.Data.DataSet vardsData) {
            this.Z_RFC_ZSCRAP_TO_QWMSAsync(vardsData, null);
        }
        
        /// <remarks/>
        public void Z_RFC_ZSCRAP_TO_QWMSAsync(System.Data.DataSet vardsData, object userState) {
            if ((this.Z_RFC_ZSCRAP_TO_QWMSOperationCompleted == null)) {
                this.Z_RFC_ZSCRAP_TO_QWMSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnZ_RFC_ZSCRAP_TO_QWMSOperationCompleted);
            }
            this.InvokeAsync("Z_RFC_ZSCRAP_TO_QWMS", new object[] {
                        vardsData}, this.Z_RFC_ZSCRAP_TO_QWMSOperationCompleted, userState);
        }
        
        private void OnZ_RFC_ZSCRAP_TO_QWMSOperationCompleted(object arg) {
            if ((this.Z_RFC_ZSCRAP_TO_QWMSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Z_RFC_ZSCRAP_TO_QWMSCompleted(this, new Z_RFC_ZSCRAP_TO_QWMSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void Z_Ec_Getmat_Rfc2CompletedEventHandler(object sender, Z_Ec_Getmat_Rfc2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Z_Ec_Getmat_Rfc2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Z_Ec_Getmat_Rfc2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void Z_Rfc_Ec503_MblnrCompletedEventHandler(object sender, Z_Rfc_Ec503_MblnrCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Z_Rfc_Ec503_MblnrCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Z_Rfc_Ec503_MblnrCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void Z_Rfc_Ec503_ForpmcCompletedEventHandler(object sender, Z_Rfc_Ec503_ForpmcCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Z_Rfc_Ec503_ForpmcCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Z_Rfc_Ec503_ForpmcCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void Z_Rfc_Ec503_GrinfoCompletedEventHandler(object sender, Z_Rfc_Ec503_GrinfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Z_Rfc_Ec503_GrinfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Z_Rfc_Ec503_GrinfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void Z_Rfc_Rtv_From_Ec_311fCompletedEventHandler(object sender, Z_Rfc_Rtv_From_Ec_311fCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Z_Rfc_Rtv_From_Ec_311fCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Z_Rfc_Rtv_From_Ec_311fCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public System.Data.DataSet varCondition {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void Z_RFC_EC503_FORPURCompletedEventHandler(object sender, Z_RFC_EC503_FORPURCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Z_RFC_EC503_FORPURCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Z_RFC_EC503_FORPURCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void Z_RFC_SYN_503_MODEL_BUCompletedEventHandler(object sender, Z_RFC_SYN_503_MODEL_BUCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Z_RFC_SYN_503_MODEL_BUCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Z_RFC_SYN_503_MODEL_BUCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void Z_RFC_GET503PACKINGCompletedEventHandler(object sender, Z_RFC_GET503PACKINGCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Z_RFC_GET503PACKINGCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Z_RFC_GET503PACKINGCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public System.Data.DataSet varCondition {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void ZRFC_503_EXCHANGE_RATECompletedEventHandler(object sender, ZRFC_503_EXCHANGE_RATECompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ZRFC_503_EXCHANGE_RATECompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ZRFC_503_EXCHANGE_RATECompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void Z_EC_GETMAT_RFC_LOTCompletedEventHandler(object sender, Z_EC_GETMAT_RFC_LOTCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Z_EC_GETMAT_RFC_LOTCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Z_EC_GETMAT_RFC_LOTCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void ZBAPI_PO_CREATE1_851POCompletedEventHandler(object sender, ZBAPI_PO_CREATE1_851POCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ZBAPI_PO_CREATE1_851POCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ZBAPI_PO_CREATE1_851POCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void ZBAPI_PO_CREATE1_851PO_DeleteCompletedEventHandler(object sender, ZBAPI_PO_CREATE1_851PO_DeleteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ZBAPI_PO_CREATE1_851PO_DeleteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ZBAPI_PO_CREATE1_851PO_DeleteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void GetExportCustomsDataItemCompletedEventHandler(object sender, GetExportCustomsDataItemCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetExportCustomsDataItemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetExportCustomsDataItemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void ZRFC_46PO_RECORDCompletedEventHandler(object sender, ZRFC_46PO_RECORDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ZRFC_46PO_RECORDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ZRFC_46PO_RECORDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void Z_MM_RFC_POSTYCNCompletedEventHandler(object sender, Z_MM_RFC_POSTYCNCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Z_MM_RFC_POSTYCNCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Z_MM_RFC_POSTYCNCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void Z_RFC_PACKING_POSTCompletedEventHandler(object sender, Z_RFC_PACKING_POSTCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Z_RFC_PACKING_POSTCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Z_RFC_PACKING_POSTCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void Z_RFC_PACKING_POST_MCompletedEventHandler(object sender, Z_RFC_PACKING_POST_MCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Z_RFC_PACKING_POST_MCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Z_RFC_PACKING_POST_MCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void Z_RFC_SCRAP_ZSC1_POSTCompletedEventHandler(object sender, Z_RFC_SCRAP_ZSC1_POSTCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Z_RFC_SCRAP_ZSC1_POSTCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Z_RFC_SCRAP_ZSC1_POSTCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void Z_MM_RFC_COMPARE_QWMSSAPCompletedEventHandler(object sender, Z_MM_RFC_COMPARE_QWMSSAPCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Z_MM_RFC_COMPARE_QWMSSAPCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Z_MM_RFC_COMPARE_QWMSSAPCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void Z_MM_RFC_PACKING_TO_QWMSCompletedEventHandler(object sender, Z_MM_RFC_PACKING_TO_QWMSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Z_MM_RFC_PACKING_TO_QWMSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Z_MM_RFC_PACKING_TO_QWMSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void Z_RFC_PCBA_LIKE_ZCL2CompletedEventHandler(object sender, Z_RFC_PCBA_LIKE_ZCL2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Z_RFC_PCBA_LIKE_ZCL2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Z_RFC_PCBA_LIKE_ZCL2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void Z_RFC_MRPCODECompletedEventHandler(object sender, Z_RFC_MRPCODECompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Z_RFC_MRPCODECompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Z_RFC_MRPCODECompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void Z_MM_RFC_POSTYCN_QMMCCompletedEventHandler(object sender, Z_MM_RFC_POSTYCN_QMMCCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Z_MM_RFC_POSTYCN_QMMCCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Z_MM_RFC_POSTYCN_QMMCCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void ZRFC_MM_SENDE_EDI_46POCompletedEventHandler(object sender, ZRFC_MM_SENDE_EDI_46POCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ZRFC_MM_SENDE_EDI_46POCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ZRFC_MM_SENDE_EDI_46POCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void Z_MM_RFC_DIAOBO_QWMS_TO_SAPCompletedEventHandler(object sender, Z_MM_RFC_DIAOBO_QWMS_TO_SAPCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Z_MM_RFC_DIAOBO_QWMS_TO_SAPCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Z_MM_RFC_DIAOBO_QWMS_TO_SAPCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void Z_RFC_SCRAP_GR_QWMSCompletedEventHandler(object sender, Z_RFC_SCRAP_GR_QWMSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Z_RFC_SCRAP_GR_QWMSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Z_RFC_SCRAP_GR_QWMSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void Z_MM_RFC_ZBRF_DATA_TO_RCCompletedEventHandler(object sender, Z_MM_RFC_ZBRF_DATA_TO_RCCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Z_MM_RFC_ZBRF_DATA_TO_RCCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Z_MM_RFC_ZBRF_DATA_TO_RCCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void Z_RFC_ZSCRAP_TO_QWMSCompletedEventHandler(object sender, Z_RFC_ZSCRAP_TO_QWMSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Z_RFC_ZSCRAP_TO_QWMSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Z_RFC_ZSCRAP_TO_QWMSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591