//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace QCI_QWMS_IQCBRMaterial.MailService {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SendMailServiceSoap", Namespace="http://tempuri.org/")]
    public partial class SendMailService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SendMailNoticeOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendMailOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendMailSmtpAuthenticationOperationCompleted;
        
        private System.Threading.SendOrPostCallback SimplifySendMailOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendEmailInsertQueueOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendMobileNoticeOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendSMSNoticeOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendSMSByPhoneIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendSMSByPhoneIDOrderOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendSMSByEmployeeIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendSMSByEmployeeIDOrderOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendUnicomSMSByPhoneIDOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SendMailService() {
            this.Url = global::QCI_QWMS_IQCBRMaterial.Properties.Settings.Default.QCI_QWMS_IQCBRMaterial_MailService_SendMailService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SendMailNoticeCompletedEventHandler SendMailNoticeCompleted;
        
        /// <remarks/>
        public event SendMailCompletedEventHandler SendMailCompleted;
        
        /// <remarks/>
        public event SendMailSmtpAuthenticationCompletedEventHandler SendMailSmtpAuthenticationCompleted;
        
        /// <remarks/>
        public event SimplifySendMailCompletedEventHandler SimplifySendMailCompleted;
        
        /// <remarks/>
        public event SendEmailInsertQueueCompletedEventHandler SendEmailInsertQueueCompleted;
        
        /// <remarks/>
        public event SendMobileNoticeCompletedEventHandler SendMobileNoticeCompleted;
        
        /// <remarks/>
        public event SendSMSNoticeCompletedEventHandler SendSMSNoticeCompleted;
        
        /// <remarks/>
        public event SendSMSByPhoneIDCompletedEventHandler SendSMSByPhoneIDCompleted;
        
        /// <remarks/>
        public event SendSMSByPhoneIDOrderCompletedEventHandler SendSMSByPhoneIDOrderCompleted;
        
        /// <remarks/>
        public event SendSMSByEmployeeIDCompletedEventHandler SendSMSByEmployeeIDCompleted;
        
        /// <remarks/>
        public event SendSMSByEmployeeIDOrderCompletedEventHandler SendSMSByEmployeeIDOrderCompleted;
        
        /// <remarks/>
        public event SendUnicomSMSByPhoneIDCompletedEventHandler SendUnicomSMSByPhoneIDCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendMailNotice", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool SendMailNotice(string Site, string TeamPwd, string From, string To, string Cc, string Bcc, string Subject, string Body, bool IsBodyHtml, string Attachments, string UserName, string Password, out string LogID, out string ErrorMessage) {
            object[] results = this.Invoke("SendMailNotice", new object[] {
                        Site,
                        TeamPwd,
                        From,
                        To,
                        Cc,
                        Bcc,
                        Subject,
                        Body,
                        IsBodyHtml,
                        Attachments,
                        UserName,
                        Password});
            LogID = ((string)(results[1]));
            ErrorMessage = ((string)(results[2]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void SendMailNoticeAsync(string Site, string TeamPwd, string From, string To, string Cc, string Bcc, string Subject, string Body, bool IsBodyHtml, string Attachments, string UserName, string Password) {
            this.SendMailNoticeAsync(Site, TeamPwd, From, To, Cc, Bcc, Subject, Body, IsBodyHtml, Attachments, UserName, Password, null);
        }
        
        /// <remarks/>
        public void SendMailNoticeAsync(string Site, string TeamPwd, string From, string To, string Cc, string Bcc, string Subject, string Body, bool IsBodyHtml, string Attachments, string UserName, string Password, object userState) {
            if ((this.SendMailNoticeOperationCompleted == null)) {
                this.SendMailNoticeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendMailNoticeOperationCompleted);
            }
            this.InvokeAsync("SendMailNotice", new object[] {
                        Site,
                        TeamPwd,
                        From,
                        To,
                        Cc,
                        Bcc,
                        Subject,
                        Body,
                        IsBodyHtml,
                        Attachments,
                        UserName,
                        Password}, this.SendMailNoticeOperationCompleted, userState);
        }
        
        private void OnSendMailNoticeOperationCompleted(object arg) {
            if ((this.SendMailNoticeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendMailNoticeCompleted(this, new SendMailNoticeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendMail", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool SendMail(string TeamPwd, bool IsBodyHtml, string From, string To, string Cc, string Bcc, string Subject, string Body, string Attachments, out string Mgs) {
            object[] results = this.Invoke("SendMail", new object[] {
                        TeamPwd,
                        IsBodyHtml,
                        From,
                        To,
                        Cc,
                        Bcc,
                        Subject,
                        Body,
                        Attachments});
            Mgs = ((string)(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void SendMailAsync(string TeamPwd, bool IsBodyHtml, string From, string To, string Cc, string Bcc, string Subject, string Body, string Attachments) {
            this.SendMailAsync(TeamPwd, IsBodyHtml, From, To, Cc, Bcc, Subject, Body, Attachments, null);
        }
        
        /// <remarks/>
        public void SendMailAsync(string TeamPwd, bool IsBodyHtml, string From, string To, string Cc, string Bcc, string Subject, string Body, string Attachments, object userState) {
            if ((this.SendMailOperationCompleted == null)) {
                this.SendMailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendMailOperationCompleted);
            }
            this.InvokeAsync("SendMail", new object[] {
                        TeamPwd,
                        IsBodyHtml,
                        From,
                        To,
                        Cc,
                        Bcc,
                        Subject,
                        Body,
                        Attachments}, this.SendMailOperationCompleted, userState);
        }
        
        private void OnSendMailOperationCompleted(object arg) {
            if ((this.SendMailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendMailCompleted(this, new SendMailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendMailSmtpAuthentication", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool SendMailSmtpAuthentication(string TeamPwd, bool IsBodyHtml, string From, string To, string Cc, string Bcc, string Subject, string Body, string Attachments, string UserName, string Password, out string Mgs) {
            object[] results = this.Invoke("SendMailSmtpAuthentication", new object[] {
                        TeamPwd,
                        IsBodyHtml,
                        From,
                        To,
                        Cc,
                        Bcc,
                        Subject,
                        Body,
                        Attachments,
                        UserName,
                        Password});
            Mgs = ((string)(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void SendMailSmtpAuthenticationAsync(string TeamPwd, bool IsBodyHtml, string From, string To, string Cc, string Bcc, string Subject, string Body, string Attachments, string UserName, string Password) {
            this.SendMailSmtpAuthenticationAsync(TeamPwd, IsBodyHtml, From, To, Cc, Bcc, Subject, Body, Attachments, UserName, Password, null);
        }
        
        /// <remarks/>
        public void SendMailSmtpAuthenticationAsync(string TeamPwd, bool IsBodyHtml, string From, string To, string Cc, string Bcc, string Subject, string Body, string Attachments, string UserName, string Password, object userState) {
            if ((this.SendMailSmtpAuthenticationOperationCompleted == null)) {
                this.SendMailSmtpAuthenticationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendMailSmtpAuthenticationOperationCompleted);
            }
            this.InvokeAsync("SendMailSmtpAuthentication", new object[] {
                        TeamPwd,
                        IsBodyHtml,
                        From,
                        To,
                        Cc,
                        Bcc,
                        Subject,
                        Body,
                        Attachments,
                        UserName,
                        Password}, this.SendMailSmtpAuthenticationOperationCompleted, userState);
        }
        
        private void OnSendMailSmtpAuthenticationOperationCompleted(object arg) {
            if ((this.SendMailSmtpAuthenticationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendMailSmtpAuthenticationCompleted(this, new SendMailSmtpAuthenticationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SimplifySendMail", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool SimplifySendMail(string TeamPwd, bool IsHtml, string FromAddress, string ToAddress, string Subject, string Body, out string Mgs) {
            object[] results = this.Invoke("SimplifySendMail", new object[] {
                        TeamPwd,
                        IsHtml,
                        FromAddress,
                        ToAddress,
                        Subject,
                        Body});
            Mgs = ((string)(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void SimplifySendMailAsync(string TeamPwd, bool IsHtml, string FromAddress, string ToAddress, string Subject, string Body) {
            this.SimplifySendMailAsync(TeamPwd, IsHtml, FromAddress, ToAddress, Subject, Body, null);
        }
        
        /// <remarks/>
        public void SimplifySendMailAsync(string TeamPwd, bool IsHtml, string FromAddress, string ToAddress, string Subject, string Body, object userState) {
            if ((this.SimplifySendMailOperationCompleted == null)) {
                this.SimplifySendMailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSimplifySendMailOperationCompleted);
            }
            this.InvokeAsync("SimplifySendMail", new object[] {
                        TeamPwd,
                        IsHtml,
                        FromAddress,
                        ToAddress,
                        Subject,
                        Body}, this.SimplifySendMailOperationCompleted, userState);
        }
        
        private void OnSimplifySendMailOperationCompleted(object arg) {
            if ((this.SimplifySendMailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SimplifySendMailCompleted(this, new SimplifySendMailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendEmailInsertQueue", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool SendEmailInsertQueue(string Site, string TeamPwd, string From, string To, string Cc, string Bcc, string Subject, string Body, bool IsBodyHtml, string Attachments, string UserName, string Password, out string ErrorMessage) {
            object[] results = this.Invoke("SendEmailInsertQueue", new object[] {
                        Site,
                        TeamPwd,
                        From,
                        To,
                        Cc,
                        Bcc,
                        Subject,
                        Body,
                        IsBodyHtml,
                        Attachments,
                        UserName,
                        Password});
            ErrorMessage = ((string)(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void SendEmailInsertQueueAsync(string Site, string TeamPwd, string From, string To, string Cc, string Bcc, string Subject, string Body, bool IsBodyHtml, string Attachments, string UserName, string Password) {
            this.SendEmailInsertQueueAsync(Site, TeamPwd, From, To, Cc, Bcc, Subject, Body, IsBodyHtml, Attachments, UserName, Password, null);
        }
        
        /// <remarks/>
        public void SendEmailInsertQueueAsync(string Site, string TeamPwd, string From, string To, string Cc, string Bcc, string Subject, string Body, bool IsBodyHtml, string Attachments, string UserName, string Password, object userState) {
            if ((this.SendEmailInsertQueueOperationCompleted == null)) {
                this.SendEmailInsertQueueOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendEmailInsertQueueOperationCompleted);
            }
            this.InvokeAsync("SendEmailInsertQueue", new object[] {
                        Site,
                        TeamPwd,
                        From,
                        To,
                        Cc,
                        Bcc,
                        Subject,
                        Body,
                        IsBodyHtml,
                        Attachments,
                        UserName,
                        Password}, this.SendEmailInsertQueueOperationCompleted, userState);
        }
        
        private void OnSendEmailInsertQueueOperationCompleted(object arg) {
            if ((this.SendEmailInsertQueueCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendEmailInsertQueueCompleted(this, new SendEmailInsertQueueCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendMobileNotice", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool SendMobileNotice(string Site, string TeamPwd, string FromEmployeeID, string ToEmployeeID, string Body, out string LogID, out string ErrorMessage) {
            object[] results = this.Invoke("SendMobileNotice", new object[] {
                        Site,
                        TeamPwd,
                        FromEmployeeID,
                        ToEmployeeID,
                        Body});
            LogID = ((string)(results[1]));
            ErrorMessage = ((string)(results[2]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void SendMobileNoticeAsync(string Site, string TeamPwd, string FromEmployeeID, string ToEmployeeID, string Body) {
            this.SendMobileNoticeAsync(Site, TeamPwd, FromEmployeeID, ToEmployeeID, Body, null);
        }
        
        /// <remarks/>
        public void SendMobileNoticeAsync(string Site, string TeamPwd, string FromEmployeeID, string ToEmployeeID, string Body, object userState) {
            if ((this.SendMobileNoticeOperationCompleted == null)) {
                this.SendMobileNoticeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendMobileNoticeOperationCompleted);
            }
            this.InvokeAsync("SendMobileNotice", new object[] {
                        Site,
                        TeamPwd,
                        FromEmployeeID,
                        ToEmployeeID,
                        Body}, this.SendMobileNoticeOperationCompleted, userState);
        }
        
        private void OnSendMobileNoticeOperationCompleted(object arg) {
            if ((this.SendMobileNoticeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendMobileNoticeCompleted(this, new SendMobileNoticeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendSMSNotice", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool SendSMSNotice(string TeamPwd, string FromEmployeeID, string ToEmployeeID, string Body) {
            object[] results = this.Invoke("SendSMSNotice", new object[] {
                        TeamPwd,
                        FromEmployeeID,
                        ToEmployeeID,
                        Body});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void SendSMSNoticeAsync(string TeamPwd, string FromEmployeeID, string ToEmployeeID, string Body) {
            this.SendSMSNoticeAsync(TeamPwd, FromEmployeeID, ToEmployeeID, Body, null);
        }
        
        /// <remarks/>
        public void SendSMSNoticeAsync(string TeamPwd, string FromEmployeeID, string ToEmployeeID, string Body, object userState) {
            if ((this.SendSMSNoticeOperationCompleted == null)) {
                this.SendSMSNoticeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendSMSNoticeOperationCompleted);
            }
            this.InvokeAsync("SendSMSNotice", new object[] {
                        TeamPwd,
                        FromEmployeeID,
                        ToEmployeeID,
                        Body}, this.SendSMSNoticeOperationCompleted, userState);
        }
        
        private void OnSendSMSNoticeOperationCompleted(object arg) {
            if ((this.SendSMSNoticeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendSMSNoticeCompleted(this, new SendSMSNoticeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendSMSByPhoneID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool SendSMSByPhoneID(string Site, string Unit, string TeamPwd, string PhoneID, string SMSContent, ref string Mgs) {
            object[] results = this.Invoke("SendSMSByPhoneID", new object[] {
                        Site,
                        Unit,
                        TeamPwd,
                        PhoneID,
                        SMSContent,
                        Mgs});
            Mgs = ((string)(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void SendSMSByPhoneIDAsync(string Site, string Unit, string TeamPwd, string PhoneID, string SMSContent, string Mgs) {
            this.SendSMSByPhoneIDAsync(Site, Unit, TeamPwd, PhoneID, SMSContent, Mgs, null);
        }
        
        /// <remarks/>
        public void SendSMSByPhoneIDAsync(string Site, string Unit, string TeamPwd, string PhoneID, string SMSContent, string Mgs, object userState) {
            if ((this.SendSMSByPhoneIDOperationCompleted == null)) {
                this.SendSMSByPhoneIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendSMSByPhoneIDOperationCompleted);
            }
            this.InvokeAsync("SendSMSByPhoneID", new object[] {
                        Site,
                        Unit,
                        TeamPwd,
                        PhoneID,
                        SMSContent,
                        Mgs}, this.SendSMSByPhoneIDOperationCompleted, userState);
        }
        
        private void OnSendSMSByPhoneIDOperationCompleted(object arg) {
            if ((this.SendSMSByPhoneIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendSMSByPhoneIDCompleted(this, new SendSMSByPhoneIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendSMSByPhoneIDOrder", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool SendSMSByPhoneIDOrder(string Site, string Unit, string TeamPwd, string PhoneID, string SMSContent, string OrderTime, ref string Mgs) {
            object[] results = this.Invoke("SendSMSByPhoneIDOrder", new object[] {
                        Site,
                        Unit,
                        TeamPwd,
                        PhoneID,
                        SMSContent,
                        OrderTime,
                        Mgs});
            Mgs = ((string)(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void SendSMSByPhoneIDOrderAsync(string Site, string Unit, string TeamPwd, string PhoneID, string SMSContent, string OrderTime, string Mgs) {
            this.SendSMSByPhoneIDOrderAsync(Site, Unit, TeamPwd, PhoneID, SMSContent, OrderTime, Mgs, null);
        }
        
        /// <remarks/>
        public void SendSMSByPhoneIDOrderAsync(string Site, string Unit, string TeamPwd, string PhoneID, string SMSContent, string OrderTime, string Mgs, object userState) {
            if ((this.SendSMSByPhoneIDOrderOperationCompleted == null)) {
                this.SendSMSByPhoneIDOrderOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendSMSByPhoneIDOrderOperationCompleted);
            }
            this.InvokeAsync("SendSMSByPhoneIDOrder", new object[] {
                        Site,
                        Unit,
                        TeamPwd,
                        PhoneID,
                        SMSContent,
                        OrderTime,
                        Mgs}, this.SendSMSByPhoneIDOrderOperationCompleted, userState);
        }
        
        private void OnSendSMSByPhoneIDOrderOperationCompleted(object arg) {
            if ((this.SendSMSByPhoneIDOrderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendSMSByPhoneIDOrderCompleted(this, new SendSMSByPhoneIDOrderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendSMSByEmployeeID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool SendSMSByEmployeeID(string Site, string Unit, string TeamPwd, string ToEmployeeID, string SMSContent, ref string Mgs) {
            object[] results = this.Invoke("SendSMSByEmployeeID", new object[] {
                        Site,
                        Unit,
                        TeamPwd,
                        ToEmployeeID,
                        SMSContent,
                        Mgs});
            Mgs = ((string)(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void SendSMSByEmployeeIDAsync(string Site, string Unit, string TeamPwd, string ToEmployeeID, string SMSContent, string Mgs) {
            this.SendSMSByEmployeeIDAsync(Site, Unit, TeamPwd, ToEmployeeID, SMSContent, Mgs, null);
        }
        
        /// <remarks/>
        public void SendSMSByEmployeeIDAsync(string Site, string Unit, string TeamPwd, string ToEmployeeID, string SMSContent, string Mgs, object userState) {
            if ((this.SendSMSByEmployeeIDOperationCompleted == null)) {
                this.SendSMSByEmployeeIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendSMSByEmployeeIDOperationCompleted);
            }
            this.InvokeAsync("SendSMSByEmployeeID", new object[] {
                        Site,
                        Unit,
                        TeamPwd,
                        ToEmployeeID,
                        SMSContent,
                        Mgs}, this.SendSMSByEmployeeIDOperationCompleted, userState);
        }
        
        private void OnSendSMSByEmployeeIDOperationCompleted(object arg) {
            if ((this.SendSMSByEmployeeIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendSMSByEmployeeIDCompleted(this, new SendSMSByEmployeeIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendSMSByEmployeeIDOrder", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool SendSMSByEmployeeIDOrder(string Site, string Unit, string TeamPwd, string ToEmployeeID, string SMSContent, string OrderTime, ref string Mgs) {
            object[] results = this.Invoke("SendSMSByEmployeeIDOrder", new object[] {
                        Site,
                        Unit,
                        TeamPwd,
                        ToEmployeeID,
                        SMSContent,
                        OrderTime,
                        Mgs});
            Mgs = ((string)(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void SendSMSByEmployeeIDOrderAsync(string Site, string Unit, string TeamPwd, string ToEmployeeID, string SMSContent, string OrderTime, string Mgs) {
            this.SendSMSByEmployeeIDOrderAsync(Site, Unit, TeamPwd, ToEmployeeID, SMSContent, OrderTime, Mgs, null);
        }
        
        /// <remarks/>
        public void SendSMSByEmployeeIDOrderAsync(string Site, string Unit, string TeamPwd, string ToEmployeeID, string SMSContent, string OrderTime, string Mgs, object userState) {
            if ((this.SendSMSByEmployeeIDOrderOperationCompleted == null)) {
                this.SendSMSByEmployeeIDOrderOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendSMSByEmployeeIDOrderOperationCompleted);
            }
            this.InvokeAsync("SendSMSByEmployeeIDOrder", new object[] {
                        Site,
                        Unit,
                        TeamPwd,
                        ToEmployeeID,
                        SMSContent,
                        OrderTime,
                        Mgs}, this.SendSMSByEmployeeIDOrderOperationCompleted, userState);
        }
        
        private void OnSendSMSByEmployeeIDOrderOperationCompleted(object arg) {
            if ((this.SendSMSByEmployeeIDOrderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendSMSByEmployeeIDOrderCompleted(this, new SendSMSByEmployeeIDOrderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendUnicomSMSByPhoneID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool SendUnicomSMSByPhoneID(string Site, string TeamName, string TeamPwd, string Unit, string PhoneID, string SMSContent, string LogID, string Key, ref string Mgs) {
            object[] results = this.Invoke("SendUnicomSMSByPhoneID", new object[] {
                        Site,
                        TeamName,
                        TeamPwd,
                        Unit,
                        PhoneID,
                        SMSContent,
                        LogID,
                        Key,
                        Mgs});
            Mgs = ((string)(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void SendUnicomSMSByPhoneIDAsync(string Site, string TeamName, string TeamPwd, string Unit, string PhoneID, string SMSContent, string LogID, string Key, string Mgs) {
            this.SendUnicomSMSByPhoneIDAsync(Site, TeamName, TeamPwd, Unit, PhoneID, SMSContent, LogID, Key, Mgs, null);
        }
        
        /// <remarks/>
        public void SendUnicomSMSByPhoneIDAsync(string Site, string TeamName, string TeamPwd, string Unit, string PhoneID, string SMSContent, string LogID, string Key, string Mgs, object userState) {
            if ((this.SendUnicomSMSByPhoneIDOperationCompleted == null)) {
                this.SendUnicomSMSByPhoneIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendUnicomSMSByPhoneIDOperationCompleted);
            }
            this.InvokeAsync("SendUnicomSMSByPhoneID", new object[] {
                        Site,
                        TeamName,
                        TeamPwd,
                        Unit,
                        PhoneID,
                        SMSContent,
                        LogID,
                        Key,
                        Mgs}, this.SendUnicomSMSByPhoneIDOperationCompleted, userState);
        }
        
        private void OnSendUnicomSMSByPhoneIDOperationCompleted(object arg) {
            if ((this.SendUnicomSMSByPhoneIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendUnicomSMSByPhoneIDCompleted(this, new SendUnicomSMSByPhoneIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void SendMailNoticeCompletedEventHandler(object sender, SendMailNoticeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendMailNoticeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendMailNoticeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string LogID {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string ErrorMessage {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void SendMailCompletedEventHandler(object sender, SendMailCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendMailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendMailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string Mgs {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void SendMailSmtpAuthenticationCompletedEventHandler(object sender, SendMailSmtpAuthenticationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendMailSmtpAuthenticationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendMailSmtpAuthenticationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string Mgs {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void SimplifySendMailCompletedEventHandler(object sender, SimplifySendMailCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SimplifySendMailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SimplifySendMailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string Mgs {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void SendEmailInsertQueueCompletedEventHandler(object sender, SendEmailInsertQueueCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendEmailInsertQueueCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendEmailInsertQueueCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string ErrorMessage {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void SendMobileNoticeCompletedEventHandler(object sender, SendMobileNoticeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendMobileNoticeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendMobileNoticeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string LogID {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string ErrorMessage {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void SendSMSNoticeCompletedEventHandler(object sender, SendSMSNoticeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendSMSNoticeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendSMSNoticeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void SendSMSByPhoneIDCompletedEventHandler(object sender, SendSMSByPhoneIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendSMSByPhoneIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendSMSByPhoneIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string Mgs {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void SendSMSByPhoneIDOrderCompletedEventHandler(object sender, SendSMSByPhoneIDOrderCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendSMSByPhoneIDOrderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendSMSByPhoneIDOrderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string Mgs {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void SendSMSByEmployeeIDCompletedEventHandler(object sender, SendSMSByEmployeeIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendSMSByEmployeeIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendSMSByEmployeeIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string Mgs {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void SendSMSByEmployeeIDOrderCompletedEventHandler(object sender, SendSMSByEmployeeIDOrderCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendSMSByEmployeeIDOrderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendSMSByEmployeeIDOrderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string Mgs {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void SendUnicomSMSByPhoneIDCompletedEventHandler(object sender, SendUnicomSMSByPhoneIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendUnicomSMSByPhoneIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendUnicomSMSByPhoneIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string Mgs {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
}

#pragma warning restore 1591